extraCaCerts: ENC[AES256_GCM,data:jxVVgmZI7iAGnvqHbRgyQBdWHWmlWwwXAoXukZ1CK9s95JOfHyCVAWuHNCmaLkuBEuXWUxLCWNBCoGNnQSqLtJ1kL6Da+QXxcqS/MxNL1abgflbjFyfJAD0f92li8DO/3w68B+kXPreUd5vCbBhJMzB1B+RGWu6o99LOwY5HVNrRyVXM4Il8HaLivjhgcY3wTa5uEoVVQfKuHSk11WTU8iuneDfVGT+OIO6alxG8xSWnFwU/9Gql0iDzNmt6jqpvj0de83/poucihO/jJQeIY5vOrmyUG36wJB2UmY2KD6gzKh8nypSKrYG8D8yMTFIeYKKnhQ7vCbkgtyv6ciEVGgtrunR0/Rg16l/SFXu9E/sRzUevVfZEnwvOVAGzgiJbd3cFqfTPJjR135BDv6lK118kunFHXziylUH0RVWMB8pv1HM4/7izSrYeu6/r3RPlnVv5/RyXrnShfwX2cAmlDppDUkhPmjSTaVmGylknELN0sEABmLI1iguakcpywF7MLXLr3R5WnO/tXeCdTl1rf83azMr5cP2xMXeCzemRIGDLctBhGeYFoKbYTJuJ3tdOsUnp9E5lrCAIqc28PAMSd8uEWIdvIxzVdRYWDBRsLnXFb86aKZ2w4mQgEQeFUzFj/Sv6v44vNFhNR0kJwB6pA/QSwowqx0pSwaKCQVqCdrb0oF5oqiOvWHU+z67EBnXRFflB1A+2ljpjNgku5YscrHOG0DrxscC0YSYwBUjpkB/7FrBao2S1EaMGwX7t,iv:j8n5llJdvaSrfOioI1EYElaegAQZ6J5L544pu+Q3I9Q=,tag:qkWSP/TPlEt0yQH8mIrbIA==,type:str]
csiDriver:
  name: ENC[AES256_GCM,data:8Wykqwv4AJvUIDLk5Lzlcw==,iv:PDxQckmIssmfGRc2l15MdKrpW2YV+fpL64rl9gWqUHc=,tag:Os7hlJkw9yFcuseqkLFNXw==,type:str]
  fsGroupPolicy: ENC[AES256_GCM,data:AZgWTA==,iv:9l8HnhVDHWNyQTIAbQ1lxYCHxfK4fdxAlu/TPs6mMn4=,tag:SH7QArPUGX55sSleLAlO+g==,type:str]
storageClasses:
  - name: ENC[AES256_GCM,data:dJWyEythO3RUeiDh6LkbTg==,iv:JkEF81lvspCYgY6lJRUqIWjBLz9J7ArPhG9hWFszUDo=,tag:FjkYyyVcJr7YBx0I6+NwBg==,type:str]
    defaultClass: ENC[AES256_GCM,data:pJSZwe8=,iv:C7NCO1mjaJp7UpvzEybf6hSjuv/Oz9nD+ZJKjIfoaRY=,tag:tkE4WEhEnLT0GLYIBkgJ1g==,type:bool]
    reclaimPolicy: ENC[AES256_GCM,data:8dLpnE3n,iv:ZZm0TrUne0WLe0uhIchNq6c9eDP2+brR2NrKd7+7DJU=,tag:Aaj55peAWKfp/KKecj6Dkw==,type:str]
    volumeBindingMode: ENC[AES256_GCM,data:LS6F3GFEvXEe,iv:8mlftzp9HHsiBR1k70iKcDdb9B8nos4ZtekgqHMWLqg=,tag:QKW9HIkDIEcG3o30E4hMvw==,type:str]
    allowVolumeExpansion: ENC[AES256_GCM,data:CWhCog==,iv:XkiObnwfrbJ8n1aapzmcqXQ82RxDS0qyEOSAYAI49So=,tag:jmykSuE4T6U100gh75/98Q==,type:bool]
    parameters:
      fsType: ENC[AES256_GCM,data:PmkQ,iv:fCEVNpQg+3etoDcCSTSU/Zzq0dGwRajfoQ1mfZvKP0M=,tag:OPIYb/45KTa1uytlgRM/5w==,type:str]
    mountOptions:
      - ENC[AES256_GCM,data:EqQeZ412Ng==,iv:TM0BgkXJfQPuob9f7mXy3hmdmoscpLtRTgjHyLtIlXc=,tag:PTFAC4jaizR5NLIXysuwZQ==,type:str]
      - ENC[AES256_GCM,data:PV3m0DqLUOb7,iv:tN+vo6BeO+1W8LGRkf/yXIomwMjIuHbwLDnVWzzqEao=,tag:FtPvo/xIHTZJubtitUAlgA==,type:str]
driver:
  config:
    driver: ENC[AES256_GCM,data:GZ38ma0/8yToIlyXhmtF,iv:l/wdVuBiH75ETf3AqVpRnuQeDvI5a3eQnyez1KZTBCs=,tag:VMp7wmro1Z54UIzOCdUUrQ==,type:str]
    instance_id: ENC[AES256_GCM,data:Vbj7gfV4m/Ailpo=,iv:OEXnvRtBj+YQaDBkrC2YDIZc+3i5jrwknjLePk17KnQ=,tag:w0KzCTm5CCxnm53tYFQgOA==,type:str]
    httpConnection:
      protocol: ENC[AES256_GCM,data:Xtg3He0=,iv:xn735Wd8bqG2b1Z+GoTGu3QER26CyrG55XRJ7S8Fz8E=,tag:yw5cBkdVDlwAHPcEqaOoUA==,type:str]
      host: ENC[AES256_GCM,data:qJ3JIGuH8tV0zE7sjsclnasjig9ZtFoCdQ==,iv:54JT+ZgPTa4u761EMbVDnjdWC4mKndaz3T2sKX7nXFo=,tag:IKeX+YaZVE5PRkean4lHNA==,type:str]
      port: ENC[AES256_GCM,data:cVi3,iv:Ml4+b4SsvzGUNKSl2+RjtPuotDw6weW6IsQ3PxtLtlM=,tag:tSlFv1t7zVSJV4KpRIZt6Q==,type:int]
      apiKey: ENC[AES256_GCM,data:jhcngoSvI/XK0umIEAvTTRx0116XQipoi5eM+fji+jddYHgPkyc4Z5sN2dPuBxBblSp2G/PgWKrSNS3Iw+UJhHAr,iv:LaeT4sE6G1UO8424f8eIZCkR6kqCRHmymg8HgLHElME=,tag:pimDfuMMUaX3PGuSSc+8lg==,type:str]
      apiVersion: ENC[AES256_GCM,data:xg==,iv:aGgwr+MCTw7/iy+qkV9RRavzvJwUQVP8ZDN6izDCNAI=,tag:m9Pxi+ZPpKBxrDDzhZcAzg==,type:int]
    zfs:
      datasetParentName: ENC[AES256_GCM,data:M26MO6BA9sLBhUj7,iv:i3SKk95DABkpnJIDLA0Ev2s8GXe6a3Fk3w8ipxC47fU=,tag:ExNHx39vnpS6m7G3mLi28g==,type:str]
      detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:6X7savVC1ZMSYVH1jmQWpgeo0ruyvg==,iv:tZQ5KSZNjZu00V7ryDVkpVcvzumM9HfdWsDiBPLo1m4=,tag:F3LdqAljavFJneN/3fwkKA==,type:str]
      datasetEnableQuotas: ENC[AES256_GCM,data:j+MlAw==,iv:i8TGSYWJJEKHuIbU/iKHtmYfBSPnAzc+QxXqpkzEiB4=,tag:IjPsyu1BEtgfyMzwOv2GLg==,type:bool]
      datasetPermissionsMode: ENC[AES256_GCM,data:VkAAHw==,iv:vtWHgP9uejozNMex15oyCkf2NZT2baWRQZ7ynPXwf8k=,tag:ugPqWh86vMsLD9Sf2WB9mw==,type:str]
      datasetPermissionsUser: ENC[AES256_GCM,data:XQ==,iv:urA30Ni3/OLZmeV2BndCe8blL1OaHyCZOilQTAYBZw8=,tag:kpgOHDfNZyAIbpe7sJndTQ==,type:int]
      datasetPermissionsGroup: ENC[AES256_GCM,data:Ww==,iv:nbh4Hkg1k+S8ObpQU81kyQbHYB4ZB0l+kvQbYqwBC1c=,tag:t1n8zdREymV2CgNgg9Wi3w==,type:int]
    nfs:
      shareHost: ENC[AES256_GCM,data:BuKOt88S9nDUvKMMUSR+YTKqXEQbMk1j9g==,iv:EbljdWHKtYSSSeHOuPT4cRNPRGAnFOLYWcRP6mpQbBc=,tag:N6FuMUFgLtiAZTdz/FeIag==,type:str]
      shareMaprootUser: ENC[AES256_GCM,data:WIrs5w==,iv:dQnGXsjELGJSIa98MWXBsg5bHesvpqMyamu3IAiZaXk=,tag:lCo+lsI+YJLEFJiWn1e1/w==,type:str]
      shareMaprootGroup: ENC[AES256_GCM,data:tx5msw==,iv:1dS0zqdKDQgYyPNUH9zJd2PHDGQR5d4k217j4cOMbyk=,tag:34SKXGWOpWz8z6BH8n84PQ==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQWk3SG5veFlJMTE5Sk9o
        VklMc2V1Y2d0M2krKzJ0SUZGQjJwZENvVWp3Cm5xQlA5VW9rbVY3a05UUUFTNDlK
        TDRzTDVvNHZ4UjVjTU9qYlQ4Wi95aWsKLS0tIHg4bU81b0lrczVQSHVRVUdOUkcv
        NTBrMXYwZUY3dExDRExlOFZiWlFwNmsKJzGV/A5igzFRWqybnbAlKaElMKgckFHr
        vP2ZuO4T83Wb8btHb1yeYDpsqTRINdNqToavRNFIsFqgxY+g+dWI1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T11:10:25Z"
  mac: ENC[AES256_GCM,data:A7eWCaqSeY839ndW6tPCBE6cP+tkowyfmJGvCYCwo1PnI1rCeufxHddbNTlQz/wWMwYT+k5iJiISsBYc+DYXZH6x7UvznA3zlg66kTMryny5VNQLS0YKSlzcBw6szFlMLvx9s6yfbt8ijheOUu+16HF6R6RLcmq3l4/VbPAyWzw=,iv:52+j7HQSYtLiaf+iO8HoAkbvk/iVs3Pm1YHy5xDkdM4=,tag:xCE/n41ERIZwLJhtmL/84w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
