extraCaCerts: ENC[AES256_GCM,data:9Qb9QCzjocNTDM+IFQhPPlZeKHVkIGbSH7JMzYfMIqHil44iqnESqaQWpLuayiH0qrP1X+OC902HFRc2EgI7cD5JQRkfQ/CC5BVh8U8r3keqKCWQrz7nNrV3clkmB5HkBy8rIPUfLh1cAT0ib4KlatTAx+uh7waJ5pg2weolmFRi2oeQsAV9fbnefIAvWP0nHhcCbo2AGZSaJnglNy0PSiNwFu5YRuD1Il0HheTkKBH9BUxsiNVoY4Iodj/jbGacjjjqLacVwxDQNHvAB+hNkXCEgw8f9LShmdjz3F3dF+i97Yq2t1wcNsOwnBD9508St3sim+MVDpczFh5ZP9f/9kvIDYwPG+lUXQVR6ABXVZ7Hz/kxgbnSi/rI1Wgxez9Jawn7TVN1cRXfULHx+OdAqG853UaLDqbDRFvgON79B9GucgU4apsBTOF0YNasFo7QL2+oCpRCpN5kLcXzbm+YHxXTUdmS+jpTEH+E586+FcahRQAfAiwZhrmnmW6Rz3YfCGwYMgzuQxM7BfcfpYOpBgCwxl7i1GJQJrka48LyywnoWzBkIHtU3n/tjPhy71pj54+sTHabuOhE50ieZiCns5FoSgm6jdcnuK2Hjl750D/EExxrk9AFAUSv0lFRkbC6POmFtU5l2cAnfKM6PWCDiRdKpHeQlrSF3wKWxio6KEs7F8kOi1nqlT4n1ouN8h1sfuNt4wZnHjiyNyXQuxjNytbLb/3qHEC1GIRwaRMwWJc9VPqOhqAz3zf4sPcN,iv:6t4moBrLimWb5ciLn4mvfxwLllB6205vBdr02Sskv5k=,tag:Nb+s1CDAyFzaiFiK5j871g==,type:str]
csiDriver:
  name: ENC[AES256_GCM,data:ED0ggLU8g7MiF+Uff/uUvw==,iv:yRQnO4eTxqtc7zWEurSk/qxa1o2TpUKA7Vlv/SoWXEw=,tag:bXRW1GkPffLPO2IkEWjV2Q==,type:str]
  fsGroupPolicy: ENC[AES256_GCM,data:roeYZA==,iv:CYGfsjKTfMcadN1uGJzSsw1YyslD9hol3QuXBNoEu5M=,tag:dN+K2ckSHcrP4ktMXB0KHw==,type:str]
storageClasses:
  - name: ENC[AES256_GCM,data:ufUY/Ml2p8AlfNDE4oMALg==,iv:0cwsYXOFceJCbiOBT/fV6OTjFTSUuVD4PZp825D/pjc=,tag:zUlwUp7Kxxprs9Cx/ugeSg==,type:str]
    defaultClass: ENC[AES256_GCM,data:v0yqA0M=,iv:VG299OSJGFGpRRksu33BBuTBo1iMlPc90YzP1Rkstdc=,tag:8qGjPH1eMrpXpW5rXWP1lA==,type:bool]
    reclaimPolicy: ENC[AES256_GCM,data:e1H+TQm7,iv:4ifOjrkFCPhPy3vfrMMsIZ4pybe9Cni/B9MVqQfXMXM=,tag:A4bxOWdZj+Hv1BlrsVfQ8g==,type:str]
    volumeBindingMode: ENC[AES256_GCM,data:9PyJUbOyUsKi,iv:PTxjb/GLguT8xdBkH+zJ+XxqJdYV2iaC5rp54Ue/Pvw=,tag:EprlEikdTaHOk1Iuk6NMAg==,type:str]
    allowVolumeExpansion: ENC[AES256_GCM,data:kif4wA==,iv:lBGZASn2s/+4RFW/AUOIW5AYXT4xLMBChbhaxiUFxlo=,tag:yKpzgf/RTwJQOJTGVrmbuA==,type:bool]
    parameters:
      fsType: ENC[AES256_GCM,data:j5oa,iv:m9W+mJlsa0KdAflZZZUuOzl8gxo7xp6RANE/FN1g6O0=,tag:eO/x3F9ARfGDyvlTxll/Mg==,type:str]
    mountOptions:
      - ENC[AES256_GCM,data:cVciOrYc9g==,iv:87/t/c22hh+OFG6uoRN09f09nE4+f+e5pvd8Na5CzuA=,tag:rIp/3G11IkZJhLQKOuDdvA==,type:str]
      - ENC[AES256_GCM,data:Y8RFiI6Uo9zB,iv:BN6bo+tsN3LGK68F0rf3n6gSB/IaAWspmcBMihFNhiI=,tag:xhs7ZbjCKmYNAdHx8zbTGw==,type:str]
driver:
  config:
    driver: ENC[AES256_GCM,data:r8jG8qV7FGFH/F+gRLp6,iv:f56tZABQUdRqhTOoXaco4eIay3Zy7OFFM2bsBj1aT5Q=,tag:2T4U2TDRlUj19lBudWELEQ==,type:str]
    instance_id: ENC[AES256_GCM,data:DnueAPy5xrUeV2M=,iv:ObvpMHK10ze1z7ZNXrhN2u6zqDY4embNwK+VCYPUnUw=,tag:z9MQsrLcjQhH/NYmkToGaQ==,type:str]
    httpConnection:
      protocol: ENC[AES256_GCM,data:jUWI++c=,iv:vjW8MwA9PTMnHnwquP/jRWPGd0XfvbXq5CfIdubLyU8=,tag:HBi+prHwcY9aPGTa+NOY6g==,type:str]
      host: ENC[AES256_GCM,data:zPBPPWRqsGiT2Prjy0gwcKugnQexcan9Kw==,iv:njdDsu9oK6ypIgmbPO6VaQY1e6QaxxZcxHG4PNhRayk=,tag:891ADpSr6KfHi/XmajHPhA==,type:str]
      port: ENC[AES256_GCM,data:vKxZ,iv:3AlxFrH91RDu0N4R+fkU+DZ2RKt7MZHen+MYsoNHR6k=,tag:EoB50JqDkLU2LZqi03gKxQ==,type:int]
      apiKey: ENC[AES256_GCM,data:LJWqBNlhCTUDSNK4pxNa+DnEExd+V+2HJfLdpizg2tErcPXRrJRGMvczJ40T2CrkDrgNhVviJ8W5sN3aU7n4mdRn,iv:tC8ml8a/9txjY5TaIaXWXLBFYv2wG0kMlC2GWyp4h3s=,tag:Z15cdXgm8to+lukPR2qfug==,type:str]
    zfs:
      datasetParentName: ENC[AES256_GCM,data:twDtyEk6WHGbXWH7,iv:CC7S18sturNqkiojJPAn6VCOFzxFrsTPmNRLSNhXe54=,tag:pgB5J7gijwaYIXF73l64lQ==,type:str]
      detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:LqtWtqOQcq2eAypPdCgFdEI8xQIYMQ==,iv:feeAHRJ+5VGrGx+I/O+SMPlVd/GB/Dxl9N/gx/fLlLA=,tag:PNW/gnMH0JTs6CARgqPwdQ==,type:str]
      datasetEnableQuotas: ENC[AES256_GCM,data:c93HJA==,iv:lWCKUubUdzZDDXVGDr6/nZBQRn3M8owRzufWJJocwB0=,tag:/q/TAFvpnH6Pyb+XVZVx5g==,type:bool]
      datasetPermissionsMode: ENC[AES256_GCM,data:dWxBFA==,iv:2aANH2YW/XwiTdg1AAVNPa3nb2NytS4/S18Mxyduxg0=,tag:ZgMBG1b2ARzmodrpPZIoVw==,type:str]
      datasetPermissionsUser: ENC[AES256_GCM,data:1g==,iv:pSjmEGIQ1VpPRDqjDKo3O5Tw+cXRCPa9nrGqMlkf+wk=,tag:RCJkWOoFTvskDbYP1pPLbQ==,type:int]
      datasetPermissionsGroup: ENC[AES256_GCM,data:dA==,iv:g+1P1JMITYt5gTKm027VAQ0KJdm0nxxdCOXwOKTjroA=,tag:5Jy3NqGvBko6iPF/3flp+w==,type:int]
    nfs:
      shareHost: ENC[AES256_GCM,data:HiXuejsVZe+z5BiqVXhKaT4ACet/eAgh+Q==,iv:u4W9tc3y3tcx7EuogBscLMWQwL+81NXrOkikDsyjefU=,tag:8HqslY1QxRyu1Ntm5/6jGw==,type:str]
      shareMaprootUser: ENC[AES256_GCM,data:m7Lsvg==,iv:dH1jXwZZ5NfczPzZdkcBUzd48bQkStBbK+ITCn6TV+E=,tag:S0cHxOZ0qAhyZrX6HvK3tw==,type:str]
      shareMaprootGroup: ENC[AES256_GCM,data:FZyE1w==,iv:Cn2IqrRoQtRNaJ/7t2tPByyI5giyKXy0DhQe5BCXFcc=,tag:ZKor62HW6luFslvNSdbARg==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUWhjL3pSYktJOEJzQUhj
        ZFplZEIyZFZkK0pVZ09JeFVJZzdSa1hoWnpFCll3N3hUakNXRGZlZTJDM3VQRGg1
        SEU2RnFIaFJ0dEltRWZHUEtZM3V2Z1kKLS0tIEhiQjdyZjdiNytoL01GaktPRzZY
        WnpZL0FtdVVqU3I1V1lycERZZmZsVnMKPLe8qK6G27G3KejE1tsVxcfM34MyIaBq
        UsjmKOJMOBj31MmRAYBHFDW4QwVLv+uOdPfcujSSzQ1t+QXDJGI7IQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T10:47:07Z"
  mac: ENC[AES256_GCM,data:Z9giwiGvVFgm5zBL7WKEueIg46zKKuPOD0sJz2J+G6bbI11gQemr6iJoOUui0Gfc1kNotF3DGxHcDtbaAkOogtAt7R9Y3XSgngQ59+9AxhyzWM2uBYMBQelUSkAH3F3crRr02BTpYlkwlr6P2iU278Vezt+WrxlMrzN9jXFpdfY=,iv:4LAHa0DvZa+r5gIxAxXoUCvNJaW/EgsDZidvfClC0H4=,tag:Gw1+sg4vMwHZWRGYlcv62A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
