extraCaCerts: ENC[AES256_GCM,data:wKuOVtTowFXIizzMOd9udqn/rhjGNHdbw0w+o4zueEws7BwMsEBbhviByKI8XB5UFiIFULYu4nX3edGBVHy4Od++BQsY+Du9fWlb2MnEtQTvdr2dLTDo+/gOfWEjFweWam9h7BMt3q27/4YIKMfcIJr56GuIpxmSyzE/zjuxM243v/zRsg9GwbHYL/vtqVocAi4WSZ5F6PmBCqkipXsPg6u8/lVHg5ku148XgTNEXhdkNhh4XNTB3mxqrDYjQrj+9Lif29g3uRroZpjKZgsS2kMoftPtSHKPa8mEJyxC6x8nzJK1xtgZ2AjMZzqYoAmptwtDpHGk5Sh633Iwc6MxrbSr8LmApAkv74F8aUeL++SfLcHLvLGhU7AFilzCeoeFcUBoq+33fbWAYR1Kc/8ZEDet0+6tROPfgOeRuGOn+Q3y9aMaGF+xlHLQGf8OjSxZoLivNCz2U29xh1aOSBYAlWTb1bX85kmQyXVAzukrb1u0qRpO91nVzGErNsDvwVHWTY0LojfHkM4h3/GceTU+rqYV74suWxsgXIbXbaMxyfR5jtkgop3zvbYcndku25MJSfh9r4WNKg4IjPuN0ytDrABikBq5y/+UL9adOqVTnikWBtTgq2Bq+OzHqD8qdloo9cu61KYAvsld+gPVCYV+hmqJaSOUMLLa/lXMBTiVJbUTO5TlZhYTfErBUQK49AxvC3PBZguvWmP9KudXj6OX6gKCxFaLcohhMZTPa2EUjKiziYm6QO20JLjvelan,iv:VrYghLljU/yx8fxT+DOaEj8bS7nXxEMPZG8VlHaKmBo=,tag:lblUkNlx5PPm4bVj2PI6ew==,type:str]
csiDriver:
  name: ENC[AES256_GCM,data:4rKVsutywBej0ZW0r4fAlQ==,iv:DDD64Gb+Z55MF3OWluUarkUKO1N7AZJ+eur95B/LL+8=,tag:wQ2o1KVi72mYDalOe4conw==,type:str]
  fsGroupPolicy: ENC[AES256_GCM,data:Pf7D4A==,iv:bBomMe+ssH5bjxf/0UObpSfZ1n08K53m7KCC08ML7/s=,tag:BFu+7aXopUmQcn4KDjGsvw==,type:str]
storageClasses:
  - name: ENC[AES256_GCM,data:/Q+sCtYUi9x+Jz4c1uW+4Q==,iv:n8/4PohdHDZQS/UjGCRr3WKy6j93XUTToEe2OOxFOYw=,tag:i4n7nJxhh7LysGoTM3X7Tg==,type:str]
    defaultClass: ENC[AES256_GCM,data:g4UHjnE=,iv:GjfElilrczY1nUE17iITUydNwcMNs5/+BFM9bmZ1iuU=,tag:lOeA4+tqlLGGUYhTWMT8Ow==,type:bool]
    reclaimPolicy: ENC[AES256_GCM,data:7y/iL7U8,iv:nC+YSz5GuyAhSk4aqzX+Dp9bsKhQzkuvXs46iyUQBFM=,tag:ohADiblf5Wt1KekUkp00Hg==,type:str]
    volumeBindingMode: ENC[AES256_GCM,data:lx8v8CaGshk6,iv:hPQA6dIznpQQV9IKRs9rAW8L7wER9EU9ZedDyBwswsU=,tag:ICpr7ZLtljbRmfDx1Eqmjw==,type:str]
    allowVolumeExpansion: ENC[AES256_GCM,data:GqA/Qw==,iv:6o+QxryyB4dKXhuUZQTUfNQ8o1/RcqNZrC2aEl3KQf0=,tag:og2U6qEHoc8/3nuYvtHwWA==,type:bool]
    parameters:
      fsType: ENC[AES256_GCM,data:G/tQ,iv:tAHj4/revuT6cnVW+DSPJM4MkhFR0EgKaQ2od+/66VY=,tag:ETVLP8nsbcHQcdMJYqW7UA==,type:str]
    mountOptions:
      - ENC[AES256_GCM,data:hqkPi/8dkQ==,iv:EpuNMQCpfqrmxkwjpf6m1aVOv3TYS2zZDEW8lG42ixk=,tag:fw06yHG1DH5KDkwRQ1tL6Q==,type:str]
      - ENC[AES256_GCM,data:ppFB8VpLO1XG,iv:rtAXRY0tjQLs3nXtgi+XpA5aragpkKSGaJANhibQHUk=,tag:CvUFXLs7C30rLw7GmSCF4Q==,type:str]
controller:
  driver:
    image:
      registry: ENC[AES256_GCM,data:J1XhmFpXw8zsPaRN7/Qk9OfA6+llpbvKm5enVs+ab+R3u5fllaY=,iv:QYLRQYXVUIgO/iY+GJ5jDSDEqlZ6d8Ys7lq6OttcTAI=,tag:T40iTMFACNF38hvBLKHWjw==,type:str]
      tag: ENC[AES256_GCM,data:PdMdUg==,iv:/6rz6vWS8NQPvZAIM2JkAwhcg4ju0UPU+Z2VbXh8KJ4=,tag:hZQ0eCVaG8JIWZ+WSVmhRg==,type:str]
      digest: ENC[AES256_GCM,data:fWwBt35hPzuPeVdSa8DtDqkuunpy5YYFKzhVs7pmC+ZqEJLm7Awg7MZiBJXZXyhvz87hyRvj7nVrqc35FdfzmHSwmFy3Bqc=,iv:eSy64xUoPO5LdkajqjA6rH460bAWV3uqx2k1+vRpPD8=,tag:toPgv5fZLENVi1KhODQr9Q==,type:str]
node:
  driver:
    image:
      registry: ENC[AES256_GCM,data:qVKfx8anQxKzpFt48rULiYTTDgxg8tzbcIjyh/Z+jPBjMuKa5DA=,iv:VpSmANyi5JV/234CgDnO3iu7pXDD5Bj8Esiyt+aBMOc=,tag:e06h8AuVNN5DdCvt40j/bw==,type:str]
      tag: ENC[AES256_GCM,data:CTGPIw==,iv:580MtR0dNxwqANVdUCJ90X/e4jY75Zj1HxyUcMybXE0=,tag:u5WVk057Jq1WQ1R11+sugA==,type:str]
      digest: ENC[AES256_GCM,data:j5Dx8cNNQ/KO0HVkKKK7alYkeVbK+DVAM3hNhz8wamkt1W5w8uyLtq9zorJ+y8z/dZzPDoSvgQSQ433lTEt3TLkzQZjkZhg=,iv:qSXvzeFCzBgj5PLBduyY8Qaevw3YQa6S3ra6pWhXPNc=,tag:b86ZRgJdUWO+1xsl8UcstA==,type:str]
driver:
  config:
    driver: ENC[AES256_GCM,data:pG2lZAWZfqtD2Hp5zumH,iv:F0Oaia9H64IMGOBOVJkuNnRYKqWakKbVwznx7VsURXo=,tag:LfuVrnQIAOYvuNnuqqYNcA==,type:str]
    instance_id: ENC[AES256_GCM,data:ntqgPKKuC9bM8AA=,iv:Ekg59Kv7Wx8KO1sKnIIj2fIZU4FYqKlsIDvReDkvl2s=,tag:ovmmRPugWRiA4bQ2HLlTdQ==,type:str]
    httpConnection:
      protocol: ENC[AES256_GCM,data:XJkKXNE=,iv:8sAYB0hbdjul96l74VZYE0NEHpe7z04Nub2oCMS18GM=,tag:IrJnmEFy5UDv1YUW9cBCHQ==,type:str]
      host: ENC[AES256_GCM,data:ViQzkhi31H6AGhUnuMRGibD/h5NNhlfu9g==,iv:H9k5UY/p5EtdHr7lh+wAfmhX32KbDt+7PiSvwXmEeAY=,tag:JfkaTxfOUh8LQ1r7VbjtIA==,type:str]
      port: ENC[AES256_GCM,data:R7bN,iv:B8GZ7ErzuXC/J7bZP9pXQXiWCV4t8Q3BfxxZ6JpZPAo=,tag:HsU3WIwMiqHgl+/5jlYvIA==,type:int]
      apiKey: ENC[AES256_GCM,data:O0LH24+kth1wjP+FKGrHISBCJ91hWvqrxAXi/5umSczh9hnNehn4pfsheJV0sKUloUs6mkOiTiSS9uXjPnxDh1vJ,iv:fZaJ48VZGY19lpQOFZcEdzZMIy743AbRZZsO7+FoJTI=,tag:+D5ef8NyhcC7WwflyT+W2A==,type:str]
      apiVersion: ENC[AES256_GCM,data:dw==,iv:rG/iRwdjY+p9kIYO+NEuG9l8XJNWw7o+BZZD+Bu7hzI=,tag:oFvlk7Yw3jZbt7s4Cdxv3Q==,type:int]
    zfs:
      datasetParentName: ENC[AES256_GCM,data:0vAI3blZLGtzOWeF,iv:jFqYHl2kaHP3vQKA66HjyYBiyTc197iGWEOwwSYbj6w=,tag:DHBIdFSCGj46k8Yj3Q5BYw==,type:str]
      detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:GRneoIsA4lX4/c29gQ620Yb07qWmtg==,iv:Kwgz458G9rw66fTe71OWoEgnsxlW1i1NiJvNDWB0MDc=,tag:gGNUYLGcuqi0RJCsTgreyw==,type:str]
      datasetEnableQuotas: ENC[AES256_GCM,data:nfBfnQ==,iv:eFvNNEWXfcNz0VZRsWOQ6iZgpd+l+arIRXRVcYhw3SQ=,tag:LxRCaFRFFapc0PRd5cNKnA==,type:bool]
      datasetPermissionsMode: ENC[AES256_GCM,data:3IlXUg==,iv:+kw+Y0XVi9PDAkSiQc8hyPm1h4p7+GXwxOK0XhTDguA=,tag:j+antsk4y0CsDtIV1PCI4Q==,type:str]
      datasetPermissionsUser: ENC[AES256_GCM,data:hw==,iv:PgTCLTHoLcCHB1Wud+nlTe7/5ccnFQSBmEtHS3+4Hbg=,tag:GeTYJe9+TXjAv5RCuLBK5Q==,type:int]
      datasetPermissionsGroup: ENC[AES256_GCM,data:iw==,iv:bOeHAXKSKV7wITDUwKNz9clD075kuXlgJ77zyfWMpZE=,tag:MYf7+QeD22jXBJDFGzByAw==,type:int]
    nfs:
      shareHost: ENC[AES256_GCM,data:QzTWxMKsfDKvsem8LZ/+qEPPeoU2pHtLoA==,iv:asSgGTGaiYpaPj4q0zDa1OWcA4wfJF2wIbYsGIlIzI0=,tag:JPd/Uif3ALWWwHgsNFo9rQ==,type:str]
      shareMaprootUser: ENC[AES256_GCM,data:F3qsFw==,iv:UBozZtjUBFjDA4qQFfJLamtoAeAjbmXm5xQmtTDmiCo=,tag:VCOsMXkO8VcPkwBrgMJR9Q==,type:str]
      shareMaprootGroup: ENC[AES256_GCM,data:m7vGwA==,iv:jS2EDtbo1HeMkjb59ldb4hnVcS7i/Gk4IF+2dI6k7/s=,tag:h+XE0FdiMzZhoZqU7GetFw==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSGN4eUZYMGhTVnlVcTgw
        U3JSL2ttQVZWbTRnY3c4VWVLT3Z6ZGkrM1c4CjZkQXAwWVRUN0VuWm5ZeWtNK1lO
        UXpCTk1SRDVTTFBvN3FZb2pEVzUrZjAKLS0tIDc2dmhibmQydWtLb3dIRHk2Z29E
        MW9iZlptZGZmUDI3WmdtRTBYNWpwUDgKFHX9qEqu2zFoyAq5Vkzg7JHqC5Q4QBtr
        8ZsP76dULynHJ+hptLewc2AjLnx2Zy6hycDd6suW+C8xbYJKU5gazg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T11:35:38Z"
  mac: ENC[AES256_GCM,data:ysdwiTlXiYEC6DCZGtn9EO7owBp6C0u50EVl9TjIYfVSHwWdlp5b6aT0f4ghNsWYGkToCEOHMy51b7x3vliIxWxyudxLL+KFd1+NT3xYhsQJBnGFol4vJYdcMQbG8misGj2uonJ2aOguumswFg7gcvhXaniefEbdgh84YksTfx8=,iv:chCbAxLQ1HRfAWd3NmrtFNBY3eZbmYHir6aRRnafkb8=,tag:WOYfxM/Fz3QW+Wn2bkSRQw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
