csiDriver:
    name: ENC[AES256_GCM,data:UtWsZegcavUMebXpBoMQzg==,iv:cIh2MNi8gSxA2Mu3HDBHmAnZ7vRIvJcSdIrlqqVJGC0=,tag:DL31mvNGdA21wd+MZUdQ+g==,type:str]
    fsGroupPolicy: ENC[AES256_GCM,data:QnZ8Aw==,iv:IXoBwR+nEW8UJW9qGohbY6QK67S5fDge8P/3I7ws5tc=,tag:Sd2SFLWlUPNml+fOR1GXHg==,type:str]
storageClasses:
    - name: ENC[AES256_GCM,data:XAIixFltiQLt7hjEV+Strg==,iv:m/MBRI5bWiS1xjtY1o3vCOb7ChTCXhkfkfbzj2i5T2U=,tag:6om86/WVQZyIA8VtkfyLhQ==,type:str]
      defaultClass: ENC[AES256_GCM,data:9SR7CbA=,iv:pKSXR7RejIUujDenNN5ZwPz+fDz914OQvsKOtZD7NpQ=,tag:7opreSxhU6+uw5at5nid3w==,type:bool]
      reclaimPolicy: ENC[AES256_GCM,data:rCEJsvw4,iv:zNvrE3ezietHsPTmXECggIMxpI4Mn2nsz7BRtvuzKH8=,tag:W0PVzasN8yXOZWzDqBgZQQ==,type:str]
      volumeBindingMode: ENC[AES256_GCM,data:F2dJJaKYt/l1,iv:vuPgjpVOpXVQeH2bD7WMDwumVxW2dlg0gnlRC0mxCVU=,tag:UBNK7i9fVIYVWdZN2VBa3w==,type:str]
      allowVolumeExpansion: ENC[AES256_GCM,data:WNw57Q==,iv:HEa59la4W1jVl6x/CaoK6XXmTxm2im6dxF0qEQjXO/g=,tag:c2OQR/2t83qQAtJ2ijBNrQ==,type:bool]
      parameters:
        fsType: ENC[AES256_GCM,data:oOwJ,iv:n/4FX7y4Fnez03z5LWuAaS/nH0TdW1p0NE087gGohEk=,tag:46aRq03gxr0+idyjL0oeJw==,type:str]
      mountOptions:
        - ENC[AES256_GCM,data:MwgWbZDXIQ==,iv:VKTweeoouQ56Y1qz+cJGbZ3vMmpJJzXxw0piO0W0510=,tag:Fs0f19PeVs+2zIPy/3hJ/Q==,type:str]
        - ENC[AES256_GCM,data:P8+gzCuVzhdF,iv:mAjrG8UCT/9LYAHxCjDkmcCZ9POXqwWQJV5Mqa66wH8=,tag:mok4oaNHZDSjv6aZy8jQWQ==,type:str]
driver:
    config:
        driver: ENC[AES256_GCM,data:fE/iLNK+XH9SaWjQgJoP,iv:A6o+UPoI0lqv0P7KRaoj09s8cX+XjPM3mBsq0veTbV8=,tag:LOffEwhNx6B+t/b9fhAR2Q==,type:str]
        instance_id: ENC[AES256_GCM,data:KpLqa2L0+q+HXm0=,iv:GL6+IGO2Ux91O+JKTqT+Rki+R5ZUzxU4h+5aGLEnQlA=,tag:HZx58DGY3XOVw99YnMM2hg==,type:str]
        httpConnection:
            protocol: ENC[AES256_GCM,data:UNznkg==,iv:E99CNZ7FsAgIwvmq+qM9Q2XHxS/GELwQRRUTZrc3jbM=,tag:M6Cuhe9QdIump+7MqVeDtg==,type:str]
            host: ENC[AES256_GCM,data:xaNWoJnoE+nygkeieNLboPsVFwEmI1vj2Q==,iv:XhfmLWE+jD6u9tgd2uyI6z4qXTI6gxJKj2wDF5mvgSE=,tag:ZxNE5KSOKKK71AZFJB46Ng==,type:str]
            port: ENC[AES256_GCM,data:iso=,iv:XgHYlwnS47BUXc8f31GDnYTZn+fjXXDLCA05KZ2n8wI=,tag:SCFKZKLueCW110L4JvY2VA==,type:int]
            allowInsecure: ENC[AES256_GCM,data:exfZRw==,iv:L1rqqIvTSzd2zuxtyVn7irPEz56DXzNRAWSOqQR3jqk=,tag:RklGqcDeF3ixDmA3M0880A==,type:bool]
            apiKey: ENC[AES256_GCM,data:ovJVOCPeZ9vw2Iu2U2QR9hah0ajzm6kk/YZ5cJs8VgC2nXZo6fV1OQOVFSsGePLwcTmomsxb4jci0Be1mYt03SbJ,iv:DkZ1Sz4THtzCaZ++prj20WJqlHzNfzcVtHltil9LWQc=,tag:bnN0+1I7ocC7MZNKwXcQHg==,type:str]
        zfs:
            datasetParentName: ENC[AES256_GCM,data:uHN/gQ5E8o8KGCV8,iv:xtlKOK+tQy/L+Tkm28UbOv8hS9wHhUCJSIEcHOpxL2Q=,tag:vahsXycX6HkRpjKiinypGw==,type:str]
            detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:/i9aFy6/P4u6xv+n6+h2X1425eVR6Q==,iv:4SadhbGjsIz5nDzh6acj3kBeqa4My3BMfYGmO+gqtuQ=,tag:yYGtHdtYj1xsZwKI2IazOg==,type:str]
            datasetEnableQuotas: ENC[AES256_GCM,data:suCOxg==,iv:rs09hgS7UJGWc8bR2+o4ahzVKHXrq/1woX5/FdefDVE=,tag:iLJTQ/oGGeHZghYSesoU6w==,type:bool]
            datasetPermissionsMode: ENC[AES256_GCM,data:UYW0BA==,iv:/af57uMygbTT06ReeNrJ6J1+CLzBnmCtHiKSo2bjV3U=,tag:WBlR7GBiMKKxL3Mnziwf8w==,type:str]
            datasetPermissionsUser: ENC[AES256_GCM,data:jQ==,iv:mIs/FAeMGfB5a6Wjnjk+m01j3VMHhpR/gf4xXOOj69E=,tag:r7fsgvIqLDaI8gaY+ztr2w==,type:int]
            datasetPermissionsGroup: ENC[AES256_GCM,data:qA==,iv:XthbM1VS7+USL0ANXE1VwA68tvmdY1vw0e50A6F6DBU=,tag:BO//z0Am28ovAZ/lrc1fRA==,type:int]
        nfs:
            shareHost: ENC[AES256_GCM,data:MGWEs8qjtbxGkJbS++oWzsjWpEM/FvlOjw==,iv:l1WTu7RQQvmz/80z1ehpL8XRtkRzG6wNDL42k5Etn9U=,tag:LAh8brMXt5tiHxMbLWQzMw==,type:str]
            shareMaprootUser: ENC[AES256_GCM,data:ojCuBw==,iv:NQ7Oao6CDRwxcdzsmDYup3aZJ4QS2KNWqic2W8EN3HE=,tag:jyQatoVXmX1q0h6zRVbXTw==,type:str]
            shareMaprootGroup: ENC[AES256_GCM,data:UmjP0Q==,iv:lRiUsR5sN5hGQQr0MN/vFmliOQfwGQ+BwwMiSqNWeqA=,tag:Dqjt2Da4T9E62sIaDhlu+g==,type:str]
sops:
    age:
        - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTnlnWEJHK25taFFiRGpK
            MDNXTi9pYktUdlY0SURHRDF6OUZQdVl5bjA0Cm1USzRuVFlqeWkxUllBRmJ6Qlhi
            ak5tK2U1cS9FTlJleGFYZ0VJTlExcHMKLS0tIDFkSFB2K0JBYWVndCt1ZVd3VjJC
            UWtkMGZsY1lrbTdoVVFVU2FYL2k0VmcKrnYDahJSKz1ZcGK66/ySzrrCGN9ADr3r
            KcZoMSDnGxTHq/Lbjw2201WdCUZsUabUsxFhU+Q0CUnr0XKWdXUdFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T10:33:07Z"
    mac: ENC[AES256_GCM,data:PNd+II8zdkYkPJW2jl2eYhIyfBhuM95ujxZ1gi6CnbbriPZMiFADoyX8zOa2K3r+PCketQn6qNJT1b3ONNvb9DhXCHzKVHUeT84iSzsr6sFVjAh0pTeE9/s/1u/61F/x9JrKNUv3znRdOAbRptdC+25vkybxth2ShmQok5T577Y=,iv:5zIEluAmPjq8spodWR+hutof3zjNRMpxR37ZX9GIFAU=,tag:uQJWgmpfudz2/4+TPLD14g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
