extraCaCerts: ENC[AES256_GCM,data:DTfejheN2VCgdqGFLFG1ju9mgfjncWc0eqeNB7NKsctJWuBd7bG260TE0Ec2QCV7QglI6h+ulbOG0bkLBTrIcxShwUPD/8vrfN1Sb9U+a4lPQTyXMvt6ZCtCEyxQ46TT+rtOa02vdpm3fTIIKkbV5vSWndQ/M5Mngs7Rw4UkrKjO4LrA0NAosWVlAJjfH2xhQm8t5HBD0l0K9He1olbETyAOudB5iJudd+Hm2gW48noPaKoYq+VOnVLMtNFAFj86uErjfwYkfxE++M2vRpnPpk31XLSPcCmmIdbcDu36q1gW8IBeV4vzO9+lD+oJJBjsDnT5V/tDY3iP1gKf41ksqD2fBBjdM7HEfMHemesm7C6mgzzxiLT4CxsQqBxr4UInAiakWwMaOWDl2/spDeO/A2zxHVLePkXT2xrZezwVlDNPiEd+56RhLW9kxhw96Dm5jSFVKlwEqrpmfiGXEce6YQ+YWEpempCjPBlQm16QOrjVe30+4/PopoghtDXcnk/J8qqXuYy6MgBGBzVdgrXmK6dQ8pOqdC5qWP+skGrbsa4WqX4uaN+M/wixPYqVn8akyZhbrPbtostKBI2opmBstvsUQDQmXuCARXbt7jxYMId7b2SU1SYbW63D3KyWzr42FtN/SArX5W90jhG9duaj2Iw61FsZXSblKcIKAi5+7LBbPcNInjQg9eeZhSLOPJnuw++xITHiVFN1UlYYpsVuhfLvV82cB7vzE1vIDg9smECJbTfZJQgdLsSn+a6d,iv:dug5nbs6pQsY44X3jM+DYnzvBVuLeM9YLP8MxzWf71Q=,tag:s/MNBZws2jOqNADqIuFKUw==,type:str]
csiDriver:
  name: ENC[AES256_GCM,data:No3QKMSUD8PxOMczmzYVsA==,iv:G070ebekutVhbTRrX/okMVrR7s42FzomGIDT0lg9nUk=,tag:MpIg1NQfDeA51slVxAiHuA==,type:str]
  fsGroupPolicy: ENC[AES256_GCM,data:uOC76w==,iv:Kirybzw+5HxUUtZ8QkKef06IM8+k/BgDGI6A6vfUtzI=,tag:OjeJKEaWlQLc0ZjuOrMSbQ==,type:str]
storageClasses:
  - name: ENC[AES256_GCM,data:CVK37JVU5uyj/9WZs7TjSA==,iv:KHNXwXuzekPoFXSUnK8a7aUFL8gCxHm9d+JzEZqN9bk=,tag:xxOF907sYb/nSk49aqFJeA==,type:str]
    defaultClass: ENC[AES256_GCM,data:2fLFjGw=,iv:KRMAWyoUJp9Ar4Q8szNGvzK7SdUH8vCj/OUrh109gxA=,tag:RkpH3dDpBUTIOvk1F5Fw5Q==,type:bool]
    reclaimPolicy: ENC[AES256_GCM,data:2d3qFjZn,iv:hYf5OYzZaQ3uRQhIKAp2n9GnJZtVga6VG2bTExMgGwE=,tag:FRyslIBXhX2z70IAXdg/vg==,type:str]
    volumeBindingMode: ENC[AES256_GCM,data:EfhWHve1p7M/,iv:mkDOn+lMj+ShgsnrWp09IYwrcGppKM72QPObXtQ8qSc=,tag:+5J2S3AWntILo4/tR+Yf6A==,type:str]
    allowVolumeExpansion: ENC[AES256_GCM,data:zBDDfg==,iv:rkLI7gG3YFGQfRQoTSwn9VyC57Rk001uq7mlhZvNWTs=,tag:UuTRBL9ICiqYlwwTXS8xtg==,type:bool]
    parameters:
      fsType: ENC[AES256_GCM,data:iv6j,iv:9NPwGWnI4su3DxvBhn2E+UQTiEJ6Xw9NmuPViI/6/Fs=,tag:FcR7Fw8SfRbQeY/WN+DO7Q==,type:str]
    mountOptions:
      - ENC[AES256_GCM,data:XXVqcuaEGg==,iv:OQC+n563JgxdYCzJIAtIxx4zAFJ6GgDNkwfrgUX6vYs=,tag:FeEd7SNuQrpCcqtMdN5kIQ==,type:str]
      - ENC[AES256_GCM,data:JZwRo2uwYvSY,iv:KuEVPXJAD61mtmJo8GAhTRW90Gha9zKgc2vvD/KVLUg=,tag:r1aaW6sPmuSQmM+iQBGt6w==,type:str]
controller:
  driver:
    image:
      registry: ENC[AES256_GCM,data:hVH+jTXivGGUJTFzm+zRTKURO/IYmsa7BW5l7xmSEdBZqMA/Ucw=,iv:FF7lSrAqHVDyKEqo8e4+f5u3UxSpn3BmXWyXv4Ch4I4=,tag:YDtsHFr66wTdzUs5u1U9lA==,type:str]
      tag: ENC[AES256_GCM,data:c7vzEw==,iv:BaFeO+M8SSrlwyI1+yg4e60BIcXHEwZ8ypYp0ScBWYc=,tag:xd/ecMS1IFZ2g1nL7tB/vQ==,type:str]
      digest: ENC[AES256_GCM,data:XynWi64EQN8l5DGtIRxLQQx7eaTQxBAaVysLAVRxczVdGdBNUAKl385uJ/C7rn4YKfG3i4HobuJ1wtLzo402ErdcavArifY=,iv:WunEbh+qsgUquf+ScMBrOhyElX9ww7Q/QemyWHAbZ5E=,tag:ibOUZAGDCeQYGjUxxU1n9Q==,type:str]
node:
  driver:
    image:
      registry: ENC[AES256_GCM,data:mmfyjbaT20yPElvIZr70avXUq2JJCV/TU8Gl43b1ZMwl1L/YJ50=,iv:Q+A1CH8So5VOltNlhrwgSh2iB13WXIt33fxib7oUShM=,tag:IKHLLC73j1uaz9zgc7KiDw==,type:str]
      tag: ENC[AES256_GCM,data:HuQltg==,iv:yrW74eFTiNDlmEjCGG9MUDXaxqFDdd03rODUIZODAwo=,tag:hUz6KJWJZE6nHOVCAzeS2A==,type:str]
      digest: ENC[AES256_GCM,data:k7Z4+gWB7v8itIqwNVctdMpOIwuYih0Lck9JQxiwm+EY1PZvGdrHXoN2ZqcBuQMd+3TEiW/2SQ9hdrQ9ABEAfku0h2xyM0g=,iv:NZQsCI8xBUk3Ul5WSdUhOUf/Kpp4YcyWcsOHis/xd8w=,tag:MDjnguSteobpoiNDgYZgxA==,type:str]
driver:
  config:
    driver: ENC[AES256_GCM,data:1o2bPCZvH0f3AOLSBnQO,iv:Y0dOJ0PK6947qL2GKhPsEjLjKsei2UPjTv5di4Pgp0k=,tag:hnhYPN5CyDntnc77v5BchQ==,type:str]
    instance_id: ENC[AES256_GCM,data:BxhRP5RXSH7h8Vs=,iv:+w6u0yJTP3SyJJETZPUszDONzNih/g7FB6vlyzgg6Ek=,tag:ku28o43Ztv5682T0TviM0w==,type:str]
    httpConnection:
      protocol: ENC[AES256_GCM,data:PEuPe/k=,iv:gWvj5JZtpqsUsPVHv2FNJ7g3O6wIyXvjo6OrhZ10Neo=,tag:TpdlNkyN1G6j9uZbaE5bFQ==,type:str]
      host: ENC[AES256_GCM,data:+LpnggG1BI/ryOlSlWvKgp77uwBYVIXOxg==,iv:7qMgOAEegr8NFgvEK/Npxmx+xcghKtFlSkT21h8njpg=,tag:8m9l7DUgGW+PMn1BnIN0FQ==,type:str]
      port: ENC[AES256_GCM,data:WXRn,iv:nBW7mwbazRmRGGzNRM544cDdbL7rfV987s+XddMER+0=,tag:HT6RRb41CWywBcggLgErvw==,type:int]
      apiKey: ENC[AES256_GCM,data:TPhtEWJ5383kb9z6rWR4mFmVdgmek7mRnYm45fsIW1b5tqBDyHTnPL3Nxo0sn+qy18XAjXlcJD0VnYSmTri/7eWp,iv:FnI34BsO2B9swU3zSv8csbfw8lk/M/rs4JIjM2GTfGc=,tag:V9fsGx/LD9l56gvmWngFCA==,type:str]
      apiVersion: ENC[AES256_GCM,data:sg==,iv:20MFmiqO3RLjjAAzm0NuwRuavzWKnsjcgbzq3zXflRY=,tag:LruTA2OzMq6rc4NnQXU3vQ==,type:int]
    zfs:
      datasetParentName: ENC[AES256_GCM,data:7OevBYb2elkYUCVl,iv:5lxsdftSIsemhfrN9rv6+2bvcqDn8etYmLTbUYppqT8=,tag:24cUJUlh7nRDNxPcAIisrg==,type:str]
      detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:p5iwq8QQSFKT48YqAJ7+YacmTRHs6g==,iv:8GY0oZ0iDQlNlBmF6nLdTPKWOslbNzYBobMsVuvCdUM=,tag:AxyeWKx6lsdbSBjY7Gd72Q==,type:str]
      datasetEnableQuotas: ENC[AES256_GCM,data:iZeYSA==,iv:HiwaIJEgGCdorhtM5OGbkVjIQpulhNmKnPHeqsr6EX8=,tag:AVj+OmcLVcNxrroSmfl0Yg==,type:bool]
      datasetPermissionsMode: ENC[AES256_GCM,data:+/UdPw==,iv:R2Y+MvWTDbbqo7W6gaf4OtoCXrIGZbcmhIUSWcuh6Ew=,tag:rS/Lx68ct5J0v/Bb+4x9fQ==,type:str]
      datasetPermissionsUser: ENC[AES256_GCM,data:Pw==,iv:JrWdYcL4u6SCkgWdVkxa+vGzwLf/LmfGEklF/6KgQxc=,tag:aakMgGL6rl5Ghuauxqo5Mg==,type:int]
      datasetPermissionsGroup: ENC[AES256_GCM,data:tw==,iv:WDRQ8M7J+1wpqwxiYPQNpYfPK/rh7kHtc2dX/NrLgaw=,tag:DYYbwdaVuwf8YbtwcN69JA==,type:int]
    nfs:
      shareHost: ENC[AES256_GCM,data:wUZwHz8pyu/46IUNhC2IpOibrsGjUhR6qg==,iv:CwZGidzeJZfe+WqGkxbRwgX40OS5p2hBdVbYiAtV8gQ=,tag:STFls+TXIKX45lGVjeG/aQ==,type:str]
      shareMaprootUser: ENC[AES256_GCM,data:QlDlxQ==,iv:UZ155EfpK+ah36b1ECoGWzCseD0Kfx5EDXQuPPWKoxw=,tag:6djmnXXHL05752K54/y0Cg==,type:str]
      shareMaprootGroup: ENC[AES256_GCM,data:Cure1g==,iv:a+Plg6DBgMN4hMqK32qgA1zJrqXytvq+s+N40SpHuYQ=,tag:drpVsRC/Ut511/mrszNb7Q==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrakhTekRtdnVnRmNjMzJR
        TjF4aDF0dVRkQTYvcGx4S1ZCRWFzQmxXeFRvCmpEYXlwd094L2d1N1IyS2VyL3Qw
        dS9uUzlVTGw0cnJxTTJrRGFTMElqVEEKLS0tIHJDKzlOUS9JVGhua2FMbUcwaVBv
        b09GUUNnck1SbWVDcnFsTW84blRrTmsKGXg2o9kuXUeVPuVRk6A70M3eqv3qlL5Z
        2YRW7I8rL1kwSF4/WRqxCBKryVsbSjw5zu4ybaBBEsC2LOmVkQqHkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T11:39:36Z"
  mac: ENC[AES256_GCM,data:k3CuBmgs9QAeArELDwxzbFuTvq8ujO2qlMajsXveRrH5VOOdUlDgjechLFLp19mNQdWeor2162TFkF2eTlTNuS54zgZN5YAN2ZrOehNa/YDcgFyW+rsYibL7kzvpJZeK7OnKM4f55e8cKyoqL9rIOznGxPzAe1OxNUfdX3+e2V8=,iv:kjlAp/RWaysmOhZVxw1Jrcqq64R00byqfo/sD58b8H4=,tag:RUfWa2g3FD5gWApqDNn6Yw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
