extraCaCerts: ENC[AES256_GCM,data:0gFS4yDPdrdqRj2YrpVYMNQvuQ15flAugbAE0EoH2SWxY7xKOT9B1KxGTgjlpvjgK9mHkcsqGYutal5gh5vGrk+7fhssCz+m11npEUBl/a4XHW4BA64IkUHGghv0GfbG5klX0EpjhQAh3KINUtngUtk1Z8tNZEvjbmeNbnuJfuBQ/GXLeauYrJLf0BRb6D08fUEGysDgNJ8+AhPpjD/xlYG9e8TStlE921dcXZDYvnn8ADmhL3uOC/Eb1jl06yL2TZLR2ossDu+ISv2GESRXFBjDCuNjid4ls/SoRYTsgySC19YgV9Jxwxdw3Jm+8NNhIytOOVUpYUVxPt6y7gQOUB73dVpeZG0iJwl+FNpN5FTTnb/AYLAZvEN0sjb/TAMF6yHK7R4kMiNzATovG+ALFQ1ci2V6OLAYkqq/qx0O3wAojlY/vxzYvN9u8qZergRTuJ5YZDjwOaPX/4hLsCwXpJOunpqqvrmsNyuQWVJIATc/F6fDMfGLTmVH8VDpPb0Qp48BH8tJIgoJCEzhPQPCT66qTgNzjPOUeqB3dLVecwRCQHv7Jv8GQaGgX08RICFSDBcZaeg3vTAh+Z6h+56387ueAzyShTj4MdHRRvKYb7OBvaokno4kGe1Eys/G530Q3g99nVJbTBE3GCIroxB93+kG5D00uwkY+BMw2j+1Ngxrf/1qY5LML/7iA8CEuGvPtHlBSNwuFJs6u5gPHReYcFT30A6YAlE1RHGSUqP4b5fuRr5F2TaYjPRsCNp0,iv:1fmaoGBV0gjfhXNohCZ6/ERUH7pbUcN2IQV9rqQCtck=,tag:yf4cnN9JahZmocxDZuL8dg==,type:str]
csiDriver:
  name: ENC[AES256_GCM,data:nGdb53ZDxVoDEyKs96uoYw==,iv:iXPavcn5TMfKq919sN2C20Z6fhYF9ffEgL2XvaDbPbM=,tag:QqXDMcMpceViOR609SdmFw==,type:str]
  fsGroupPolicy: ENC[AES256_GCM,data:zGwzrA==,iv:ku8Chvvh2K46dBhq827an5Tw1ifOo6haCnUuQiv94AU=,tag:yEO/YT3QZZQqXSdYrLTIwg==,type:str]
storageClasses:
  - name: ENC[AES256_GCM,data:Gj30GjLPGUEjPPQQqp1X1A==,iv:0GTvhEdP+f1Sd7sGeoy262I5IOD14qHZndiMzbKo7KM=,tag:kZ9ckQD1UMLy5hbYbWgUrw==,type:str]
    defaultClass: ENC[AES256_GCM,data:HLxX5OM=,iv:PrLF8XbAi7gjgw08dd227rCGt6SvyJMp2yXn/o7R2VE=,tag:U8gLHIM+pejeFDwuFbLL7Q==,type:bool]
    reclaimPolicy: ENC[AES256_GCM,data:P6SzLES4,iv:TsMCndeRjWPcdlUA7gpaYGCPDsK7VERCgS5Bnv/RUCw=,tag:gh834F9ZCjz7/GZ6b6gHtQ==,type:str]
    volumeBindingMode: ENC[AES256_GCM,data:lIop9GjFscf4,iv:Acdooq0ktJWmMWoWJ4VR3Ke4SjytPcIUeuNVMbXMbEM=,tag:0tFVwOb171ho4mfaRoOF7w==,type:str]
    allowVolumeExpansion: ENC[AES256_GCM,data:Gb/B3Q==,iv:6Dd+3tyijgC0ZWv3oIEHG3x6ZP0gxkX0w3LzUH1/ap4=,tag:ByKQsVNTCr2Pz942uhziDA==,type:bool]
    parameters:
      fsType: ENC[AES256_GCM,data:Fu4B,iv:8RmgFGW7y4zqsy4VeuJZlbzdnLlMmVOkEEeIlUbYSTI=,tag:BiQfQ8RgM94Yzx543j4/vA==,type:str]
    mountOptions:
      - ENC[AES256_GCM,data:m4GGjA9kNw==,iv:I80MxhjRx0IpufZKgkm7yO+7MNbKEFHJHGx7rF3BAwI=,tag:xcAlweMD/Egl4yJHAQBblQ==,type:str]
      - ENC[AES256_GCM,data:qpMdjchzeFt8,iv:7eqNoge2MVrKbaPrV2oLM6hu1Z1nBH2Sw5woRbhBLV0=,tag:9/KM2WdTbuiEDQSTaL5BaA==,type:str]
controller:
  driver:
    image:
      registry: ENC[AES256_GCM,data:X5xDJebHTccKDWT4GNv/u6Yhz3z62KCKMbJMRei9ryv2Ja/RU7w=,iv:zNKzTesmViM1Dxuy0O0onSCBSPpwhwbg07zh9pcfTPk=,tag:8TUKwFZOeyum1IAyBx14vA==,type:str]
      tag: ENC[AES256_GCM,data:r8OODA==,iv:djjEmJLhLR7VWrCsxvwfy1+pegZxgFNiRBLWXM9uj+8=,tag:tZQqMPwfwVNW+X7XLxXU2Q==,type:str]
      digest: ENC[AES256_GCM,data:0t7/0IlFgIz/btjwn1CTOPNjzgEH3CEl1GIb7bRIYRjlWgjZng9pO3DPLyqHaAiX8tuaf73NxRX/ljJSdZ6QxKIA9UWwWJg=,iv:FMx4OaHXzdH5iYVuPIjRSrVCD1ns31buHa++s/RNiio=,tag:X0XL7kwU2To/L2mVdYBg/Q==,type:str]
driver:
  config:
    driver: ENC[AES256_GCM,data:UmwT/AWcfsQvrkOGkQE6,iv:rOhVvGHRL6unETXCLOMPjf69d0jpVOItZA8KJJFN8tE=,tag:G2gEizMZJbk0j5wurX4MFw==,type:str]
    instance_id: ENC[AES256_GCM,data:8H6/toz53RH3QvQ=,iv:QS+Jb/bf9nrWCuVfMf82RC4FMdvkEFUXXimVIo4evwQ=,tag:/NiMl+xFcDFFPNTFyVrUHw==,type:str]
    httpConnection:
      protocol: ENC[AES256_GCM,data:rP0pNzs=,iv:Vhf9aSit6bXsVov83vZFP2UyyGkxOEEDRN1PUHQNLXI=,tag:aaDn9KjnIxVgETFmfl/wUw==,type:str]
      host: ENC[AES256_GCM,data:LEclXDgeZ0qz7KoFAqhw3eIQSXH18lMBBw==,iv:ZPmZ3wDzUiZHC/gfOXeMrQjwTrhxxukzk8zVYvM78ZA=,tag:qzs1eqiN1mOswPerktjo/w==,type:str]
      port: ENC[AES256_GCM,data:Jkvz,iv:/hK7dlUXNixHIk9r9/IPjJSN5EQufOEH1NNX6LL37U0=,tag:22OS9VBdCpicoLDjzM6myA==,type:int]
      apiKey: ENC[AES256_GCM,data:kP2QJ5ebdBZbrZS5uM0jfaEYgakYllPbOmI1t2JOPzt390/jphWSUn8nf0abMdReSdPitHbKPOldTgXmmd4dqmad,iv:apuzD6Sbf5MFrG/BtVyjIr6NgKCT+FGrdnI+5vdyJqQ=,tag:QJlDT5JTZVa2Xa7ePWMGKQ==,type:str]
      apiVersion: ENC[AES256_GCM,data:NA==,iv:60XB5mvkJiJIqTQl9vWj+cz0KSLn5wZdX2ZWlO5l9Qk=,tag:bVQ7NNv/9AC8OixMvMzNZw==,type:int]
    zfs:
      datasetParentName: ENC[AES256_GCM,data:/7vYwCt2oks4sOMA,iv:02O4a8J3vXPOFhWb9SnA2oVGR+ng+dKAPZlH2JyvSO0=,tag:76RPr1oLUjOvJBJiUccF6A==,type:str]
      detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:iEP5bw6GiaiTQbtTr/7d041srnWWJQ==,iv:n2IBFowmM6ioCYKzNKbiM0Ono1rcffm3f7MSLww3EWo=,tag:w+7yxK4ilpxDrXviJ9V0eQ==,type:str]
      datasetEnableQuotas: ENC[AES256_GCM,data:sP/AlQ==,iv:ourceCkQpe9Z0SJV9208MjhyBtgJrfsFYglB3jEg4wA=,tag:1cIe/2ycTwdN8Fsy6Z0ODw==,type:bool]
      datasetPermissionsMode: ENC[AES256_GCM,data:lX7kag==,iv:cuzUmnvHWLFZ3rrHnv1bkDkxHsY9TdfTMjjA0IJ8lKE=,tag:Sv2/3e31SWV4BibrXbDvLA==,type:str]
      datasetPermissionsUser: ENC[AES256_GCM,data:Wg==,iv:/q547vs8JMiSFmi7KQM15W3MfVjvpXa7jVPTSKppVeM=,tag:6HkUA6iCC6PVys2fLt2NOg==,type:int]
      datasetPermissionsGroup: ENC[AES256_GCM,data:ow==,iv:yPDx5uBNnUrT3oAvq3X7e3/leJXJVhf1LEDLgGY/10E=,tag:n2Evw51/RJdq+ErWNn24jg==,type:int]
    nfs:
      shareHost: ENC[AES256_GCM,data:XuINTuIIaK9OYiB7VAAQq1wnVJS6IzHERQ==,iv:X4JY/nEJuLwl3jK0gxGfW5s6VL7RAFvMN968ZgSrDS4=,tag:rJM82qTDOpleAnl0CHJuIQ==,type:str]
      shareMaprootUser: ENC[AES256_GCM,data:LLpP+Q==,iv:ZPilrYMRMJ1ahGSSUIFqo7j26nTU5Q7c/NQRx7VU1Dg=,tag:z/qHZKHSL4bmpyMfc6+yww==,type:str]
      shareMaprootGroup: ENC[AES256_GCM,data:4Io/YQ==,iv:atqz3e/w0BNR6YjqBVQiVGPYCSGUK+EqeCrcg1+PBnQ=,tag:g1FQbuUePtTfXewSP4y2tQ==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZnIyUkdCa2drc3NtTTJC
        NkgxQ3o4L2FzSFVKWllhTytBaE5wTWFQRmlvClFKU2drcnB1M29haUsyREQ3ZE5j
        SVptY085VmZSOEVFRElzckNhd1NaU2MKLS0tIGtBcTVzbGhyc2gvTHdVbzAwYThT
        UVg2amEzdWdzL3Y0TlRBUW9KVktjdEEKICW9uLJxaMMVTPwJivTVm6Fcw4nYXJe5
        lmlnLAa91DzlB0b0q2o2oPoRWv1RhPq9eM5awTSKIM7Vzrm+xANpUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T11:27:58Z"
  mac: ENC[AES256_GCM,data:joWzOoPzzQchDb23rfptN2HVKX3pYMoBUzQKhUIn0NNMwLWccGy9fHg8y4b+xVyvn0mzsME8F3TRSljZHL7/FyVkDrr3xMhIrHmoU5Hn1WaUscvXbNvlDJ2cpj3dfqGn/4i/byJivyIP6U63iQbFD8p5IS4cW5j1GhVyCHaSdAc=,iv:Kj7t+y9jJ/GiPrGDzxxqdG0BKA7SUmzny1C4Gv+R7n8=,tag:KkFOz2Sm78Of2zb1nJtm8g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
