csiDriver:
    name: ENC[AES256_GCM,data:d2arlrbD0lRNtrTrWGaqsQ==,iv:JxhthZ2JaIqbw2nQZZEhYlj707mPoOCIanimukBdgEg=,tag:mUNKH0oERyngI3+JlWqsEg==,type:str]
    fsGroupPolicy: ENC[AES256_GCM,data:3kL/DA==,iv:RZRJdhY8mU4WaAlsVyUqr0aBRF0QH4DUcHCrLWSef+I=,tag:kv/9GRig2iwSomJeSoBvFQ==,type:str]
storageClasses:
    - name: ENC[AES256_GCM,data:gs/JlmxMH1Q0QEhumW0zdw==,iv:RhiTBATfHY3Rl8qJi8cDDWSR51CkReRhy/XOkJhmWEs=,tag:rKMVzored4C57Cpxy2wL1g==,type:str]
      defaultClass: ENC[AES256_GCM,data:L3xoKNM=,iv:UZZg+A8BEg8ckcUbfOOxiaW3JPLeV4Ucp0tDeijs3+I=,tag:SuMp1vFSoANpip/oLKbKcA==,type:bool]
      reclaimPolicy: ENC[AES256_GCM,data:Jz7ShchB,iv:RQkx40QmvdZdB1iJZ9TEw41m/LRTIKYm2Lq8T7T/xfk=,tag:feVzVhVLKfi/w3ipEJaxIQ==,type:str]
      volumeBindingMode: ENC[AES256_GCM,data:/X8Vygc26dMi,iv:37YarNvB0l4gkDK8t77UckIaeVeK6W3ZsxwFX9Uj5Z4=,tag:ChdkobuzM9uKNquiUDAh8Q==,type:str]
      allowVolumeExpansion: ENC[AES256_GCM,data:CmqnhA==,iv:RXUXfxH0VW6TFVyPXLUGgCNkBGHXBoNMJFEHKjxM9Pc=,tag:5KH2+gKb8jAOUbZWnhvACg==,type:bool]
      parameters:
        fsType: ENC[AES256_GCM,data:2vdd,iv:+IXg5eqCSlF2d5Jcooa46ajM0V96/lXwlfmLFsuZEfs=,tag:S6tZdMMkLg4d1DDwk95jog==,type:str]
      mountOptions:
        - ENC[AES256_GCM,data:ljVTzQWgUg==,iv:BcZ4C+bPEY5r6R8KIzs/1ZAMRkHE2T0ZRPbYNuZWboU=,tag:UTxqGPXHZxSmqby8aXHTww==,type:str]
        - ENC[AES256_GCM,data:C389uJUItk7F,iv:+zHjyQAki+WLMdcsf9e+oLwUtoAzlwVhwUIDW/kgzBo=,tag:Wy21YfUcF4pcO1bR3IU/Mw==,type:str]
driver:
    config:
        driver: ENC[AES256_GCM,data:wqsXENWYtrMWV3n9+CHN,iv:17W5uUA7ebRGTjvpXum5OB2FTCKt731lt2yA+Sa9UWA=,tag:vSUwUKDdepxpzIdR+Xps3g==,type:str]
        instance_id: ENC[AES256_GCM,data:U8KvDJkiggKenWw=,iv:mPPROtXyiVE5HjmqmfrrIjIqsX7uEEMs3SkM1hz2YPI=,tag:P18Smx706ig1gJQ6pWRQNQ==,type:str]
        httpConnection:
            protocol: ENC[AES256_GCM,data:RgiWVw==,iv:Pu20kaePTk4kznIIjjQKMrb8SiAN+0pKexyM25e6/CI=,tag:gzlH6rUCnSnl6wqkaTArFQ==,type:str]
            host: ENC[AES256_GCM,data:xTyvGrmnf3ntA61R5GMePitoRnodtTDUmg==,iv:s7DAkpXNh1WTYezozoJQDsRmdf50aT0OoLnjt5yd2vk=,tag:u4zkUxfQSUfumHMPvv8SHw==,type:str]
            port: ENC[AES256_GCM,data:et8=,iv:XIxu9zfOm6yhQcxlXClUU0yA5WnWxTe8QguiieG7E/M=,tag:VbSa5dq9yIQKRQKmtOhDIQ==,type:int]
            allowInsecure: ENC[AES256_GCM,data:mSBrAw==,iv:VRz3prL5J2c6zA0SE7ml2mWH82H+O0TTl/cpry7lQQI=,tag:cjdahfO06l8XZkrd3F8IIg==,type:bool]
            apiKey: ENC[AES256_GCM,data:DSc3qqtwwPZiqQM2TGg+X6wUFAMmCeZLfeDqcRGtNaPNaC/UJZ//wD2PRB9avscD3dRxkK55/PrMYq9og13IC8kY,iv:6Hu8Hz2A+h+0zHJNoBM8nFbDZcp1GWXCo3KbEBXqjAA=,tag:kke9WiOtIK2uZZnszbwbxA==,type:str]
        zfs:
            datasetParentName: ENC[AES256_GCM,data:ve/m+PXbYFi/xdeG,iv:AitRmzbpU53tluMMleHRNh8rH1dNOpgCFkJ/aryMP9M=,tag:TgWEP2M9xuZCzk+vQxb16A==,type:str]
            detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:t3Pr+4k6XuAZS/Iy7U2w+Eunc6obDQ==,iv:S9kiA0dav6MGmIBb/BW3QkntMtNVjlWBQ4SL/NpV7Mc=,tag:WDVOpF0kYhvP4YLdyhoz1A==,type:str]
            datasetEnableQuotas: ENC[AES256_GCM,data:3wIs+w==,iv:7g+bEyIGMlJwihmcFmi9yY6GAMlDkRAIcAxScidWxFI=,tag:LlB6OKHNuwRdEB8T9phUFw==,type:bool]
            datasetPermissionsMode: ENC[AES256_GCM,data:+AEofw==,iv:uvXxd8FWtk8djd0OGD+QRpxH+dyFvZSykq7kPmQ8oPE=,tag:ZRQtRSr9OpnvaNdHRrSj8Q==,type:str]
            datasetPermissionsUser: ENC[AES256_GCM,data:fQ==,iv:MnnbxMxZmfcA6q+ZcgAaWlJrvcfCVdmFJmOT25Gfzdo=,tag:yKj/hY2NsmRy8r9Td8tLhA==,type:int]
            datasetPermissionsGroup: ENC[AES256_GCM,data:RA==,iv:4OC3pDyaWzNJsAc6v2zo/O0IgAciR7rGr6xXR46t8Zc=,tag:vEp/KDkSk653bs1Z+w2uBQ==,type:int]
        nfs:
            shareHost: ENC[AES256_GCM,data:PnwKkedOW/uCp7sggEZEhN8Jdiqe95z3Xw==,iv:tQR3vvwZkUidttPGTv/NWMbV+0GNFjfLqWUrntD3THk=,tag:p2LQlZNgj4DmK3a3ehtKfQ==,type:str]
            shareMaprootUser: ENC[AES256_GCM,data:MChPqA==,iv:sdJ0hLGYweQNYsRdLtMg8Y56y9ibQ1tS6iOFNkwY7lc=,tag:3yeUxqndPTMUDafT86IsTw==,type:str]
            shareMaprootGroup: ENC[AES256_GCM,data:ldNONQ==,iv:iLK8DRf2RP3UoTMNGu69GjP0lqjlmnaGMxHvVcgHDd4=,tag:NLIPCctcxVNII2aTCOTzaw==,type:str]
sops:
    age:
        - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYmx5MTFIT0tpWlVBMWlk
            dUpUTjB5UFVhN2NrNlJHRzBmdHFCNHJHWVVjCjlpZUJkQ2o5TzdwU092NFlGUUFW
            UEhkWGFsU01vVkJyZzU4c00wbEpyK0EKLS0tIGpWZTNLamhCTVQ3QitXRnhidHQ1
            dTloeTRzUnJBREVOQ0cyM1N6bWozZjQKYsDyXjT8xDKBGMrgO5EcFeEGTMp2kZA7
            T3PKFvJ2jI2R/KRDi3qsP7oDE8IvilFR8aLKqgPquHf4szxB1Xg3ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T10:22:17Z"
    mac: ENC[AES256_GCM,data:6V6OGj2n+uMir+OZuLhkZui/qgeZYrNr5E7A3yM5N9nw49473BJFEc2FOdVhCr8L8cs6YOzJjMsppJHhWQ3fq54XhkOw/PnVwktVyr+3PMDb5VxoY/hMPvmrDLtgqxAS6I6ANSwgw6WKn2f5evfD1LbQSocX94nAh45vnyD5EuY=,iv:+R5/tfgIIqGaLJTnA08qUOrbvtYHSBj7DCYQIEGXAzY=,tag:wnIDrZywa7bVwqqRzJC6rQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
