apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - helmrelease.yaml
  - namespace.yaml

secretGenerator:
  - name: authentik-values
    files:
      - values.yaml=values.enc.yaml

configurations:
  - kustomizeconfig.yaml
