postgresql:
  enabled: ENC[AES256_GCM,data:8c/8pAQ=,iv:TT3uBafAzblJ1GkkGuhitOPxN18Tz71LvlNar6xV8/M=,tag:asvsuo/Bp+AwkGiz97x4DQ==,type:bool]
authentik:
  secret_key: ENC[AES256_GCM,data:ockgk0fIQB9iH8+QMhphLQ==,iv:77OSesyQipJPcJ9DV/nnOVEeqeyekc2WGBLZain4cuU=,tag:sXnhgv4kysiLL9Y3ZL8gqQ==,type:str]
  postgresql:
    host: ENC[AES256_GCM,data:Tm+PQZsZSpBVz/OEiyRBUJUSmiRoD4SKwfqM+LBE76stdZa0/UI=,iv:y102C8oWqbiCC2FthE1YRlLJkTaq1k4SamQxFsx4PKQ=,tag:q3h0v8jOEqVumLZrLjY4XQ==,type:str]
    name: ENC[AES256_GCM,data:ZPgLTVYvLO4f,iv:jzIbVCQ8bGZMkBWj6pnzZqPVFaRlFTi1abRfcOhCiYU=,tag:jPCtO7cK8D9jT1ihvfyaSw==,type:str]
    user: ENC[AES256_GCM,data:5Qruc0AD+aaF,iv:ebvENUsiNCaaxByVpjAUY3JgBk2yAIB2QB22caF3Zag=,tag:WFtfCMuuDoTO2L760NJe8w==,type:str]
    password: ENC[AES256_GCM,data:GKcsjuVPagVO+HxsoXtPrA==,iv:sEkfADbOxyTN5+gzghHWe2dLt6oIcAiqGtGySx0rAyc=,tag:TZDgpgJURcCjoPHyCQZu4w==,type:str]
    port: ENC[AES256_GCM,data:nLPtAA==,iv:Y2PI90V0SihHKfeGQTLQA5CWL0upbZ/lHtWh98B8jbw=,tag:NGS9yH+DkahXtbiMv6Xlug==,type:int]
#ENC[AES256_GCM,data:KxX6hvpqOZ9Q5Dv4cQ7bHybq,iv:NLve2mdUOzula2Y1kJiwhMFHFNwd5fltFvdhO0NR+Ks=,tag:zKyYWnCM0wYl57U0e6rbcg==,type:comment]
server:
  #ENC[AES256_GCM,data:C/pID2DDIpV6BqPLKAex2xWUg+LmJWrf+JrFJ/u+Xav4O6m64NQ=,iv:2wZeZA1ayYaVA89XsORwUKX6Qdu/t+AUpQWPBWsa0GE=,tag:0P8cCkTp91nWVLNFvqYWeg==,type:comment]
  enabled: ENC[AES256_GCM,data:AyBcoQ==,iv:PT2SUGsQsSqUNpRQ7go51ZKQq1YM1fAzuBHiYziRr6c=,tag:vqh0OABQZ5b/TcKf4q/seQ==,type:bool]
  #ENC[AES256_GCM,data:Oht+U7J9wUuCsURwgG1vXln0TqSIuC1uAA==,iv:loJkTVPiQl1rCU8lrrWoNM970pM0UK3OfxGW2XOoY3g=,tag:HCigGyH+hCD996ryql8dIQ==,type:comment]
  name: ENC[AES256_GCM,data:Aq+vDiq4,iv:OkIC9Rlo+aa/ut15cpcpN2/KH9Z1DIejq3fdSM25gPo=,tag:Gs7Dw/qLMj81Cxq/a5Bo+A==,type:str]
  #ENC[AES256_GCM,data:2zAWWx+oGW8b3ltf0jDs4V4wUHJGTU08Do6Z1L01sxGEue+L,iv:JIGKbmM/yv2xOcdLaWV2adZe6rPIH0cZZQB0Jhb0xY4=,tag:o5S32SobJW7BQN6SPG1AHQ==,type:comment]
  replicas: ENC[AES256_GCM,data:YA==,iv:PwQssusogxNGWzqrogsKNtYPJwKfEX7fs6M4xFkzdGg=,tag:a5ICuLpj0DF5itC91nxMrQ==,type:int]
  ingress:
    enabled: ENC[AES256_GCM,data:LSD+bgU=,iv:Zzi/c5sGkDl5v6fK5AQZzmiOyuq20TDVjuCo2v+Ead4=,tag:B2KDrCF1XLupmbEIS2D4ZA==,type:bool]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN0ZLQUc5Zm43a2tCNGxr
        QzhaK2ZSblZtdlZDcnpGd2dKeTB0azNYTTJNCm5ReGxIaENGQlNpMGtyM09vSi9z
        cUYrRi9DVElRb2kxNytLay9aVmtCeDgKLS0tIHM4dnlLTTFpSS83MUV5UEVTelVT
        VisrTXJHSzJ4NUxpMlNpTzlianN4MGMKP9YV03e9tZZVKUE3BG4vhoq1N9g8/+PS
        AcJ2W/MrsbOIttJA15qI6lYuWiaH+WFqpf4vy93RjaF0M/YkNE19SA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T13:08:24Z"
  mac: ENC[AES256_GCM,data:MEgY5hbuXTSs7vIk1Xog4jopM6SAWpSWcRPAuST4wGlzz/sV3zNOYdT8WGVzMQiE9rwVQT1qoPclG6tnErsdPmiLIgU5lKaj2zNxD1YrQ2a1MKZtWLLED4/WkAgmU7pbaRGQzX/t4WYuIhAW+X7mTQjiO0vYSN3gwSccTY1pHec=,iv:MGGlXsdmFGwqU6yridSueA+FDzCd5G9OyW3sg6XK0hs=,tag:EsEwtFxWm80CtBKNW8uNdQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
