controllers:
  main:
    containers:
      main:
        env:
          #ENC[AES256_GCM,data:Tcu2WNKYD8quctRara1BMGLEAoglNPI2NGAR,iv:E3fTPHG7pD5b9sJD5HOlhVhqwtTaUWvf6bi3DAGNIWI=,tag:ICLw8U6vxpIAI9aTcK2V1A==,type:comment]
          DB_HOSTNAME: ENC[AES256_GCM,data:7GiFuSx1fQAQzFhiG7CuNwmubFwHuoU/ZsqLlwAjJUFgLi1n/No=,iv:l/aneoqfqCph/0D4Lw1BNwCegWtjSZytgQahfC+7Y4k=,tag:xlkbab/j9YP29Voqo22REQ==,type:str]
          DB_PORT: ENC[AES256_GCM,data:p4+pnw==,iv:JsvB3RPXYuoPJ4kkltbKWQ7WnT7C/Jn+WAkYJupakJ8=,tag:enNSQAXVpOTvpgCkebqyGA==,type:str]
          DB_USERNAME: ENC[AES256_GCM,data:X0Y8Qk9t,iv:/ZcuNzbUO3tRXJe6StQCHsExvGMw36q6sqhEaFvVpRY=,tag:h0MDAr+SwK1pEC6+M4INjQ==,type:str]
          DB_PASSWORD: ENC[AES256_GCM,data:lhSxX09yUGhHGuQeYcS5fw==,iv:nEsZsxZEiBDFHDyV/dtcjxMdFd3YZ9yvkftJLdRZBJ0=,tag:Kc8E4kkEFKIzEGwB0+Rs+Q==,type:str]
          DB_DATABASE_NAME: ENC[AES256_GCM,data:2wsIdhZD,iv:p5+zFfQ9cdPO/fX/m0E1Q7pFMXnPwbPS9GAV5zIn54U=,tag:GOPmvjKuP+HbLaqpHBJT3g==,type:str]
immich:
  persistence:
    library:
      existingClaim: ENC[AES256_GCM,data:IbYx2s5RCh4b95Bnn7o=,iv:cpgGXhlbAY5iVEQLMuoTitoHnaDPlxLJUwivb+J5EtY=,tag:VyNuvEmGdlyvCm2I0660jg==,type:str]
  configuration: {}
  configurationKind: ENC[AES256_GCM,data:dRFO6Z0FoK1J,iv:9kmhvwV9PJYGbleMAnGGxnTJCNAju6X45yI0IYSbZHU=,tag:PMXsiMUXBzfjUCdr1A4wAA==,type:str]
valkey:
  enabled: ENC[AES256_GCM,data:pZtLwQ==,iv:cvFFpauuMQTk7QpGJRgXI/ScDwZUdY8lNrQ0qwbXPkc=,tag:heSUl5kfro2Ud8fZnNFBFQ==,type:bool]
  persistence:
    data:
      enabled: ENC[AES256_GCM,data:efqQ4w==,iv:d1BbPPOEpcpFjH97ibIv1qOIeYQ6rU0v+lRUYTOWdG8=,tag:jlROt3+WYK6pjedk9o4Olg==,type:bool]
      size: ENC[AES256_GCM,data:9Q6a,iv:a59Vcibn2OeBW8ZsvuffrJGZoHAKQwi6/jGWL27HOJo=,tag:gIfDrk9zJdLbIgsIrLVS1A==,type:str]
      type: ENC[AES256_GCM,data:BVrS+RaL/zt4YOHXid7SgFV7L9d3,iv:TT5CuabupEecuwKsrHiThoN+S6LGxjpJs71o9t0/Ppc=,tag:oOu7lBA8dTdGvB668HYrVw==,type:str]
      accessMode: ENC[AES256_GCM,data:GbDAipq34f0vGs36Qg==,iv:l9a2IOw5cemzgkfz0Pd+m+hsvavgLz2Yo9uEx/nbU9s=,tag:VsVKoMaibtSG41Gqt3dUXA==,type:str]
      storageClass: ENC[AES256_GCM,data:ciIa8gcnxQyvhcwF+TTphqi8,iv:S+zzSOcRl1NlzVfiKTW362/fq1u+l01HyZK/IgQ1kNY=,tag:0zNdFz9KpZ2MG2qYbYWf0g==,type:str]
server:
  ingress:
    main:
      #ENC[AES256_GCM,data:ILfnbA4AA56Y+UEow49wtFIcnngtVxp/HHKd9GN0YoCG,iv:wXLDX4fodXbolkigaHzoVElbWkzBCchZyOzFkwgykHc=,tag:8g0rJcHiUgtWlBTMhRZVUQ==,type:comment]
      enabled: ENC[AES256_GCM,data:hzeKfUY=,iv:YnAargdVOIl5nfz9NvvpPq1Ka3ldi5QlwB5+A19dRw8=,tag:toa5fsC1C61TVh56FBfhUQ==,type:bool]
  controllers:
    main:
      containers:
        main:
          env:
            NODE_EXTRA_CA_CERTS: ENC[AES256_GCM,data:eC3cmldzidZcu2sr6sSLXO5NpXrQ+cNkjiB/cxN1Pg==,iv:gaLcPDq78SsmihuPvUNtDDe5ZY6LK2t4sqhLUITvZuI=,tag:BRvSCF9cNyjusrkD4D8H6g==,type:str]
          additionalVolumeMounts:
            - name: ENC[AES256_GCM,data:NuB6aKxpi+hxdaqwWwWfA8cy,iv:az8tPPp7KWGUBozLmYpTljNfewz30wuh1B8VE+gnZLc=,tag:4SJtwGWZoFQU9mI2eYTS9A==,type:str]
              mountPath: ENC[AES256_GCM,data:G41B6tvC0vPffZ5U6jKA9Axca1vQUc7KK6r5eg==,iv:rVzw1c21vlIipF0Pr8f4bu2TATamW8xlBHElLmY7A70=,tag:MNHTpNw//B9G7sFwIFMKGg==,type:str]
              subPath: ENC[AES256_GCM,data:fShNe7IpcDH0EvXxcg==,iv:Oso/L9m+0cAe8zyOgzGrnD1BlRIuHysou7AubWXwxzU=,tag:wO/DfBCfrZGeEXGYvCTW2w==,type:str]
      volumes:
        - name: ENC[AES256_GCM,data:F3D8jsRo7oNL72zhYfB0nxaa,iv:YQU0Q/n+petfEExbUPyYYQYA5DuKQSURUwrvWNJ82Us=,tag:tZouO8p/tlzfM9FTz/VsJQ==,type:str]
          configMap:
            name: ENC[AES256_GCM,data:cmYhkJC1ekjvSwEYdEagyFDf,iv:d58fEdelzxYaiwSfkHZSlXNUTGTjmg2WIX3qfotidGs=,tag:1Dz5nv7YzSbvDRmz2QdmIQ==,type:str]
machine-learning:
  enabled: ENC[AES256_GCM,data:F8PeEQ==,iv:jKceMeeo3kLNPI2/9FpvRxVTGmmQNtVCmfDQsVsUWAU=,tag:V4of5chmKJW4JhqCn6rTXQ==,type:bool]
  persistence:
    cache:
      enabled: ENC[AES256_GCM,data:2w0+ng==,iv:rNFtu1wAWcyOpx8LTKiVZo1tWknk1BBPNIbPjx3UqUs=,tag:y0gqX/uwy8r8n0VAmjHfuQ==,type:bool]
      type: ENC[AES256_GCM,data:0Y/uzQH0NNPks/9Rmgal0x73bIMN,iv:AggSv+t/8oWvUR/QmvhL1myLOVyrBBc9IIX2strt090=,tag:DyatOUKT3GRVGeTGI86tLg==,type:str]
      size: ENC[AES256_GCM,data:HWA1FQ==,iv:zNodOVt7CN0JOoE99mJE+SOKrvrmkhdF3+ZT3GlWJVs=,tag:pbeNA2+h7zzHx7P+Ark96Q==,type:str]
      accessMode: ENC[AES256_GCM,data:RObMj3n+RhOgvDOcuw==,iv:PlqlT2OboGfnzZB1GuPhW33f87beP1KE+Vw5NDhkUIY=,tag:qDTr18TsCLTC1XDDG0j0lA==,type:str]
      storageClass: ENC[AES256_GCM,data:8y/Rc1IVFu8XfrhMzyPv+F3I,iv:J2ymW7DiBDKgLN36S/k/CAiPZI2rdKNHMwyqwDQZ4j4=,tag:3wVzJNpvIn5ouWfOzhpUxg==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTWpRWHVrUmRFaXd5cHBH
        VEIvR3pBY3FzRGpGT1ExREhVL1I2OWtyQlRBCjRESERSMStCTnNVdEJHb0svNGdB
        eGFRNlBQWmdoMk1VNGJEOHBvRjNpQ0UKLS0tIFZNTytYeHFNZmV6ZlVyOCsycWQ2
        R0h2dGg4SHFWcWx3Sk4zdzUvaXZZM3MKd66GIKqZNJxCuG7//Aynke3+DBHT00wa
        fgVogndEaW24+/7XI1f/7LjIizjlZ/PDNZojaI8DGp1A54MT1ccZ4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T15:15:06Z"
  mac: ENC[AES256_GCM,data:hJ9hR57GJamUTrPuoLmxJHMJ65cwrWjC15yUPONTVbLn04gcFZJEaMwcs0vKmcXILHs6ruhOx6ieBePn7d5F3hYCThAcgmiHqi3rtVZnigJCuVErGCPyCxBw+HMu5pvP7Cs1P6tjSltiIOT85SlX7jNd1KOIQTwRwiOA5uTb3dY=,iv:OOvWBH8K4mBldC9pQz8PQun7OKdb906kjK7rBZnaeVE=,tag:ZJ65vzVjb/51r1FQ8czdrg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
