controllers:
  main:
    containers:
      main:
        env:
          #ENC[AES256_GCM,data:pRJDGKOW7poSe9er/jPVwBuRGT4iAwisxuF0,iv:sgSr9JQxzqLCgAKDMT/UPh6f2hHuPfTRP3/mQ1zY0wI=,tag:M/esGqKYEZ1PFuoYmtkCyg==,type:comment]
          DB_HOSTNAME: ENC[AES256_GCM,data:nIHk+eXk9+gjBLqTIOtggTr7Stc/zyRlFwIxzZ2SLbHwZECVzJk=,iv:IANP7uOGFMflrBRnG5E4uUyrG/QvoNJiF/rG0F7X3vY=,tag:OsiqT8jO5klvYPIqr2USlw==,type:str]
          DB_PORT: ENC[AES256_GCM,data:bm7ffg==,iv:CHu+GGiUwIdO5ZiUX73aQvjqpu7JVSpAoeDvrvGreg0=,tag:zZnpcTU1fJW4iQraNTp7hQ==,type:str]
          DB_USERNAME: ENC[AES256_GCM,data:2eexh629,iv:gIRdVAByRNBVU1gEDIJsKFqH7V6C5fbnXzYdpwAY2Ko=,tag:ZTU5bEcZBnxfkzXiZLx5Rw==,type:str]
          DB_PASSWORD: ENC[AES256_GCM,data:S1J675UV,iv:iD0YBIhby3lTtJ6d/e/MboCd/ckDDX11mqAI3kaD+O4=,tag:xc6acCYq5fnEusbmCngJIg==,type:str]
          DB_DATABASE_NAME: ENC[AES256_GCM,data:dMMJV0vR,iv:dY/YQv/hmYMkOye2IWEBnlSjk5q2iI+GVNxTCI8lXYE=,tag:vmi9KqaCqPyPzk88CppI+w==,type:str]
immich:
  persistence:
    library:
      existingClaim: ENC[AES256_GCM,data:JmbWGz23TVqEAHf4JUc=,iv:t8xwh47PgGuO/mMKOu/hSWEHE6a7Kdgp5IjG8MP0BCk=,tag:WDtC5Xq/4nVexgRjb1B+ww==,type:str]
  configuration: {}
  configurationKind: ENC[AES256_GCM,data:YLy1G62t1aAR,iv:7RP7hAunzNqu6Hr/OjFGR2RBx27reUJAXuPnQtZVnpE=,tag:psKNrsNSmzkKl5Ylq9NAkw==,type:str]
valkey:
  enabled: ENC[AES256_GCM,data:4u5+aQ==,iv:0zUmmzYEPC9duNFNv5nRyBz5a5u1lQvwu0jdXhUnGFU=,tag:oPpq4PbUU56jr69MfqL/MQ==,type:bool]
  persistence:
    data:
      enabled: ENC[AES256_GCM,data:cMBCFg==,iv:s8aQFdJHl97gveCR2wBipgnmfdrF9QNukN9t1zRsF3w=,tag:Zh4mog+RyAhQzynroX5z2Q==,type:bool]
      size: ENC[AES256_GCM,data:IVIW,iv:TH1B/PhMu3VqhkhYJtszWRRw9zrGkh2dZ1JoKXxoeuU=,tag:/BtU/c54bXQmnUjp5/XiVg==,type:str]
      type: ENC[AES256_GCM,data:uk/c8AhlLzjp1/FNutlD5J6Dz01R,iv:BliLjVChY3GJTSgydBsCE/cytsD+kvPYgJk01qyGFeQ=,tag:8cG5DOtfyat/OpM/XLgQbQ==,type:str]
      accessMode: ENC[AES256_GCM,data:Mh+Wjg958CnyIl/ZQQ==,iv:lpQo0rx6xP+yNiEBtZnFRaU2aHjjI9o0pm7hgwTmFOs=,tag:ZXTM3POgEkRp7zcTi4QsVw==,type:str]
      storageClass: ENC[AES256_GCM,data:JpjBRCcqnGYHm4aHCXX6sTQ2,iv:+TCDcFAmf9/+17TpqxO0Xv/2Ms2hChuP4VFZIbpGTiw=,tag:Vd42oCE2cAMx6dU4wjp0RQ==,type:str]
server:
  ingress:
    main:
      #ENC[AES256_GCM,data:qddodfjjpCWxc2M488Ntzk90Lw9xgjdE7hBCd7gou0wV,iv:Yk1XDt2VCvhOlBk1pslYEHJTUk/L8yuXQik5Rl4tkYU=,tag:5aEMRVYEkndSN4YWG0+upg==,type:comment]
      enabled: ENC[AES256_GCM,data:eSA/zy8=,iv:L2pBK4vHPe0RAQE0KEVXw/OkXdXiW+EYaYfYriv0Y58=,tag:FtqmcM1TVUvgXUS/tS1aVQ==,type:bool]
machine-learning:
  enabled: ENC[AES256_GCM,data:tvgABQ==,iv:5RDDA6iirLYoPcpGx6nph3AUHzxayZOm4BxooSdKVeU=,tag:YCrls0RvG0rBsb7BfdtLRA==,type:bool]
  persistence:
    cache:
      enabled: ENC[AES256_GCM,data:fo7CMw==,iv:kQW6pot33PDu8QOhUgn2vz+3lvEMmMoWFnFN5oGYoqY=,tag:lhGqFNbfgZ2yWaWSxKnjjQ==,type:bool]
      type: ENC[AES256_GCM,data:UXvNjJIJvYV4cCK+FehWiSPg1jbQ,iv:suZWNr8zK5EYKA4qTxLqZNzCbpKjUkfkmR3Wk3PFMvk=,tag:oxPOtROFudWCsmnz9jQHtQ==,type:str]
      size: ENC[AES256_GCM,data:FDNPAw==,iv:cnzneXRqGXk82MyDiZu5XJbp0SCgowZn+lTP2Htw/rs=,tag:XNJ51gVM8l/5mxjB9mE/wA==,type:str]
      accessMode: ENC[AES256_GCM,data:hYJH8g2N+S+xkR+CoA==,iv:ZpB5OKh8EEVx6xurW/pDerwNWgAqd75lXUhetnYD4T4=,tag:GxLNJZy38+FZQgYr0k38zQ==,type:str]
      storageClass: ENC[AES256_GCM,data:ngNYJ4N3ZXG1gapvYXC/dwCJ,iv:PJSFoOw4jkN955aoMTsUD/XObmkd92i8qjP7uixi0hM=,tag:+WBZf/ughG2gOwa59A6HhQ==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWVJYOHRlR2VySUM4NE83
        bS9FVCtGYk5uTU1ZOFM1K3dhY3lxRjVRcTFVCitrakNlUXlQeThPRHl1UHpJUGpj
        MU5iZTBrREJyYXpXK1NnYUg3aUw3RlEKLS0tIHFZck40b3ByWUQzUTVDNnVMYVA4
        bm5EWTN0ZjJFNGRkYjFOekhYVy9BVEkKOPnBR31T5mjlrgGXw6c9LTzqC3imrRVG
        UdMVwOW8+tDtfSap/0n8r39HujDHE8JgxoHQi+YIt41I95XaNt//ig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T13:21:54Z"
  mac: ENC[AES256_GCM,data:qABx3VFg/jd4M3MgFs2x4Zr4W63XPgePAW+3BFluvIGP+DFED/Z2wrHAM7VVhdKy6GhI3Ve7Jaqy9gTRjDqQZw51wJtDFKh27vGrYCdnKLnN/2VojvU/9g5k9znTzTexkEf3GyoycM6lv5TAxwbSihnN4B7k4v/JzPbVMFacfZM=,iv:3whvbC4cK/fGX2uC+pMY95Ss6Js2T6Am6hNaIdC5kzY=,tag:wPSp4BsJ1ZDMa3gstG3M5Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
