controllers:
  main:
    containers:
      main:
        env:
          #ENC[AES256_GCM,data:oUgW4XjSq8jvslfUlVNVWYbR/MQHX5awnq1D,iv:ylAEjzgyB/C3gFWIc7G0cFpyXPDQ0WyWCb1OddWTHEY=,tag:6zWIbAnPaMq7ZYIO97RqWA==,type:comment]
          DB_HOSTNAME: ENC[AES256_GCM,data:21TjxLQCOg6IvXsIck+1aKAfb1tLcZMC3gXaYWnaijjuSAUiwyw=,iv:J28DrlhjjsJbzXz+J5N1I6Ro24usmoh8aH0rgmMlnos=,tag:N+bCBa8Iz5882vO0mTO53g==,type:str]
          DB_PORT: ENC[AES256_GCM,data:s3oVhw==,iv:nyOm8z0UwkPCP5+IbW3J/Yygl9XbtW24kSe5yzPiv9w=,tag:Uxktp8H9Kpc5D/eNEBdC8A==,type:str]
          DB_USERNAME: ENC[AES256_GCM,data:pq+Spz3e,iv:1J9tY/i28igSexg+nJ3pruGFlYk32H5E3OV7uemvGOk=,tag:Wo0RGwdN1x4x+4q6Ty8PiA==,type:str]
          DB_PASSWORD: ENC[AES256_GCM,data:cQT5iiD1EnuDCIDT9sQXog==,iv:vdQIzUvnBCpUoK/C4kFyRZcI5SAQ++UKwEZ7y/k4prI=,tag:J0g0QQHDXa9oMUOKuXj7ug==,type:str]
          DB_DATABASE_NAME: ENC[AES256_GCM,data:nqu7QOlF,iv:MowNUTNzEpbjFjaxmiu79xlDt8Oj6mEDtY8L7w7yDl8=,tag:ls0JVrLigyg8bD9kn8Ojug==,type:str]
          NODE_EXTRA_CA_CERTS: ENC[AES256_GCM,data:6owLdMoNbA0s8NTRJPKAHF+1jkebu3sXL8klHvOLwrWadA==,iv:i0OD7uFTubCQ1YqvVOfciWM+gOkKoX8hf4g2up3+nQU=,tag:Ux6CZ6j8uqQITaBO83tAXw==,type:str]
immich:
  persistence:
    library:
      existingClaim: ENC[AES256_GCM,data:sWod0kSqm1btrT6AjVk=,iv:fhf4AjiQ1Uzcq6oEGDgYLjtJPyPz6jVYcislagefTGc=,tag:pdjnHZAlCVGJBp47nLLkPg==,type:str]
  configuration: {}
  configurationKind: ENC[AES256_GCM,data:XzhYjSBbn3Df,iv:umxd1g/GLgehPTXgraSktQgzD0jS4B8tfnwg6Uu5Uys=,tag:g0HCP7C/Pzf+p1Y26dObfw==,type:str]
valkey:
  enabled: ENC[AES256_GCM,data:7NKhpA==,iv:B1viZAD2mFaeCBbdqO3Fk7PdMoNFJqwObM9O2LJUbuM=,tag:0fIT0wYKJpkLlT622jpilw==,type:bool]
  persistence:
    data:
      enabled: ENC[AES256_GCM,data:8bMdUg==,iv:6QoW5DpkuYD8ZWwCTcLwxO3d3U5kP2+AH2deAZ3EE3k=,tag:lK4TpmXtnVn4k4Z/6Z3V7A==,type:bool]
      size: ENC[AES256_GCM,data:f1sH,iv:nR9nc/oi5G4ak8PIm9W+2OGMslBBdQD3vsoyouuPR0M=,tag:rfr3b2h2h8EK8+Kg3jHfCQ==,type:str]
      type: ENC[AES256_GCM,data:JXYW+xNX7iqrmrwmlwou6lsRgUCS,iv:0x7hYXfaNmBw631q2wytheTzc8ogGxGU4XrVhJaQkQk=,tag:1CMe1A8L9DuBJCaCE2cRJQ==,type:str]
      accessMode: ENC[AES256_GCM,data:2pW+3t8lZQfBk5408g==,iv:M+bUo54+x2lFw3esPvowA20jH1qZZ6nFpTd16oQhs8k=,tag:wz3ztlwohkAEQlgEgiuTTA==,type:str]
      storageClass: ENC[AES256_GCM,data:Q9H+psn83PJ6wKjxgs0PCFyJ,iv:qVvXJQ/cm/pNpgnnykdrduXkMghZpdexO6Kfmqy0Wqo=,tag:ODkxITInsFf8EsD5+/1HkA==,type:str]
server:
  ingress:
    main:
      #ENC[AES256_GCM,data:BIpg56fefrmPVKN3vf0GeQAXeVJm21+SNNskq9f5Fub0,iv:zyQ/Fm0JLntiMR1F7NBxQh7QqQr+1F4iOO9vS3V+sf8=,tag:anYJMaFoFihWIQgMfJH9rw==,type:comment]
      enabled: ENC[AES256_GCM,data:kR98GiI=,iv:AY0vxs6XWPyNufVwr/S75eZAV7wjpKLJOAs3igUIlNI=,tag:R2wAqDS+qrRmTAxlY/xwzg==,type:bool]
machine-learning:
  enabled: ENC[AES256_GCM,data:qrokYw==,iv:7Q/ktwjWaKqGW+exMDoO5zJ2zwG5LJFmgUc3u3i/uY0=,tag:uU3+EMBmVQkMwoRGFu7PAA==,type:bool]
  persistence:
    cache:
      enabled: ENC[AES256_GCM,data:101GmA==,iv:WR58cToWx7WXthsJ55m4temDWhb1g1mcyZByICjQxQE=,tag:2zOY8He2eD38S1MyM42pvg==,type:bool]
      type: ENC[AES256_GCM,data:opCNSeUMavtoCnhi+My1xC0nvMpg,iv:nKtxjS7C295rqXyjhsshRSalB1sl0HVDe/iT/8nNQuQ=,tag:RwXnuc+jTVTclHjdG6n/jA==,type:str]
      size: ENC[AES256_GCM,data:dLCQ8Q==,iv:56eZkdvGuDk3gD7Usq6cYB/C831TPnMGMa/6r6U9HaM=,tag:NVrbmoGJjbT7Z+xhr6xRGg==,type:str]
      accessMode: ENC[AES256_GCM,data:s85YS63w58pQgaHlRg==,iv:NTS1601+tdMv6Bg/RAvUnkLg1rwyjQzygL+eeHgT2zU=,tag:QHAyxG6n0MDj30EvbqN8dg==,type:str]
      storageClass: ENC[AES256_GCM,data:tBqMMSQv5lr+phmggdNVU/CT,iv:WvQB69q/yZ1XMKRSSLQRVuIKYAbGAXJZWFdB/LzKKIc=,tag:UFtKro+eG/mutKJndHxVYg==,type:str]
#ENC[AES256_GCM,data:SlUbACBf4GOh2bTzfbXA8myTHFfZmHECtA==,iv:tuSmAlGy/4BLMkvux2BEsTJbdjl4UP81Le2TFybXiKg=,tag:H7J1JVKNdVbUmGhmkizpqQ==,type:comment]
persistence:
  internal-step-root:
    enabled: ENC[AES256_GCM,data:AV/RDw==,iv:acb1Ed+HhpGXhTwJ1xmp/vjc83mDAIgKdcFuHrpt2H0=,tag:kUU6xj3W+zUktyKI1Q/eGw==,type:bool]
    type: ENC[AES256_GCM,data:Vn8EJgfOQY+2,iv:flRyrl5zIVXc9b/wZYl28kTlO+6UfM52CSVOEukYHx8=,tag:LvocR+zgA/Jbw+LWz1mwug==,type:str]
    name: ENC[AES256_GCM,data:JJ9xKo916WcBJX9khV3o6TZR,iv:zz1VBwCnTu682IEwVKITERID+ZX6ZZ9olJsSIE89ISY=,tag:3zuGeG41QPDLbyfG14nmfA==,type:str]
    globalMounts:
      - path: ENC[AES256_GCM,data:B2O8tFSdBMlxP/gH1us=,iv:wnbDTASz5x0/Fev3Tx261wHstmJdEosRVfkyZPjZPzE=,tag:qHMtGQUPGIxk23kCkA+vhw==,type:str]
        readOnly: ENC[AES256_GCM,data:rxLiSQ==,iv:eCf4Qmbnjmn0yfTmRp5MVd1Mk7lEXMNtlxvoorHh7iA=,tag:TJ4Tn0QQwfjAWrBElBbO6w==,type:bool]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVFlvR1ZsSVBYV1U2UjQw
        UDBhbFdmazV2VTlrUmVQT0c5R3BnVXNFY0NBCjVEeW5Yb1Y3aTQ1M1ZEenNUK212
        czdYdHdnK3B1WGVaODhEVTVpa3c2aHcKLS0tICt6YTBTUkN6VzFNbVFZaW5iczBx
        UnhoRjFuYlJwbzIvWDlOaE9FbE4zU3MK4WThxfrilYOH39EAg3Dnh4pgHXQy3D6J
        zDou1ZdODhK+GjNA071Tx1XLZElZSwO2BuF4EgIxZTnbQvqF/ZtQfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T16:25:51Z"
  mac: ENC[AES256_GCM,data:h8szLF+in8v1eS/tj1S7OqMsj5kPQUbluGLQkZFxWbtOsP8Cswgw0o5TeGMJrBgNIefzgJa3oMSO/JlfdYEVprhMMyZqu/zj8xSAOEqKKv6fMxkDh2ZFoT+FlCNTWP6tYgNKsZxqoA9+tBUkapt8a0aGwVx/m4XGUZh4ubaDvQQ=,iv:O1nOLtLCBzP+yGur6SHEx4wZYVcP2t+UL99mlW1LJy8=,tag:MXmrRQiAQOo1+b2OdOlmDA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
