controllers:
  main:
    containers:
      main:
        env:
          #ENC[AES256_GCM,data:5CXrAsEz0I+Ej2o4jp/jJcl6OeENp7rJ6dD2,iv:8bIiwqGOtCmAfRt3cr2pNPJiuZzIR0HUqCoGoGpoaFo=,tag:kujOxGkfd4WLnKU+1x2npg==,type:comment]
          DB_HOSTNAME: ENC[AES256_GCM,data:dy9ihF919KX7ROs0Iq5ZYww0BYE3X9DLr7n3PmTlwhFLhRhrFYk=,iv:HPoWB/gF5BH/ou1Ocq/OY4pfyoh+yTc80rmUY4Z9EFE=,tag:ZVtW+xQm1f59UTBgjCwpmg==,type:str]
          DB_PORT: ENC[AES256_GCM,data:7rbokQ==,iv:5u7W8ouhJHapcsNsSclDQgQtPxJfC0/rkL+3wdk6aCA=,tag:fyxpTS5RxCG3ndLxINcaUw==,type:str]
          DB_USERNAME: ENC[AES256_GCM,data:JLVnLb2G,iv:BdEEUliyIcnH0xeo0nRqjixEHFJHGED6o1XRKT74LEc=,tag:mGu2nv7x1b3vvkhGXekAWg==,type:str]
          DB_PASSWORD: ENC[AES256_GCM,data:cvSZbl0ruRSFob2wlZAsmg==,iv:6jWHBPuPQ2g1+76hnAGO6zGfO6hTDwzrqRNbTacINkY=,tag:ISTwj7T5vNfxQj6YqbaA9w==,type:str]
          DB_DATABASE_NAME: ENC[AES256_GCM,data:S/NFlsBl,iv:su7vFQ7k5iWIKSldHcaaDrG6OHlfhT71yy4Cr7FVUBo=,tag:I6yj6OQwHkb3v44+TINmtA==,type:str]
immich:
  persistence:
    library:
      existingClaim: ENC[AES256_GCM,data:qs8iA3FVdH5ytRMSwGY=,iv:RkwWkUlREkiQ+UeRp64HNbGR4iJHX7OFOHoZsq5SOoU=,tag:pCJ2EXVTX/K2tcjWiJlTAw==,type:str]
  configuration: {}
  configurationKind: ENC[AES256_GCM,data:5IcgPHLh5tQH,iv:ReR7Uo/kF16gJf8YeBbG+u6eS+0qZ2jyTwtvo80pNuY=,tag:xmTJa6fPerDCsEyo2eVILw==,type:str]
valkey:
  enabled: ENC[AES256_GCM,data:O84Aew==,iv:l+T/fvP72XHxyDq437ezzPsh4HV08AAPB8ChabAh6+0=,tag:FVLAmwXQI1IMwmntopeh7A==,type:bool]
  persistence:
    data:
      enabled: ENC[AES256_GCM,data:1yTjVw==,iv:0NQmM6D7dOitCYLar6hguGHOgT3vFNWYFITLCnK7ESc=,tag:q8Iqa0mcsqUzdCUsBhP82w==,type:bool]
      size: ENC[AES256_GCM,data:nvFZ,iv:JGLclcJx0nGXIvtneKrJKuxumRpR5col6U7/O/rAm+4=,tag:jXHYKnVWVBxzeMggvlrzOg==,type:str]
      type: ENC[AES256_GCM,data:eH5FMsmXf6prjlrSVt7UcIi92PwI,iv:Gh6ixdo+XZKslBac7daFIXnsO7uqqyzKmfrNMDcIuA0=,tag:ItDGOUTNwwtwsK3MAoSovQ==,type:str]
      accessMode: ENC[AES256_GCM,data:94FOAMjf8cf6ofReSg==,iv:05IIK72yyCn9ZeQzrVQVvKrCeP4oDfEtB24IwP7NetQ=,tag:czsqN7nfrjXJe6ISCcCgLg==,type:str]
      storageClass: ENC[AES256_GCM,data:fP7enn/Q5hLqcgNGzet3PIRj,iv:YP9A3kciCSUrMxVWK78IK1gtPv2TK15Qu6jcpiw7HtU=,tag:Wl5t4LhA8Tk5ZQNkFKh3Xw==,type:str]
server:
  ingress:
    main:
      #ENC[AES256_GCM,data:GlfGjbxVFm50MZ2sOn3stpT7Qls9ITCs0M2NUhMx0gjG,iv:8L0LxcXOq7N5u7f1E19DJMCBlqWG7nIvw/T8ojg9psA=,tag:50ZMwIPWwzLxU0T+1cMEmQ==,type:comment]
      enabled: ENC[AES256_GCM,data:MCqNZwY=,iv:zbxCdpLwYoJRCJZ8l4w+B7sDKhNRCLuHVMMHsC/Wch0=,tag:TxWqoWy11Ld8eC/+XN9zOA==,type:bool]
  controllers:
    main:
      containers:
        main:
          env:
            NODE_EXTRA_CA_CERTS: ENC[AES256_GCM,data:dvkJbvSuB5yyNvhN9xum9Aj5hYkPkcOvVYuFNnyj9w==,iv:YnxzeFONSMYX2jxo+ByzNRiY9ePdtuffpY0LPM8fbWU=,tag:QAQHIzo7J0yM/7h6PVSIJA==,type:str]
          volumeMounts:
            - name: ENC[AES256_GCM,data:TwrHh8Hw5i6dL5Nc1YUcMrt7,iv:z/nUWGg4sg5bUCBUr/9O1cfauaP8WpQFekkdYnA8v0M=,tag:dyc5jzrWeiRDtIwuP7ShyQ==,type:str]
              mountPath: ENC[AES256_GCM,data:v52gRpwFGs1xYXsHKisSqGESJT+bR/LGO2CyyxPmFw==,iv:w3GabIEmoV4vHMDVLQjZvL+gAEQ5MZGtL0yGETeeMN4=,tag:gVjCQ4Vwv3K7+7rRBGlcuQ==,type:str]
              subPath: ENC[AES256_GCM,data:X0/FuxWR4iulcmJFuQ==,iv:36ktPGhmhsIdU137jhs87894VXh1p50PuVtGL6AQO2E=,tag:hIUrAyLmQUYwWNRCyaDuWg==,type:str]
      volumes:
        - name: ENC[AES256_GCM,data:XsbVnCWEoHPraLIVAkBjseyn,iv:UlCpab90kNRV5o+XKWcJeFt5We0mNRkO2clTsUcOKL8=,tag:ON4U7h9d1+cz1TA+0wsbkQ==,type:str]
          configMap:
            name: ENC[AES256_GCM,data:YBJzU3N6siO2HoKfRHLLmsNs,iv:syM/h4M7BBgUKMdYzPdZNv6GbRjvvgU6n2wFU45kbY0=,tag:wVaIlCB4MD/MV9QWW6HbEw==,type:str]
machine-learning:
  enabled: ENC[AES256_GCM,data:3s1NfQ==,iv:uM7Z7jDQ3oKOK6PO8oWHkippJbZuTzbU6xUIOk1ciw4=,tag:/lJAFYBG2kwWQu/1lQSKzg==,type:bool]
  persistence:
    cache:
      enabled: ENC[AES256_GCM,data:+w6MjQ==,iv:PfzWVit1Ibq+jUuWg22drtC+zck1/ySuC4eFO6TlkAs=,tag:wdEdkjfhSHX8bmx0ALOLWA==,type:bool]
      type: ENC[AES256_GCM,data:McgLLVfA37q2OPPw4qLQTHB37/pb,iv:cJp/wtf8icDNqIqorFMjJmOKPP7wVV2uel/4kI7Y2Wc=,tag:m4mHF/+zttZfHRpRYhhT8Q==,type:str]
      size: ENC[AES256_GCM,data:erK3/w==,iv:NZdvv7pmbmcu2rqZ1E5cHoRUuf+HPpagCd6rPUnOlkU=,tag:SZVULwFGU4EbdQCepvsfIw==,type:str]
      accessMode: ENC[AES256_GCM,data:OqaHDPnmfD7GPOBnzg==,iv:dlKTt7n9FUNCFjhRG0rLwVQIdJxlMNGqJIAtWhJRBv8=,tag:7EDsTx/YmwpPq9xiqUs3Fg==,type:str]
      storageClass: ENC[AES256_GCM,data:5aLchyddbB72CJ/oMEg2xr8a,iv:WD+L7mGXxZbuDbK2dute6Cc4jLHMNhAFQ0fg+uI9Qf4=,tag:yoL2M7zeBfTJq8RFV5Bckw==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU1ZqbXVCejh2Ym5xcnd4
        Tm5aU3lOMlR1SEt6TzJwZkNkR3JWVGJoV3pJCmluSlcwcTM0dGlNbkc4SWVZaHQv
        Wk90M1Byck5KQVBlNGJ4UzV6bm1vdUEKLS0tIEFFRGRVR1VhTkxud0FsTmoramtV
        RnIxT1VkenFhTTNJem5jS1dDWm9taGsK7JbnKvgtmouttkteGfRcnxdSWlacKSOY
        s0MyAuDZLMe53o3r9GdnQZ74NHsD6RhBb4znfrsD0KZ9/zrcJfrmUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T15:02:31Z"
  mac: ENC[AES256_GCM,data:CWt3Z/jJuaPklgZkMDMRhX2NckptgQPUuNA8XoIaeT9dFNwFLbrZZ26xgZBiDKiwt1gx6op4mfUR4IJI4QyBstak+Kc/I7/84Q9At2+M5omoJvAkM9hubH2jPsa61H9DJz7chBINB+yyGFEJ8WgsZhVJ0pfaEIDFASLNZvi2Wgg=,iv:oxlnzitgUL3XXmckGikQ1ZkPoJt263nPeCpLbXhAd6A=,tag:XMz5n95vG/eNxt6/6k8fvA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
