controllers:
  main:
    containers:
      main:
        env:
          #ENC[AES256_GCM,data:5ewv07Itttg4Y0Whnfc/aG8jOJT7MlYGdxpL,iv:YWs89NSXdTFm9u0uuGcCNUxBxJPUbvM7RBIPG9SSdS8=,tag:fvZi88VKj//DIb828561Sg==,type:comment]
          DB_HOSTNAME: ENC[AES256_GCM,data:f4HnU0NyPDechVuMiz413W6OxFJGhSqmdIeRe/cwzY0lkJB2iIo=,iv:27lt9DEbSe41e80TSKezKF8pjQNRv0W9gfGo9lHKaLI=,tag:61/EEV8pKV9fKAPzieP6Zg==,type:str]
          DB_PORT: ENC[AES256_GCM,data:X5cHhw==,iv:DS4xs44MjELuo8tLqE+Pk6n5ioCj5cW5huaLEOV7soE=,tag:JxrhhXwMpHUfN7UOUECEqw==,type:str]
          DB_USERNAME: ENC[AES256_GCM,data:vedkv/iR,iv:qw3l1KIuOfqynDZFk2fHGmpBaF6eyGV39GhmWHGZp1Y=,tag:SZWxL5uFm36O8/4fnSXSfA==,type:str]
          DB_PASSWORD: ENC[AES256_GCM,data:q+WHpMt+JNXwwMlDYrt7RA==,iv:iCsa2p+3fk3c3JUOgVGnCT51OE/IsZwuQ+oSvWeaHrM=,tag:M0BxL7V+r7TzTdT1HaYwEA==,type:str]
          DB_DATABASE_NAME: ENC[AES256_GCM,data:63VZlGrL,iv:mU2wZ5fb4LRp1mHo5hYhj2FsJ4f4qM2IZls1I5PjoJ4=,tag:WPZ8lxvm8Lr8jYG37wi3Dg==,type:str]
immich:
  persistence:
    library:
      existingClaim: ENC[AES256_GCM,data:ZDW9zWm45I31npv5tCU=,iv:R4nncNYoffVwFXGAKDU9CAEmJ8gBQ2gi8NAuwuojFFU=,tag:aAVwsJFgXgx3e22MFMyV6Q==,type:str]
  configuration: {}
  configurationKind: ENC[AES256_GCM,data:9PrrLjCuk5ys,iv:RozqBmKb/FtDwGkhczLoWvY64bQXmt1ww9m/pQ2xqWY=,tag:Gi02/oumCtRx0blTDOATOg==,type:str]
valkey:
  enabled: ENC[AES256_GCM,data:8x+T+A==,iv:cmSnYndkuyg2/0Q2MsuMVpNhSdN0x8uJ5eLoApAGfOQ=,tag:vGnANRW8gFeA7B1aj4YKig==,type:bool]
  persistence:
    data:
      enabled: ENC[AES256_GCM,data:rq756w==,iv:KBlIyf6sslNcZ78959eyQA5sJn70nXxPa9pwN0sNBxg=,tag:e1lnA41iHjYbouxHsaZqmA==,type:bool]
      size: ENC[AES256_GCM,data:v1f/,iv:NMi60xVbJB9GurLsq8Axfj8TY+Q9iRtjhdYCYo78ewE=,tag:CdqNj//mG9/sZhrFVF/4cQ==,type:str]
      type: ENC[AES256_GCM,data:lO3pZteoidRMeKNZ/FcmOrVM864F,iv:bByLf+RNrNQ6x3QURDB7ZcqU6ZXz7SLMm/paGMF7vZc=,tag:mk7o964UOHowUBlt01xiGw==,type:str]
      accessMode: ENC[AES256_GCM,data:TfCR5zM0N6+cYpNJYg==,iv:oQViSPMHIz30G7FsYkMcGzKZSto8pNIvu3R3FDitv4s=,tag:AhpED+8lDzBCqVeW/FXWqw==,type:str]
      storageClass: ENC[AES256_GCM,data:Azd9s0HoSWwEnLtpobl/sm+K,iv:KoMwW8WDnJgWPy5+1hsV3sXklf2A5am3y+Yf6JZ7BYs=,tag:EdUqWN363TmmrjHHMExc3A==,type:str]
server:
  ingress:
    main:
      #ENC[AES256_GCM,data:IKWp/9axdlrzNHQ40U9UkIJhKA7YD805TbMEbGOAu9nk,iv:iWvsWvJIWIEBldh7zVkaDwWgAU/q+9GrmBtcjyR9hJ4=,tag:nlp+IRJ+hufhZlXdWKkJHQ==,type:comment]
      enabled: ENC[AES256_GCM,data:HLIJ530=,iv:4upCtiazRYIrSIUKVQ4h+JdaLEPTvz57W8trYiXKO6Y=,tag:V088s2RrKder3za+k7FnPQ==,type:bool]
machine-learning:
  enabled: ENC[AES256_GCM,data:UcUr/w==,iv:olOFnlok77wX2Bv/qN2P2c1RNfEcCCE9iWPPKyQU7kc=,tag:5z/vqlALDjV/d/kE4aS+8g==,type:bool]
  persistence:
    cache:
      enabled: ENC[AES256_GCM,data:x3/zUA==,iv:dMfsw3mve9rSL5WUvGoMjsMytGqCP1HItu9cXcI97JA=,tag:jSh8A7MkjjPEhYS6Tr1hPA==,type:bool]
      type: ENC[AES256_GCM,data:KvIUAIwKEulYE9hTnyK0afWae4Az,iv:Cr/KOngDztufsmCPnAooefVG9ijL0b6Pk42ufk8yA04=,tag:12w/+Dvq9FMhYutO4H/+5Q==,type:str]
      size: ENC[AES256_GCM,data:7ra22Q==,iv:Pxr53YnarmuCDnyujAKE2OF7ANmBzDsR9wP+xEwfjQg=,tag:r9uqtGEb+8f1N1kT+s+zGA==,type:str]
      accessMode: ENC[AES256_GCM,data:/WiZ/acmIUKShLAq1A==,iv:JUAuBTMZZyOvUwhk1HTa8RDRvpW+ufPWljDehG7aePM=,tag:fJyzL+Tiyo9cLSo1e5XhEw==,type:str]
      storageClass: ENC[AES256_GCM,data:A61kSWPyXWTO08GN5CXZoZEH,iv:dS4hCS39rKp6pj+gX/WrFLXdpkDO0lcpmQuoRvTxoBU=,tag:iQgbKeTUjH/l1AyMVgy4qQ==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQlZrVVZwMmJKTjM4RHpw
        WEtpTkQ1V2ZjL0NVaUljcjZoTlJUajZhWXdBCklTS3UyWVR3dFVUR210anB6QU5w
        M2FpcEREdEIyMTR6U3hCelFFM3hJZTgKLS0tIGNzbXJteVZ2MnJDcnh1Z05uMHk5
        VC9YK0NySURNVXo4ZkZ6b0ZVamwxUEEKW5H5Y0fCTeEA+e0dSgSPSl04yszYmX8o
        IYxLi/j9yL6Epigdzq9kuDa9jAGmdYE2B63VB6WsOVSWP3XEHk1c1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T13:34:20Z"
  mac: ENC[AES256_GCM,data:XIUJRwyM0IF6Ne2s27d2fB38XZUDvqLm/vWpEHF7x8sF7Ga8HR1GfyTDJXCbeDSRmqgPjzQXzNRIsFdRPRyjnJGCnngniXd6JYm1cqzQJfdm2aS5hKpoIXT0xLkAxQWqjBqB4FvUQ7Wq8I/l3Hxmibyqa1LWkSOf9bIk1656CwU=,iv:NF2WVIFc0WxHFSDcr4vsH+E3PmzMrtEpFZnRVSJ7oUI=,tag:LLe3wSUCX4V1/9HlOsqUZA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
