controllers:
  main:
    containers:
      main:
        image:
          tag: ENC[AES256_GCM,data:bkw9AsVU,iv:8BJdnyIEl7mTYnZtEKN8HE1lV1uH2wexhkIYjRCOkTA=,tag:fcLxuPHNlpQNtLw53Vip7w==,type:str]
        env:
          #ENC[AES256_GCM,data:xDQCh4bBzIm58zjS+/i4QrULNkShuex8hGF7,iv:Pfzkd14FMvCTkW03PbIRaVxTuwENDPY6Luw46c63GdM=,tag:+PXGJkum6Pnmnt5hjnsEpw==,type:comment]
          DB_HOSTNAME: ENC[AES256_GCM,data:5a/DwxrBn6l64W8Dlz4EFn0YCtZ30jTKQKi8yL592NrbgfFwvrg=,iv:tVUNfjEsbHEDQICux1yoGk3ZfgDg1t/UJl6aEkcd/Y0=,tag:2Zfx8PcvysLoce/vpBjH9g==,type:str]
          DB_PORT: ENC[AES256_GCM,data:F2uQ/g==,iv:MFtdX1LPyzMrAK6eZHsogwODN6E5lfxURQQ2mMayt4s=,tag:CpIFRfGlq1HxthJV/JQofg==,type:str]
          DB_USERNAME: ENC[AES256_GCM,data:lr3gAmwC,iv:EEocAYgkF6vBpYWHeRS8c9kNGQGGztPEHJ/W1rfdqTk=,tag:gnwg8Wnmt9LgUh/Y4FvxDQ==,type:str]
          DB_PASSWORD: ENC[AES256_GCM,data:+fS/ZWevfFtVP0pZoFK2Wg==,iv:v0HLMZ1JcELZk7dTBAvq+wSzQSvhaJ5pQe0kaE7yNYo=,tag:aqYkSTHosKSqbyyJxfCMIg==,type:str]
          DB_DATABASE_NAME: ENC[AES256_GCM,data:/VGJqzH4,iv:JW6beb1tlong6IZn8mzTJBHeSiyQepJVpYDWp9tZKB8=,tag:NsBE8Zp9pD5I2pjXMcRJlQ==,type:str]
          NODE_EXTRA_CA_CERTS: ENC[AES256_GCM,data:9DbMlCCBSJ7eUXVMjkgUki27qw1+1YgAS8H/arOsY679SA==,iv:eoH5SWDM1ZETzHVGy80lwtH6lUcBg1F4BBZ8AiSx7LU=,tag:/pRYoGcBPWJkOrvNbwawVw==,type:str]
immich:
  persistence:
    library:
      existingClaim: ENC[AES256_GCM,data:fTeTVREfso8Z2YuKnSk=,iv:IuFSWkQSu6gLW9BEBl/XDAXVIa/YHq7RZytE5UDyagE=,tag:g3qYEPcLFqAumlq1icLCIw==,type:str]
  configuration: {}
  configurationKind: ENC[AES256_GCM,data:XkC1g+8jmSGD,iv:95OqHkAs7LgfyQxa2Zj+2SsMwW+n2fxa16HASQt5lMM=,tag:JQWJWsvPO9Pzg9U3eNFuxQ==,type:str]
valkey:
  enabled: ENC[AES256_GCM,data:6SRfIg==,iv:9UyFs50k2vgYC05aS8j3knsqKmX1xcLboqXQVV4TeE4=,tag:cB7hz66ZkxWWcIARJcffDQ==,type:bool]
  persistence:
    data:
      enabled: ENC[AES256_GCM,data:1CujIw==,iv:lJibPLz5d7zGOjszzazRiVb0zQGsfTWH1gkUG4wTn0U=,tag:d8Ik+uNFRzwnPrZOKoKyiA==,type:bool]
      size: ENC[AES256_GCM,data:0izw,iv:xWWR4r0kAZE0nuhjW+e6JKP7VJBNxOpEPq6Kx99uHAs=,tag:GaexCPVkxHU9ZsTxac67dA==,type:str]
      type: ENC[AES256_GCM,data:USL11NHxm2rfuoD1vzwR1VCvsM64,iv:yLN1ignkPMd8L3bGjF68whRQ0Dx4723eTvH7hmmuJ4M=,tag:l91kwXyRa/gvhtZ/gnVP9w==,type:str]
      accessMode: ENC[AES256_GCM,data:pb4LQPFEgi23Mai40w==,iv:8N57l+mFRuLiJwdLgR9unS7PXAWCNQKC/0PGlrEhTxY=,tag:nqzTzR7pUEVSVBytRJcG5Q==,type:str]
      storageClass: ENC[AES256_GCM,data:H+0qSglJEQR1ebg60w5gCziB,iv:6G2HZs3fC1G9/+I575dEwln6zv7i9SUkkVANoY+2ySY=,tag:lJoJxPAQBNNgbLMZTPwL1Q==,type:str]
server:
  ingress:
    main:
      #ENC[AES256_GCM,data:cs8J6mxxbiIMg3tX17mVT+HOkuk7d42No1sgaDzWHKIf,iv:HMcPHdOxUW9TOJN4oWFg976W3BcQPYT823L/oCfbZqs=,tag:5D+xlpZ2+eDtjBk2puwQCA==,type:comment]
      enabled: ENC[AES256_GCM,data:FinhRJA=,iv:aJ0sZ2S4dK6KYvtlNEpFLRLeIP70Zg5T53eAxcl4Tjk=,tag:x88UPWCA4ASQ6zMdJy7gcQ==,type:bool]
machine-learning:
  enabled: ENC[AES256_GCM,data:PPml5w==,iv:ycsa5f8dLygLyrAcQbi9YQv1D3hMTE6HGu1kZI8kwps=,tag:Axpp61nbxx5haBh0T+YNcQ==,type:bool]
  persistence:
    cache:
      enabled: ENC[AES256_GCM,data:U3/NZQ==,iv:jGFRK1bPFYVz7dY1JORX+5r4dvHyhfia1bwp6R3sxF8=,tag:ZbQ8RcnS3vgLCjYQ2cTFfw==,type:bool]
      type: ENC[AES256_GCM,data:/BsCDodnnEIU1qBe7aJB/F5i1Gs8,iv:iTGmMY8ojAswe9okdsZWsPCC8KBm21BjqwBbf8WZnU0=,tag:r9lhOUqvGH5Xc0OjZTNSkw==,type:str]
      size: ENC[AES256_GCM,data:6+yA6w==,iv:Cap1/gaRwVQwTUsAtQcHCHc38Bx9pwAF7PaOTEGrDyw=,tag:mK13RWb7QfGx2LRpmPGSeg==,type:str]
      accessMode: ENC[AES256_GCM,data:m7fgAcHoeceO9u8ecQ==,iv:nszLXZFCJCKQr8mWTyerW+AGUkxBirWPkRKwp3A3HK0=,tag:qCKA2W6OCKknremutYrfoA==,type:str]
      storageClass: ENC[AES256_GCM,data:z3fkun27vZoU9iR14BGP8HKS,iv:kdawp9x7H3efZVrjMBnzTqd6saH2B0VRYTTCh/v2jnQ=,tag:C0yOQplafMO+3hVWvctIKg==,type:str]
#ENC[AES256_GCM,data:Kt1x4G+0aJwqGGmJ0rDFycdJadqOdJMilw==,iv:1SLEXJS/CmZJCYDr+FQc7V4bP4k68GBpSD3o6aSYyyE=,tag:MSsauTHSzQSaiyEmDWcRxA==,type:comment]
persistence:
  internal-step-root:
    enabled: ENC[AES256_GCM,data:FL1l1Q==,iv:Pppqb6KtzvSzvSLYRUn8BlccZdjU0XCnjcYI68+6yS0=,tag:iQ0XAGGUn7TePyJOtq/a7Q==,type:bool]
    type: ENC[AES256_GCM,data:RrSwr8zzIN4A,iv:8kC/SBdkplIfGifAQsW533oLSueZBgNi93AVz+Nyd+E=,tag:FBh//yNj7NSboHMHJwX00Q==,type:str]
    name: ENC[AES256_GCM,data:QCQrl082WcVD5n3+ftt6Tswd,iv:rMI0vnxXyiI0LjfrUNNTM9xuB/Jo/8q1PPRwZF41ovM=,tag:FvOTGF8np5JbSJCeWHsNCA==,type:str]
    globalMounts:
      - path: ENC[AES256_GCM,data:ji7JDO8bSI2pIHp7xdU=,iv:oSfc6HYSTnJei6n8s2H6Bb4qcxvg+NZEcv+zCzPJon0=,tag:7/yx8YCCkwvz2A/U4dKQ0g==,type:str]
        readOnly: ENC[AES256_GCM,data:X4P8jQ==,iv:0ctRauPA4WE0pnjoR8tupZOF6CuEyDyZNsRkokyTjrQ=,tag:DvaGMGWGn8kj9y8fBFmtag==,type:bool]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbkJyM01wVmw1eFBKRXdY
        ZUM3UXpxNW5sakZ4Vk1KcTU4QjdYSGZsK1hvCnNjeEtsb1RNdVc2dVRiMVpLQUM3
        UkgrWkZZcmJmRHRwZGZLL2tsRFFmNFkKLS0tIGcvRHhRb3VqeEtYL25yN3MvcGNX
        TTZ1QlE3SU9MdWRoUUJHZWZyVDFGU3cKtAhnVzg6rKuwhdeF25iaIhjos2YpnH+G
        F3uw/A/km9kwCnrJwfnPyAv1C5UWt4HMzCBUskr5/3P6F8xxr8J2cQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T22:19:51Z"
  mac: ENC[AES256_GCM,data:6Y4FlXw3bSsI6/svjMJev3sHvI6uCO8mslssx87uEray2YgN6z+szo9pV3EV4BXykSNEev/2+UShX5ILWPKhQWKgZHBTaOXwAZ292WU9TeVUi41XB2Nj6fd/+BFYLQsrMkBP0JDcC6VYnv1jOP1+YhnTbKuoUb7wMJhh9C/GGPw=,iv:wwUwls508PvFsqZYV/3QKhzPabZQXDcvLJui/lFnTfY=,tag:FiOXKPky9l37bsvucCPMeg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
