controllers:
  main:
    containers:
      main:
        image:
          tag: ENC[AES256_GCM,data:gAheB8/H,iv:kRAVUt3lqec1YxVCqcXjYJDxgfYM/aq8Foc7WyJCZTM=,tag:pCRhlItjXnULnsQF+yEZGA==,type:str]
        env:
          #ENC[AES256_GCM,data:fdtaua3mhvpAejlB4T1hjE3hrjSgS6IxC476,iv:iD3GzSetbPh+7ewhx2JTZRDU5NR+Jbxw09fljnT12so=,tag:k+6Nb84qgPw0oPY4I9hNtA==,type:comment]
          DB_HOSTNAME: ENC[AES256_GCM,data:HDoXqsKjCUjDNhNteoHfrpu0VdBmK16+h2aW9ftP7Wr+Db4cWNw=,iv:F6W6krdFcaDbp91+4kRHZLo+GekMScU/4Zc/uRJUPls=,tag:uVrPPL5enDOQS8O0s0ISRg==,type:str]
          DB_PORT: ENC[AES256_GCM,data:/Qj9cA==,iv:gtrSGGVZVKnAjTOtXnjXBAYY7yPJrKrU3Og0jLa8R40=,tag:8gKJttboEon6rRbZCDZzPw==,type:str]
          DB_USERNAME: ENC[AES256_GCM,data:H8p6Uw/z,iv:19JSIiIhc2QM2bp8non/CFHrbuLDmX+bAdQ8U6LNR1o=,tag:zrPXmyYsRpBEzIDwKmoDuA==,type:str]
          DB_PASSWORD: ENC[AES256_GCM,data:/3JynyYUHWGwVQBtFxjw8w==,iv:lwUtlM1i0ReDwk0jILm/9KsNmMoUsm/vy03jtjPvaDQ=,tag:to4/vI4ur0S4hivJ+YYxIQ==,type:str]
          DB_DATABASE_NAME: ENC[AES256_GCM,data:bE+HGGDQ,iv:SAkBx2kVcTPExCxEY/GigQCuXi/0HfB2xBMRyuKAT/0=,tag:/jFXXsNFLGb5RQUeATUPFQ==,type:str]
          NODE_EXTRA_CA_CERTS: ENC[AES256_GCM,data:2nAgjTgbO3Nlb7fCCVDiIurgceuh7k25jAM2bFuJyLMU+w==,iv:KboD63euIHZBlVWk0KOfeICxXyDCtSjgjqGWBy3TNZE=,tag:Vv8ZmuxPh5iKFipqxSolOQ==,type:str]
immich:
  persistence:
    library:
      existingClaim: ENC[AES256_GCM,data:72TcwQJWkZTfFJ3BFgs=,iv:LxxuyGDMaRAWKKvcEw6UwMf8pvWG+zjykRCMD9zZn7k=,tag:s2Z5/+NyNxADJaWcIaBDnA==,type:str]
  configuration: {}
  configurationKind: ENC[AES256_GCM,data:g7+TgaZCPee3,iv:ukdtVxsz7rKYY5BRF07KkUMvvGFtutWgpHZDES4yEp8=,tag:VwhbsSWxPBy6NepK8V920w==,type:str]
valkey:
  enabled: ENC[AES256_GCM,data:Ugl5GQ==,iv:4v6JtCQPNksNFDZdxI6fKk0nrBsoLodNhSV4n4+hz7Y=,tag:d8HPgpBIFXRwSNjke3epoQ==,type:bool]
  persistence:
    data:
      enabled: ENC[AES256_GCM,data:NmXu6g==,iv:eDKrOk4l7fhM9++bwDe4lUEThME9lZKCTWQzmXFrTLU=,tag:Ku9cGqHxHMxsgxs85cV8XQ==,type:bool]
      size: ENC[AES256_GCM,data:4LCv,iv:EX+nNhZkCpgiO5teT1Chw85s6R+VJ5ieCE+pykT3MMo=,tag:SLaGNBi/Sd2VJZK7j3Ko1g==,type:str]
      type: ENC[AES256_GCM,data:/LDK3oU5SXA4I2oavS5Zl53Fzack,iv:2KNZYxznj4UavklcGnf17PQtZD76xhy2MYn2dYfVNeo=,tag:hEYg3NXyBSvWweYxs4kdLw==,type:str]
      accessMode: ENC[AES256_GCM,data:k3tV7BK9bV+ZR3YjFg==,iv:ABzzNQXB6fQU1MXyd6ApfwgR3L3TstV3XqfbIYjEV7c=,tag:rANTwIy9Mz5YOxtdWdhtww==,type:str]
      storageClass: ENC[AES256_GCM,data:q86ULcUKUEAud15qW/hktvXT,iv:V1wOh9Wt6qpvsYiVLSrwCOkC+XjIQSpq6YMBj00obqY=,tag:YF2pLRp0JBpQKoHC3lW3Og==,type:str]
server:
  ingress:
    main:
      #ENC[AES256_GCM,data:uRj0J4MYbA6TVj2b3iRM9c5qNVRxc2ZUKtYhmYmfCNvD,iv:hep0x1TbcGhFYP75mi77E9ZoSy/MMpn/Kq1Sm3A5wiA=,tag:LyAdib75abI4H9VYAni3uA==,type:comment]
      enabled: ENC[AES256_GCM,data:JU9YM1E=,iv:Aamt//4kbv7Xf2/yP4TBTCP1rnlAu+tryJvvGkJj0jw=,tag:QQcfSR9JCeX3HlqslE4Oaw==,type:bool]
machine-learning:
  enabled: ENC[AES256_GCM,data:WICiQg==,iv:VDSm/9NLxUx2s/hwgW3xOYULrEzbXPpDG3janyLhrEg=,tag:Qt/6ANiGrYDJqGevilCBUw==,type:bool]
  persistence:
    cache:
      enabled: ENC[AES256_GCM,data:A19Bbw==,iv:Uj71cxpMIgUXc+cFeO6f/FPegMysdlNB/4/peHqGBzY=,tag:5H7QX4tZeePab4AtqCprKg==,type:bool]
      type: ENC[AES256_GCM,data:Vo/DCclft9TsSTaHcCdFyn4R9Tdp,iv:cg9SDxxdElfxQzx1CwRpI8JCf1kW3peTkr/f6NmZvjk=,tag:5I1WvW5+60QQnwXsPD4kJw==,type:str]
      size: ENC[AES256_GCM,data:iZ2Sww==,iv:UvAf3PYRjMlPWuNtW3IHvFIQ8rOjm4cstDf+TATP7no=,tag:S3aJHq+Y/7cnc7CrNtLY/A==,type:str]
      accessMode: ENC[AES256_GCM,data:ZHqvQhl6Ln5raeQM4A==,iv:zDicP4Av5xk1WHzIx4QD5ixZQMyg8TW+pat0GBnFzsg=,tag:YrcLkUNXaurpAWHiv2Pfjw==,type:str]
      storageClass: ENC[AES256_GCM,data:0U5STHXOCHoBdokXAtH6u5di,iv:OWgC/O4aZqaRMbSlwRuK1SoQPbrH6Jo4QAMPXkMt5so=,tag:rJIBYI8sbErjWn4VLYR6xw==,type:str]
#ENC[AES256_GCM,data:hy5mp+rkgvA/sXo6x0dzwd4lpv4jpTrPBA==,iv:QHJSCuVTmwYCm4rcGKzPuPaSJvrFTop7KIXiHFVKlLI=,tag:GiL5TFKUV7DCTpN4BUEs8g==,type:comment]
persistence:
  internal-step-root:
    enabled: ENC[AES256_GCM,data:H6H2KQ==,iv:smeDXc5jz19ScPYjxymh5UobM54jWLqZAYND5xiEayo=,tag:nMcN8+Bdu5IgvFzrU/sRrw==,type:bool]
    type: ENC[AES256_GCM,data:kKCt4cv/cqgm,iv:VlF4bSMujmGEoyl4gclNdF0gacPSvCIlQgW2vE3xJZA=,tag:2tg82zSYGw0CrQjDETFM5g==,type:str]
    name: ENC[AES256_GCM,data:692Njd56CPx9i6CqPJbGIOY5,iv:k090qgjw+V/iKdFccy3gEWU6D+M6yVhuwJlqYOiUOJs=,tag:ZBpVOj0/92mxSQVnYdTL3g==,type:str]
    globalMounts:
      - path: ENC[AES256_GCM,data:7F2mystBX51A1vulg3c=,iv:KXsblOMSHW8GjVnDo/+pAc2WtB8HInmqs42EawKWT9w=,tag:PjZJKlsJ46lnZQUVBVJX1Q==,type:str]
        readOnly: ENC[AES256_GCM,data:6daF7Q==,iv:sM2ZP8AUqVMn3C9AbqI3k753EFj7WrhdZz43Q5EdkBU=,tag:Qp0D8YuV9ByszyURwG4T8g==,type:bool]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ3dzRTlCeDhTdkJPMlA3
        Y1hMVnQybi9qQURaa2hiQ2llWWxMalp2M3g0CkNPbWhNYkhDV2NEV3BtcGVVUHor
        dzlWblhvTjlPcmhFRnFsS2xHLzFXUUUKLS0tIDVKdDl5dGh4LzhkQkhMNEVYQnVN
        WXlmZkk4S05NcXBEcjV6SE9GanFNU2cK5/x2dg+Syv0HM9bbkdSa/4b1RAUezPl9
        fFYXJ7pYHLf43nJ2QSYUQsecenxrwyA8dPI3oKbjntI4d6Vk6kcjZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T22:03:06Z"
  mac: ENC[AES256_GCM,data:/qaKDUWhk3ROqbppj5bHentWNBbYsGgPBvJqaPSzAm0H2vbIn1YidubHsPoqyJVgUVOcb+BrEYtPOec4tk664enbRutTtT96dxtCzrJQNW44c77ODQ9y4YmUIRlM0HEPnOs91bBgkzHJ71edR31cJujajcXAY7KijF6RMMkj40k=,iv:ExwC/Cy7/0WdbN3WCgv7Zt/+CKgH0Nraao1NpkqWkfk=,tag:yOZfhJj/PtSHBQrvm7rbeQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
