apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: truenas-iscsi
resources:
  - helmrelease.yaml

configMapGenerator:
  - name: truenas-iscsi-values
    files:
      - values.yaml
