csiDriver:
    name: ENC[AES256_GCM,data:FCtJXttor3vTootpXLiqj+9z,iv:X3JaYqojp/IyQqTXv683Hgoore9iOCe8qOJ6NAoQQ3Q=,tag:pXWMmWL86TDypPuRDuEAww==,type:str]
storageClasses:
    - name: ENC[AES256_GCM,data:YqQ81ahKD36kN3q1UPBGEif+,iv:UqlLhE+p8uyIg+gX5GEY+TVDP2oead91fdmGPQ7RoJ4=,tag:o/IthroVGLv2KXrItRYW5w==,type:str]
      defaultClass: ENC[AES256_GCM,data:LJaf8Bk=,iv:Oxo4bZpMK6vGVEJHXO4KPncP8Wyv6cJYIEHfJk+Vlgw=,tag:s36GcCStMzD1Rs/g9fH68g==,type:bool]
      reclaimPolicy: ENC[AES256_GCM,data:1fMV4Gl/,iv:iXGhQvuhu04jP5LHdVt+awf/6WcuKVE9XNoCAAhUGlc=,tag:IPupI+cqbvcvaBS4Yv5Q7w==,type:str]
      volumeBindingMode: ENC[AES256_GCM,data:C7t/BlaOW9gJYSj7uQiQcokbIsg=,iv:ne2jg9IJJJg5HzOYWg1/Lq6qzgznEk1wfj7CTJmZAjk=,tag:oobPrP1JtkAhWNGnnDEzgg==,type:str]
      allowVolumeExpansion: ENC[AES256_GCM,data:Pml5hw==,iv:wfibJ/jtzIpt7mlZE8NGXy4WXrWQZMKA0gzF+XfZlBM=,tag:LdfY15FGo+CFc5GmAkLvQA==,type:bool]
      parameters:
        fsType: ENC[AES256_GCM,data:TW9I8A==,iv:IVnqtXKoBZfUOknIvqgCXeVRzZhBq5CB6iY14CGYzoo=,tag:thbIoIMr7dxQLTFUKycPzQ==,type:str]
driver:
    config:
        driver: ENC[AES256_GCM,data:x458zy3pVP/3Mt2S4/cJnsc=,iv:ZWAuAzyYMFwnyiLIapPBoQxIT4HCrt/3JRXbv/baixQ=,tag:0HQvNWSRQkIy5S8D/MUTwg==,type:str]
        instance_id: ENC[AES256_GCM,data:tz3QOe/cYlKutpsz7Q==,iv:kaE2aJGev5bWLjPaFPJMz6JzvfvgKT7w1EgO9lP56+E=,tag:eWQ5zg3Y9Urp4Dj2RdFo0w==,type:str]
        httpConnection:
            protocol: ENC[AES256_GCM,data:Pt36ZQ==,iv:RmbksO25RXeG1OrzFNvZO+hPf58Nrp8ZV23GWRPFUiU=,tag:3nsf98hab+ayHWgQ/oaIDw==,type:str]
            host: ENC[AES256_GCM,data:CHLLL9gLJOqPdd2R0ZMnQe4Vitp+Oh+MIg==,iv:G5x9ZLDAa+6abLNfKE2ii+VvNarAQV0mj4/VkfM1u/0=,tag:KxKb8eIt8ySfj95Nxz/YqA==,type:str]
            port: ENC[AES256_GCM,data:SAw=,iv:VTq+smaWf6LSJsRIsExL8/3wEjTgNpLvWVqsxJ4xdyQ=,tag:NDti6gA44IR6x4AQCxLgjA==,type:int]
            allowInsecure: ENC[AES256_GCM,data:8RQbpw==,iv:un4je3lwHUNQCZp40x8kSmD8bFDa2NgcOiNE+yqzb6o=,tag:9bIZ6seENTq8T1ZCY9wxmA==,type:bool]
            apiKey: ENC[AES256_GCM,data:zhuv1H5lHUkFFvgHJhZNI0ft0lUQx4L7LF93j0VC1qjLj0xhgk7OWXdgyrbgZR73FQfJELo3Fw1G0sjWnTzSgZzi,iv:u2WKYrW0ZXZYNyuzMTlCsyfvAbVkhB1S0P4IpTEfl10=,tag:/+LKFBC+4jYJTuRlh4qZ2Q==,type:str]
        zfs:
            datasetParentName: ENC[AES256_GCM,data:GhSShahx7xpnuVt2XHw=,iv:PZqkK16QsXIc98CUigzYz2jdLXjd9hoFCSE7uNCOSJw=,tag:XPoSEWJr/Nwp6HcU/76Hgw==,type:str]
            detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:8tOqsH7WeyWk1D/eYI279LzS3KqJKZdk,iv:bYRPiC19qA1obOrUEvG/n8wcUgeUCAAQkLD4cTUqnnc=,tag:wX/oEmfditmvwNjpR33yoQ==,type:str]
            zvolEnableReservation: ENC[AES256_GCM,data:G8DnvFI=,iv:BZkb4OSqzIp7FxZd9/KSgHQhSj7UsndhTgP13IIs8uo=,tag:x7/zhOKfhURDjsId0CUbVA==,type:bool]
            zvolBlocksize: ENC[AES256_GCM,data:L9Y0,iv:X4sCFFZxdsue8NpvThGyaV14s+8DzCrt/f+R05X57Jo=,tag:ocFQBENk6db1acgYGBZYpQ==,type:str]
        iscsi:
            targetPortal: ENC[AES256_GCM,data:+Iakli1QG/wNNFhVdvgmst/+0xpyuNNrMcsQcjYt,iv:dWMaPUkrL/pA44+1nzap79uwB13H4K79dM2eNajyXLs=,tag:0cpg7jsqT3YfINNGM7WbXQ==,type:str]
            namePrefix: ENC[AES256_GCM,data:fRqK9w==,iv:T0kxxmD4iSo6/9ndGF1YGukQghU5NkurGIGbyzuDz3k=,tag:/7Y6+MGEtF27z03uCQtHnQ==,type:str]
            targetGroups:
                - targetGroupPortalGroup: ENC[AES256_GCM,data:Fg==,iv:ZifZBm8WxkD9jDBVpDIH9niJNTBpPPukcMk+BSPfVlM=,tag:/qPaukNdRpltzJwBQAu9iA==,type:int]
                  targetGroupInitiatorGroup: ENC[AES256_GCM,data:MA==,iv:FxVu1DT1sX0Xki399ZRe35FTfBMTvhCe1FFOD8xM6wY=,tag:wQNvz9ObQLlqLrOrT1Sxgg==,type:int]
                  targetGroupAuthType: ENC[AES256_GCM,data:erRnDQ==,iv:ivBzMVNCtcJ6C4aMNFovoFuLIgCluuU8sdPgxCx+d/g=,tag:BhzgE3RM0OJvKyJ8UZX4XQ==,type:str]
            extentInsecureTpc: ENC[AES256_GCM,data:3638ig==,iv:QbTKKMUZdKeOs/wEkCBqJnALbsoUUpamKBRDWxqK+SE=,tag:ysz5lTm7UFqvlMPOpNZ/Sg==,type:bool]
            extentDisablePhysicalBlocksize: ENC[AES256_GCM,data:G3k4bg==,iv:keuPHiXsBEBog1ILBPW5N/rHnPQt8nXwa7vBkp5DHNk=,tag:e3fYcF2H7CfA8gaQkj033A==,type:bool]
            extentBlocksize: ENC[AES256_GCM,data:LmwP,iv:GcBg+5onYgtscdMUqKV0zO1Eimb/reVaYDTHvVBEXpo=,tag:ooZMr7EmVYPgUhP1G71s3g==,type:int]
            extentRpm: ENC[AES256_GCM,data:M7oB,iv:5zR+rbO5awNO6KouXWCUjDGGFqJcWmPJKOu5DY2lYc8=,tag:UGFPSb3ixS9ywDXX8pIedQ==,type:str]
sops:
    age:
        - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdkZHU3E1QzZ5NlJRZHNq
            TUFjdk44eS8vWFIwRGxDUmY4ZDIyMCtGK2hzCjBMVEFLSm5VRlVGem5GRmtNMmVI
            cituNVVOVkdtMDZjM3VhLzMxMkRKSGcKLS0tIEpGR3JQWnFhVDJmbENueDlLM1NU
            NmsxcFFjNGV5eG5GeVNsR1p4MHk1ZDAKWn3/oZhVgPH8kOrxOUQHWLTUjbu37aRB
            Xqr6SmMS/HdySi6914+IZUg1eSlgITx65ch4iihptppHcqp7Rubp/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T10:20:58Z"
    mac: ENC[AES256_GCM,data:3lirfttCrHc3JXe0bxvhAXsJJJBaM+9I3CbCAJui0dInoa5/vZf2GRfH3Tqp+Op7IjCmM3YE/PeG/xfpS0C0uaf2EM09BQgZRU4zrtHRWEQLWhMXPAJuoIv8BOK4O+njxMgKMzo+cDKRBQI5E8JtPgHCdmzvWcWv2bFpCNAtm8E=,iv:1EGhhmVYJug8IcOAcNvZ4YWxZcxMR9S2zJywCBZwn8o=,tag:gHLijXnYNOScOn8XMddxNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
