extraCaCerts: ENC[AES256_GCM,data:YRw49hz77Q19A+g3gm8nmVJwxb8BfYi8D1R2she7ZXhLteoLTrnZGqGc5gvoPrt5FIIgY3id1p5nC8xu59ZfypPPxwxmxOv3FSdxhMpzkXjPVjdiFvoTog2Y7FfxVIu2Xdhx6Y9xlh8zgyLBnn9KJjzk3WkcPnOPbWubieJ0fPyUCErMERny83MzhVWpTBMB6fKRf5220gA0UZA19JNx2OmyXE86bIrC8NFTBnEsgSL2+ahm7tNpXoyCvUQPwlgrKgoQ+Bqt2bUpSMCK2/d6MkwMO9VqCpKpSPmWL/fiB8o6M6B2xWkKp9RBakJA5tpjbkmYvujLpzmTDl4fVFN/XauntVWq7fGq3QrY1ApWujXpwgo8qTW9TTex63//hidEz/7OASQfcY+Qutds/sGUhvNr8z9EZFcekckIb+fhplgfOV2mcu43HwMCyKdf+fMK2QYYe0mBZZMrsU5mJdRoWoSXzDwITk2X1KFwcx7h5oyexApjk8dnnWBojaMlKxCAvFEaPMVHxpP7hioEbR6QaEj3LFbss5Yo1o+1oOlNUzciwaVvpNn7H3BZW8jArnpPvS/iqacttt3drJxRN5SvHJtOApiyfb0wyNEKBsBES8E5eOGP8olTZXDe2aNG+SHuT/HHSWUhqBOnQZ2PEVzPJ3q9jms76zJBlbNgWyqIwnc6MaG88l41SS3HxEjdul2V5Bi6Y1uMH49wdl9RHMXsP6IkgjZ0smRDzga2srFA9fYQVhB22ckvYHhdcRw5,iv:0apJoPLj8X+JWYsrECDMqAK26rPZHR6PVeGku6eju2Y=,tag:vWnNe0cDlUtEuI92OmTvLg==,type:str]
csiDriver:
  name: ENC[AES256_GCM,data:1/qU29nFruiXx/9cD6u5Ug5U,iv:+J8vntC3vR8WbpnIpBkryxyYdxH/fWfeFh0SNbkwCGo=,tag:TNiNO6iIRgYhgVNFD5zi1g==,type:str]
storageClasses:
  - name: ENC[AES256_GCM,data:zVluFWg5yUBw/7VPN7PKKfCY,iv:Ja8/GnV2XSTx+IrFBDBvLQbSkVepvSJkylnABJHjZeg=,tag:FzKv2O16NvTVD52qN3t9Iw==,type:str]
    defaultClass: ENC[AES256_GCM,data:XwIG0Es=,iv:BpjqWTBrZXwpur1mN9Yl2oV3b9/RwH6jlNxnZrL6oNA=,tag:ZvQ/Y83gm31yy6xmlDgnWQ==,type:bool]
    reclaimPolicy: ENC[AES256_GCM,data:A8T9TAnn,iv:GFOEeX1Cx9YAVByyjYVY2YFNjMxnCE4TZRtTWeXKqiQ=,tag:fqsNikGYcMUQWSakcBua7A==,type:str]
    volumeBindingMode: ENC[AES256_GCM,data:2ISnuTqtIAa8FEZhU7R7d8XU5Ig=,iv:Nahuf1hLNUcEe3cFlZ5H8hR5La579m7In8d5M9PQU58=,tag:RaZMp9DFl+/4HQO/j7xvlA==,type:str]
    allowVolumeExpansion: ENC[AES256_GCM,data:U0cOfQ==,iv:FerPi6p7mfpS5oVZw6oi+znSOebkt7J3OlEJN78vET0=,tag:h7SX47EWrGoaU75ViMeGbA==,type:bool]
    parameters:
      fsType: ENC[AES256_GCM,data:nY8x6g==,iv:FS3LP2XiqInKoTNSvNpdJO1oZycKKapgATwunKyfSs4=,tag:0i9xfaKbeESU0LBcvEWOxg==,type:str]
driver:
  config:
    driver: ENC[AES256_GCM,data:gQm80YnK4bxfrVt8f3ElT48=,iv:FkfhjTcuaPNinTKqk/y5JfMWwhd3ZeoM7fGP+uAKRjY=,tag:IVfZTtywNGDDEx7Ou8c+Nw==,type:str]
    instance_id: ENC[AES256_GCM,data:L9ln0HSNQlqzluI/eQ==,iv:z0yAiBP2TaYh/ZWcpdFhOSnV1ZYdZefu4EUhA3cdMAk=,tag:n9yqjbjFTKs1bsp3a5mnaA==,type:str]
    httpConnection:
      protocol: ENC[AES256_GCM,data:ydQigGA=,iv:g/Ahsu2HhH2UxC2+Acw91Ut+o8PMlHBELLeGOF1cBTA=,tag:Xnai1PkvCj11emy2veUijw==,type:str]
      host: ENC[AES256_GCM,data:c4ONT7FAQDmgWkvusM37eXgJNPCmFveQtw==,iv:fMl5de3q6eRTh9hlbAHUz7OvSSOvoBJFNmMGPktMI9g=,tag:T4zL8rQ3Opp3paS5FIPufQ==,type:str]
      port: ENC[AES256_GCM,data:YFBH,iv:6f4VAg9VGiRGlxSEQggmX/CqwSfpg4PoiFpjwn7DJWI=,tag:oKpksVvXEFspwqSTwg44hQ==,type:int]
      apiKey: ENC[AES256_GCM,data:satoxFs/v3X0HLQ6FP36+KIkcBEXvM7ghH4GPSPI5lu75qzQ9uI24Wl5ItCM4xOeZ2OUmFarqkKoe9lZs42bGbGt,iv:DYCyiqLx6V3txWNcL967nLs+DY/E5wgzI6Gcqfg861U=,tag:QSkzI8BEBmySLmINVgqNJw==,type:str]
    zfs:
      datasetParentName: ENC[AES256_GCM,data:LdhzCtt73iihJ2Ll0+Y=,iv:FZY2Yk0bxGgGJWD7vd/9bCEAZ9mrNkFxHhiigjAX2Sc=,tag:3vHAlpwcp5G2Bcg/Knle9Q==,type:str]
      detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:wdibAi93z7xL+DWTuGq8oUTVJ5DsiXFz,iv:MgscGQEi36GCAb1U6nZCUWFgnaE/aabvdRDM8jHGfKU=,tag:XRMolIEt8fb4sw7dLdkWGg==,type:str]
      zvolEnableReservation: ENC[AES256_GCM,data:RptLHLQ=,iv:iI9ASUKh+rKOkqIemlDzlMxb5WLuNf/lrucRafcUbzc=,tag:vZme2MPDh9GCrKN1cWwZyA==,type:bool]
      zvolBlocksize: ENC[AES256_GCM,data:ddNo,iv:U8Il40iyo4lA3uy0YdWEXPUlkU0QzXLLqAt1mGaYMSA=,tag:xUS6Wiu8hIr9woedf8JXSg==,type:str]
    iscsi:
      targetPortal: ENC[AES256_GCM,data:E+j8lud65c4Bu9etL0jNJqhlrcSp72Fbdev7Q6Xs,iv:XIhS54DjFEomv54QIVW3IDwHMGqTKGZoTMwEK0tg30w=,tag:/u4iuQdC+C0vAxWZE7iExQ==,type:str]
      namePrefix: ENC[AES256_GCM,data:8P0yKA==,iv:hL6eVRGzS5BFug34Qcn0Z5LI5qH9MmHiDzVSmolTzwA=,tag:6/6PgreLZtHgXf4w8XNshw==,type:str]
      targetGroups:
        - targetGroupPortalGroup: ENC[AES256_GCM,data:og==,iv:JrK7WTicLEX6i5/lFD/ITaCVaNS9uuBF+TAOPr9aKKY=,tag:4U2ipKB96W4WE3mRJ1jgpg==,type:int]
          targetGroupInitiatorGroup: ENC[AES256_GCM,data:gg==,iv:c2I+/ezUq9AmLozPqCql2Y36eFsyO3qGK+UNuBpo2TY=,tag:VcK9Z4Z2SiOgFwJ+ewMg6g==,type:int]
          targetGroupAuthType: ENC[AES256_GCM,data:TZRQbQ==,iv:zcFz+0T8dPQvRzzXe8n6q9FHawGvUg+DZap+DK4fBK0=,tag:0G/bLtw7fKXZAeeXdHZzXQ==,type:str]
      extentInsecureTpc: ENC[AES256_GCM,data:PrkYFw==,iv:OEBaAv25oZYKRkV+axzeqqd66ZWU/XEva6GiTOLQ90s=,tag:f+s3TfY4EXZXPkT57ef+0Q==,type:bool]
      extentDisablePhysicalBlocksize: ENC[AES256_GCM,data:swbOTA==,iv:vBOyyIDgvi5NhV2OqQAjJsVuRujCo+iJ4Hc7fVuOi9I=,tag:po82wTA8gu0K5U8CDuUHrw==,type:bool]
      extentBlocksize: ENC[AES256_GCM,data:xdtR,iv:hT1Humo0QVsnAie5Rt5YVEkJVta0orpa5DKrQOcaArw=,tag:6uRUaBswVNyTNlTUt7hCzA==,type:int]
      extentRpm: ENC[AES256_GCM,data:MpTf,iv:QHCXmlUIGTZ9/+Y1C89bJkfCvGzqmQ6zKpfYNIVgEVc=,tag:6TP+hXtJ7/CEN5xDV89dyA==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzL2ozUWV0MHhyc1dCcVpI
        VHVwb042VnJsY1hJSytnUS9YaFJhWnBsa1EwCmZzUmxrbG0vQUwzNDBXb1d2eVJP
        YjFvUGM4SUQzTnBhV2Q3Yk1CWG0vL00KLS0tIG9aS3hMLytRNFR1bUFoaUNKb25L
        bUNlWXRRRDZ2ci80YUZST3ZNRzRleFUKw2QeSgWR0v8homK9SE68XwYXVtoDHrht
        TAke6Ow7yNi5qZm7QWqCQi+nf3roMLSte3l3oVW90ZRiXuvlJjTe+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T10:46:28Z"
  mac: ENC[AES256_GCM,data:aNcs7QWDzAa6vONTZttkyZZ8/wX21lkIDiR2PoeP89N7YGbhljnB+jyE1pkCDDUpWx7d5+Q+FK4EUIJ632j3LrbkT996QX6p+KWPuvmh4HVMkrjiqZ8SDWrZpY/StElfCQ3zcaM2qSqwk+ORMNC3jdNmkGF/wsI9t69mZTsnG/c=,iv:jIe9OV/ykKnRqxtG/O3d4VCb/RmL6pIyIkjVjCLvnMA=,tag:F6SyiFpvQwFQ87egknxubg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
