csiDriver:
    name: ENC[AES256_GCM,data:qRWCFVecXm2JfdBKtkLlpe0c,iv:9fV1tcpGIHGDA5ZvP4OETf1tmSfDwtV5lVD89cJ3V94=,tag:v71t6ZR0Z8/ujyAuiJJliw==,type:str]
storageClasses:
    - name: ENC[AES256_GCM,data:40BYUdUc4KmyqVGuCOMHyNtV,iv:goeTM9wOIkbt/GfsVXkvO3xAc6drB/up8oe6UueufWY=,tag:glRB/7uJ5yFqQLc45b0SoQ==,type:str]
      defaultClass: ENC[AES256_GCM,data:xEnffRA=,iv:YTEas57HMT0nXpzrbvmIumw4JY70UsWRyRCm7v8R04w=,tag:3twV0br/eIvd/ymc0ih/CQ==,type:bool]
      reclaimPolicy: ENC[AES256_GCM,data:73lBAJiq,iv:N2ZScE1a1bany0tmxxRtRZ10/UDkxDBUiZDEx/BJECE=,tag:4tHiVWdy17LLz8n5UsXBeA==,type:str]
      volumeBindingMode: ENC[AES256_GCM,data:t0MbSFLlOZqKqVHaPtqvQGOeTvk=,iv:BUjytawT+lmueNx4fJLm7B9jN5fQpOfgdDj9kVTPqCU=,tag:DnKwsuItS/vxYVUZ68yefA==,type:str]
      allowVolumeExpansion: ENC[AES256_GCM,data:nYmH7w==,iv:tFO0L6tMn43K0AT/L5/e7IlQeN1rxih8sRFHcRPtzjU=,tag:TtLBKo/jiml/cM17pXqU7A==,type:bool]
      parameters:
        fsType: ENC[AES256_GCM,data:yekhxg==,iv:zGm7G/keu/thZcKoqON6Hijm+c9jy/x6ucjLAOpM3Hc=,tag:Lv5jVSLA/TgLFb0bsIpPNg==,type:str]
driver:
    config:
        driver: ENC[AES256_GCM,data:vMx0D+FqTug3v3LvoJgiF50=,iv:uf1w8c/FUByIbk3+fTa51TgYhpILNt/8u/XypTAijYk=,tag:RJ5WmqAPIivTPF02k7hxBw==,type:str]
        instance_id: ENC[AES256_GCM,data:hISq7OwL1Ng1n6b8gA==,iv:T5cz11YKDF/9MvV/t1/nZuWlrtGm5TSpJWFRf9IaPtE=,tag:sF0EFPWi0jpvBYTPXL/9Cw==,type:str]
        httpConnection:
            protocol: ENC[AES256_GCM,data:RXC43g==,iv:jCm/LrgluPNochgdjekomFl9+g8cZWPvn41a14FTNJI=,tag:09A+iCBV3HuWVpZDWgMHGg==,type:str]
            host: ENC[AES256_GCM,data:mh/7jEU8IFqolYbUA6uogiBSR0zolvpQsQ==,iv:iuBrcNI7QGzdsdP0TIBXbF3BMQ0mFzIepXIDgbF/JOI=,tag:bb6cyXqm/NmVpEWI7beGvw==,type:str]
            port: ENC[AES256_GCM,data:E0g=,iv:CxSkH3FPnwpEWxzPOStR1cXsxodRzYh+uSP+Yg1VRto=,tag:kQX5ygiy2s1ZLX8F2Klv5Q==,type:int]
            allowInsecure: ENC[AES256_GCM,data:55uynw==,iv:6DhYq1n8OaSgmdZTkoMNfjB1Bm1gZboCA7GAGDLpK74=,tag:tg+aAuHGqUrmBgtWOoU8Yw==,type:bool]
            apiKey: ENC[AES256_GCM,data:lQhPCW79ZBiSZUSaWs4E0UjAwZE710fFMnDp+sSTGWDzJlL72RnqfO3ubdXU4K3xHJFdW2zXLpcRybGKchzyETqX,iv:QlZdJ8d2Grn+mLoZbwu1RMeiQOAHW9q1cViS/DsA0cg=,tag:xxjkS+Rtoio9X0dxN3n+JQ==,type:str]
        zfs:
            datasetParentName: ENC[AES256_GCM,data:xIYuPD97mv5CYRQcPgU=,iv:sbml+9tXOPgddCO2Oh31S+VPcp9Ji85sz5aRHAOCyw0=,tag:Tpw6chyqyxTR5Z8TUV4PTg==,type:str]
            detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:cMGy32WghOcdvP0Y4KaQ1xd14QK4ICMS,iv:+nvi0sAV3vJBJF7zWAUTivyQsoxGMhrYrrnNxUbeYEY=,tag:A6ev5+J2bUDPvQPyOItl7A==,type:str]
            zvolEnableReservation: ENC[AES256_GCM,data:iBlEdKw=,iv:N76HtA198q+H9LF1WEhdOo2HFGCXgecw2e3C1SdaDYw=,tag:35rWzI8We8IqHj25nUcwLg==,type:bool]
            zvolBlocksize: ENC[AES256_GCM,data:sjz7,iv:+s1yZACTvOVKAcT0CfuBUpLgTkkVoq4YD2YmGZ3Z8VY=,tag:3Td+iTQTxBFh9Or3YphVGQ==,type:str]
        iscsi:
            targetPortal: ENC[AES256_GCM,data:D/EqbUUpc2C0GBRFdUsrotA2yDgI7lVXEYBGHCzN,iv:8LBSiMcYfB4Gr16f62ZvLDnnMuTa3kqvhkzLMAAEGR8=,tag:5Ob1YseBw/xe/1LRhDp30g==,type:str]
            namePrefix: ENC[AES256_GCM,data:zYq/aQ==,iv:uro815YR9RRsdwQpooyG1tGxiqaTIpZJVnNK+lmXmps=,tag:sOXAVM3sf1b+MXWYgqMmzw==,type:str]
            targetGroups:
                - targetGroupPortalGroup: ENC[AES256_GCM,data:4A==,iv:s0BL0OIwfWYq7fldiiZKxscwJ0hrugnkmnjw0hNwg/M=,tag:J1OgmabZCyopeS/BacV7xA==,type:int]
                  targetGroupInitiatorGroup: ENC[AES256_GCM,data:HA==,iv:HAH6oQCsFaLPDhSGjkVYIJfNTnoT8g0bfiDxCNL9cQo=,tag:e4hfunF7vS6KSf2lnKqjEQ==,type:int]
                  targetGroupAuthType: ENC[AES256_GCM,data:p1A1gw==,iv:y5lHvwDgPlp/WGrooCYRZ0kaz2peVFOvxlQrnuQ8Kgs=,tag:xJsTZKy4z/HURgbU8wNb+Q==,type:str]
            extentInsecureTpc: ENC[AES256_GCM,data:TejJNw==,iv:2wvWn7qM8RuwPusdigkKfXhl1M4xKo2D9Sl7hO+W5PE=,tag:hd9vS7RQGMo1A1yPzsWIDA==,type:bool]
            extentDisablePhysicalBlocksize: ENC[AES256_GCM,data:YW9bew==,iv:M0rFTjk763aW5JiGxsDw9OPWRsDQpcOw7Bqp/z1ZHCM=,tag:v1rfQ0a3+WStx1hb4TnQ6A==,type:bool]
            extentBlocksize: ENC[AES256_GCM,data:gfQQ,iv:pB8Qol2DPtKTTAIXcBRK7IHIgUlBRvNrH/ER0Ll1hr4=,tag:CiQIbeSX2OFbiyRo2QTocw==,type:int]
            extentRpm: ENC[AES256_GCM,data:zN/U,iv:ItKvrCzM2gZ1eSBb4PaFrcZPGAvLFYHB89iu4nsOvwc=,tag:aXQdhpE4sv+5L0YKXXGvRA==,type:str]
sops:
    age:
        - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV2lkT2xTNHBoZWoxK290
            Z0hIRk04SzVlVHFUQ242MmlGMkxDWGU5Q25RCk5HWGdWTVg3d3lOaVdpdmdVNENK
            TFZJMWxEd1Awa3ZOTG0rTk44bkxPUDgKLS0tIGZqR2lJQWkrUFNRRW9TZHg2NVVB
            QzFZa1dhWHEreVNPNXFXTG0wbjFSWlEKsuyGbGZoP40h7nn30VwWM8gsVIgKvdan
            h3it6hhIuRyzi9yKOJTECSyV1bToNYF35ebo5+nnb2mG+e2wDrTITQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T10:10:05Z"
    mac: ENC[AES256_GCM,data:ql0iUsXmYsQm8vhAPG+LOwertkvgyRsNX8BZ0ufbdl8tuVcju1RfhTkdH7r2+D4VCInEm6j4c6tcCwPpk/BLSPa2hSy0JnKlFQ6Hgtod1YZH76T+ihGnehojC8zq8GvAj3hkIzuso8d3AQfVGKS9jtWxrii5neP4vGksizMHCOI=,iv:7UMTilx+0g90M7WRqqbWrtFe/OnMSPVg+BOeu6YdKXo=,tag:T5+iIYa2DbnogbDTgL0YNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
