extraCaCerts: ENC[AES256_GCM,data:s3FAwmwpLhbPwkd37amXNq+AWVpRwadol7wONDP0hzpaeNW03UrhISXMX7d7Gg1fjvErlr3wR7mBLjqamsFizidZYk0TXlVPLbk3mhztmm7N2hOFma7vTR4hHOzwj0bwa4eWKh2pxGXrX/Xu2nNnYGwZzwfP1CSs/HvEDBGpLaND9GMXQOcOej3a6is5igaoCvSW+8YiNyx45Xq9loy7p2Gm8heMhMx+7Hv9Rxvx1NhVnsJb+k44l1kmhF0ThLu6NftLD8N/ONktJHgZ8Wj/QYxse1g20eqx8ktQYGV5x/9oH1saMZ5vqdRSCKFjWbqF9aXFMvkVbhEFK6v2rPS0vfjSPq7CzuDDXZKxCvGn+Dtx2jqymrj3mnAjc2dEWDChRKzy7Ym49KYw18MM/Yt8vvANiMYnzsBxIWn0o64i8/errbhguxSenL3PNgWPK6W476sfhSx5EJGGCD9waXXV0KxjI4mmd7ccSHdC9eoRTMQBHdzJd/p/Exd6bUALQ/JQNhlNZTnYMBKz/PaMzC60QZysthyhX4xxdqFKHlou5KXHi7jBqNlzNgsnFXHF7z8Wk+UdsPq+z3LUH4iy5KrOXyMh/L5o3Rlf9kb4XW3eldMTlBieqfHi8QjjI3WeMiSoFKOX84Rk1kOOLrg5QbwRPKb2DsRFtULixwoCjMt+CEodCVE5nmH8WEcyhdGB3Ml3y/Vqs6PfOo2fTcVJJVHNkufVzSYw+3NpGYg1ETFhIsfAi2msokgmKbcLQB8i,iv:Q5ta1nvdfxRjd3arBa+uULlDioUD5QlzIPVb11IZgxc=,tag:d+UJI2UMhRzofuL2HqEOdg==,type:str]
csiDriver:
    name: ENC[AES256_GCM,data:Ca5Gg0Y28O8OZG8lRfHNRUCa,iv:N6R5MRA8Q2dhhHVp2cxixE4pSa1ko+CrmKKWTB1HaaI=,tag:gsCTeVbnRJvloTPyp04I0Q==,type:str]
storageClasses:
    - name: ENC[AES256_GCM,data:mgyGp4qvTgKBXwGkBJlPRkis,iv:+MYtQpirPI9PwTc1NE34wTuL1/iJWesMi1mg6P2dhhI=,tag:bykafudHhEo8BfCLv79Wjg==,type:str]
      defaultClass: ENC[AES256_GCM,data:viA3ByA=,iv:EwJLQbcqsmGHLlQnz9LCrPKSiPVd65sBVRWLZewdSpU=,tag:N6939Ci102oAMcHv0x2tWA==,type:bool]
      reclaimPolicy: ENC[AES256_GCM,data:0kLOopoM,iv:YZsM8Z+QzT9CQTWgEV3eMy/89r2MaM33JO8WysOLbXI=,tag:DvezUhRAHyMQKW2eRnTSZg==,type:str]
      volumeBindingMode: ENC[AES256_GCM,data:Ss4+rwz4phU8X2XeZ08nHULH7VE=,iv:2EGqPNdXse8tVkXO96fd1NF/2Sa6jHMHWp8qXhPeAVY=,tag:9fzp+5VTtTZVlwSTkUlk+Q==,type:str]
      allowVolumeExpansion: ENC[AES256_GCM,data:CMvNCA==,iv:LJeUKXOO0LjKSHN9ZFfX5ROeBo9kg//LTovspCdWVQU=,tag:BANx0uyOvvkNdjubiZ5R9w==,type:bool]
      parameters:
        fsType: ENC[AES256_GCM,data:0/AiOw==,iv:mHZ4lPUga9FNj6clK+KSDsi2ZN3k719kS5/eZm1kveg=,tag:twkSOUlxVrlLr/L3Dbvarw==,type:str]
driver:
    config:
        driver: ENC[AES256_GCM,data:knUuQeapoFHLWJaDn96oOKs=,iv:JGet81lKKFa51dkmMrAft+kfGnzp512mipuoaDWzH6Y=,tag:txdDqglFkCvxu3onWlRRMw==,type:str]
        instance_id: ENC[AES256_GCM,data:Yyfuc77Wg7xtauUSKQ==,iv:ljOkgbaE0Kkk/EJyux66ajixfnYE+4ibwOyQJrONOIc=,tag:qBZhQfWj+yUIxfCp5EggZg==,type:str]
        httpConnection:
            protocol: ENC[AES256_GCM,data:eoYn6Q==,iv:gUJyPVHiXm+DmBVEeVeDontGKo0grftMkpj09YmBkS8=,tag:MVvkkr97uipJUPvQ4ZtwtA==,type:str]
            host: ENC[AES256_GCM,data:Zf2uZ5Ot3QK5yviMD+yq4Pno9JjCxx9/XA==,iv:OTYREuy8bRJc3zWt/uf6OfPBxs+U7ihEDk2IZMts27s=,tag:TKo/54Y0fi0D8BviKvueoQ==,type:str]
            port: ENC[AES256_GCM,data:VRs=,iv:Yvxk+DZUz9BI4ichuzmtQBFr0iqFYm3tyS+UfM0EDAA=,tag:wXOHz7lSjvnz5PNj3/MhrQ==,type:int]
            allowInsecure: ENC[AES256_GCM,data:6RLQPg==,iv:vHh4RlZaJdytH3pVdRGkT079dbMmJJg8P4eauBLHnok=,tag:oupcLr9hZVayvQih9QiOKg==,type:bool]
            apiKey: ENC[AES256_GCM,data:HBdv6Wszqqi9pWOuZ9BgoKBF22o42D7EQxwzvtVwo8c0WXY302jYdCSCbw1a1rC1B7yR33wFh5oGVX8EhmRROinP,iv:yuTZIzqtz74DXNUVlrhqGU4c0z0XrR7P0tH+RbNq4NY=,tag:Axld2D+FiGP+zFCRdKy5zA==,type:str]
        zfs:
            datasetParentName: ENC[AES256_GCM,data:mfiREW/Sfo6/wD6dGf8=,iv:uLIao4hk8sUf8JkfJMA3VHT4m51eBybDUiWTI9iWYnA=,tag:9QykrZ0tuLOpqxQ7Ejk9Ew==,type:str]
            detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:lzf7OnYQ6ScVjMSkC2ihVCXBdY2Rw+cV,iv:JpVsdq/SKth9mp8DG8zy3eRCuKCo6LKs0woLXP2bidY=,tag:Q+Gfw3FLL0j3fhQFkElUaw==,type:str]
            zvolEnableReservation: ENC[AES256_GCM,data:jJnjQMk=,iv:z9wc4bE2f5dkESqZKNEEiMHaGXKxukDLF2Zc0QFQqSE=,tag:jvnIIQNbGs76nt0eMRdbGw==,type:bool]
            zvolBlocksize: ENC[AES256_GCM,data:I33Q,iv:suKl6PUNX+pgAlY1ewOYiytjIcx3PW1lSAu8vjaJzUQ=,tag:YIqyDgUvnQII4meEamP5JA==,type:str]
        iscsi:
            targetPortal: ENC[AES256_GCM,data:1ropk6rgQqK/dtP+GEEMhLb2GT3pEI9mte1/Z5IF,iv:pg0/M5jkB+e/4Bm2tlVU0yP1msNRo4Da7gk/mONRihA=,tag:3B2XX+gTqE5MzFf1Hq4VkQ==,type:str]
            namePrefix: ENC[AES256_GCM,data:c9cYqA==,iv:ClnPqGSqzHs+48GZVP0ODwY486dSZYDP5qXOevzyXA0=,tag:X+4TgJFCi+PFVtA3xwPrfg==,type:str]
            targetGroups:
                - targetGroupPortalGroup: ENC[AES256_GCM,data:hQ==,iv:apY/9ffkJOf7Z7oLguhfn6wcxV4w+OZHv3qcMYFgebE=,tag:SQgpsUl1zWRAP5AZYAmAEA==,type:int]
                  targetGroupInitiatorGroup: ENC[AES256_GCM,data:mQ==,iv:fSW4O8CtnPx4DAxRdNFVEsPrX7ThvsurBOuglpaP6Q4=,tag:sQP0EuPDO7GIwDe96jjiSw==,type:int]
                  targetGroupAuthType: ENC[AES256_GCM,data:IAfSzw==,iv:lEoGTfX+a/lvmQM4bCL7XqtGtHzrRj5KS6GZSGo+iCc=,tag:jcIwLl0LiHAdN8/E5VAPSA==,type:str]
            extentInsecureTpc: ENC[AES256_GCM,data:QlrW5A==,iv:KRL2hHAJ4u9wOgxO+JSZIxy27/CSfZ0+hOZ6fC+XHfA=,tag:55lnj17a55Ht/9QozwmENA==,type:bool]
            extentDisablePhysicalBlocksize: ENC[AES256_GCM,data:YM7oqA==,iv:A+ws5DAfCOhq+Xf6m0e5STOBXJsvICOLHU4xGYoEP/g=,tag:DQPN/eTJf/Wrg3drxcy4pA==,type:bool]
            extentBlocksize: ENC[AES256_GCM,data:fVWr,iv:uA7AjiBKtbfyKwsEGYfUMOcGnwuD2/W0Q+1HCfsn3vw=,tag:523v/fTfbxMAXGLp0DhvwQ==,type:int]
            extentRpm: ENC[AES256_GCM,data:0Sea,iv:bXuXgwERPTxzUGbXdiJ9TlFuj33q0GLYKGP5Anq1P9k=,tag:rzYhB3T7Hf0GSoNLoP9l8g==,type:str]
sops:
    age:
        - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZDlSMU4wL1dDeENmb1lt
            VWtvOUd3N3B5dXlRQUNaKzhXQ1N4cHEvNmpNCmpUOUxkeWc0WS9jZ2dtMU1qWUhH
            dXJQYktkajNMRE96UmtGUmZ0MXdZa00KLS0tIGtoRFBUMmFneGRlWCtFWXgwaE9i
            N0NlMUk5QmdDNXlWNW4xVHpNcENPTnMKF7jbdVUz6lydLuGr6UN8C9u1f3fYm5iA
            xDFPPVoY1KIqLVn5FNMpw0/cwWdvoFIoQlAG1aOr7Yuvo+dxhWuK1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T10:39:26Z"
    mac: ENC[AES256_GCM,data:iN0ymS2q11QISOoWDp1dmEP02ScI3+8AuXoQrAdxNp9lwHDj7j7CMFLKcIXiSpYh0R9q5bnYfdT/4bG0S0clNVfqhLGg+BwTmI7k9bPbdKn3SmpZgxYi0jX0r0DRRthGslLrprP8vH+eEfVUwS5yaS8HEDg9vqNRSoXbXEU+TSM=,iv:KjETyRkpt/6WfeXxWosvSXE5FUBCDIY74QC9irC1Lhc=,tag:D0dDeE1eDsJDNO3+/13oCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
