extraCaCerts: ENC[AES256_GCM,data:vZEyqt/JbEHpnezTAqPnjuJu770H0GfOqYJHnz+HnytoapiUAGLzjwiO1pMApzk4EEEh9X239jyVAKoThaGMeazYoHn00OoEEwlC3iMtBOa6WnIVM3wrEYAC52U+2VbD9wskwV6uk2nq9TzqtxFZR81QBTcHSKB0VbdSlQUZuCHFQLNmpO2ScNNf7HHrGVuTqu8Wqrcwvk4eRGmMTVr8gEq12dQ65dk9AeIXHwa03/frOG6f+EhMf88j8lWurzE4jdhzk5Bfg/UwmUhvc4JvWEkd5Wp0e9LDEGeHwypjzoiSOxXgiA2Z3odG/kpU+V1FYoBuv/q2Nw9eIn1bSzN1S3lc7a8nt6n3JbIpWZdsRxvfRxTGPQmkqVNlPxFF7Oj7ZDq9gGxxm7S34oy+KziDVFuGIAGZQGWAktvcp0fCZagQ3p5Qe/rFOsdqTfoZWncD9qqd3f7mj8gvZ/fTQaCJie5atj2fmDgCoHJqNkvSq31uyzSuyR0S/KnqPu2IbdsvbZnxS3HgWybTIi/YeixV0aWKn2Xv9tz8VFxMJ0EtFuEaqRB0vM3NezZznhdtQ25DLG1dGKAlZlfibmLuhRS3FaH4TS+Im9eEBVwmL8dYS7fdecEjWIjb0Nkq00v27uP+wsYdTSuN5+AQUwkKHkM1TJK4cv2ulPDa4wnZHX1ziHGXaN2wsYA0j5BliR+BD29iha9ceepG+Z90c/E64PvX60hpRoIbAd1KyONiCDyqGfygW6808jcbTsXCfdxc,iv:yFDVtRJDhwXoSS5MHu4W6pya0s+61Spds3uDZqGBKQk=,tag:17Gga1P3/2+x1T8cOiPK7Q==,type:str]
csiDriver:
  name: ENC[AES256_GCM,data:Hv1qRL9+inmcCTT1tYgu0Owh,iv:/UKbqOcL8f73L/nOnwpfw+1cv5rPRgjt0yJhMIYgt2Q=,tag:Bavlk59fl106RD7Cmn7D9Q==,type:str]
storageClasses:
  - name: ENC[AES256_GCM,data:0i3H1CrdM/PhtVkBVw3ejnOd,iv:LwVmqewyqlRb0a8U1VF29jwuRnyXhXHHRaW9ZLYwXZQ=,tag:vKWxHAeoAWV5YQ2PEKKm+A==,type:str]
    defaultClass: ENC[AES256_GCM,data:tUEJa0c=,iv:B2athvFk+ipSitMID6Tjmelu5/7ak9eGGX8XB6I8VTw=,tag:pRctfHQyuo26DHXglMWvDw==,type:bool]
    reclaimPolicy: ENC[AES256_GCM,data:LqmbuPVu,iv:SNFSW6xP5JZjld+K8gGN9auL7FFzRWIcD8M+tfURSLo=,tag:yyXi3xrvIXsT3Yf1326mwg==,type:str]
    volumeBindingMode: ENC[AES256_GCM,data:Bowf3Jj07st6ckc9Di2KZRWGtbA=,iv:OToKLWOEXSC+I23DsBqGHLJiRkvoMQUdd9EBG3dJh2A=,tag:oeIyfY5KA0OOVor+TQKsEw==,type:str]
    allowVolumeExpansion: ENC[AES256_GCM,data:RFUSDg==,iv:AQel5iIX0E8a1h3okSwUUoXzrltJ4DWKOOqN7T7kcNc=,tag:OuFwoCqZZ/B9Iccv7NcgDA==,type:bool]
    parameters:
      fsType: ENC[AES256_GCM,data:eOqJoA==,iv:rge72OUbtGND1cQGlOp5YNd/LTbMua5c0a+llEG8I44=,tag:ubbJpPFX8iZ83qMsjH9tyQ==,type:str]
controller:
  driver:
    image:
      registry: ENC[AES256_GCM,data:/IFLXKhguZ0iHF3YdThxgSrDw9nEVGeLEiUyi2SySIDsYjxHX7U=,iv:RtG7cvNBRGNTX1oQ2Gv/VWJERG2y+qEYPtO3fc+owOA=,tag:odoVcqeB7soCwAw4Gvrh1Q==,type:str]
      tag: ENC[AES256_GCM,data:/7Y1sA==,iv:29SxoDDg888SIFPwCuc28W2iOuvtZz909wS9OuJfvFc=,tag:1HkmDzPQHJ/R83EN2qHrnw==,type:str]
      digest: ENC[AES256_GCM,data:tTsv5kHeqnlHxIQtEcmJKewI9sliOqINyxsiC1TaVc5TbAiNj/z0mjUr5h7OyXZ+5gUrlaGMddO5SnhOYqVzKj7Ct0ZiD/c=,iv:fevifPWiA5gOGYXbK1qMvIbU48EoCazKcqCCLtMuteY=,tag:m2UjPwUX0oWTW999121DGg==,type:str]
node:
  driver:
    image:
      registry: ENC[AES256_GCM,data:BdtEXTf4t3nSE77fd+ZtUxpnOdQ9nennO3SLRiV7pb/3Om8Gshw=,iv:LdSC/6/JQN7qtgdmvAAYf6apkgBUzsFTMLaAOpvYwBM=,tag:a0hQPHg3IyaXy5RcZQYznQ==,type:str]
      tag: ENC[AES256_GCM,data:RQBOsQ==,iv:HSSTPJ/R8o0lKYaKJcVsVZZjJih+A5va1PAnA6Uua18=,tag:gXskwNMCha7XSaxv43r+Gg==,type:str]
      digest: ENC[AES256_GCM,data:E8I3nF3OzEJy8TSnL69hRwSDaM3q0ty7fufM8Q22fJ2pj/vyTrNKIrrfpx69USVp2HyKl1xDCvziX1QzzLY7fEN9AA5xfHs=,iv:lTwY6sFfx9TeP8jyR5UAQKjDnAlfuXCZRZqkQkPwrs4=,tag:gPzJTgX08cnlTFiiMdM8fQ==,type:str]
driver:
  config:
    driver: ENC[AES256_GCM,data:ZJRtnEBIlCofLXz28BbdpNQ=,iv:zTyq+NAVnhprj3CG8rrA2UBW/NMdJ7JKVg2APS0FIIg=,tag:VpGaKKM41/QRPuTu1ItgIQ==,type:str]
    instance_id: ENC[AES256_GCM,data:t2j2uh4CtXbngR/S8w==,iv:IaUO44vBdyJFyEi906b3MURiNAR5+9Oj9me9SC55BBE=,tag:PAF3H2ab1wy4lpbSDCrQ3A==,type:str]
    httpConnection:
      protocol: ENC[AES256_GCM,data:dwfpozc=,iv:eE67o+3kiTCS+/LiVQGRwZ9Y9V0gRldzn+6j4hd+Cz8=,tag:kNHpn8ezFRNzE5JfYiSd0g==,type:str]
      host: ENC[AES256_GCM,data:ncpRhBVCBIi+t5oJnmu6Q+ebJvTHAPW+gA==,iv:bNwJnrx0Wbd6bx8m9EmiAr2XlGFfClKFyyIodCp7E+c=,tag:qxYXfvTEaNBWB/grxIjCJQ==,type:str]
      port: ENC[AES256_GCM,data:eGYB,iv:KpkLho/DSIuw1IsQzpFVlQUB7ab975QO2UTYsgeajEc=,tag:AkobiDTkMqenrPthOgUbUQ==,type:int]
      apiKey: ENC[AES256_GCM,data:O8Y+5nys5vI+iX58M18IPakvQIE6XfT1RxT+/VbSlcuARBugXto+4p6zTiWQLdaLi0h91fLOF4JOAPAPyId0yH/f,iv:sNN/86KZrSKhwT+vTKL7fSNsU9TFl78mWLvvYoeHaDs=,tag:PbypZJNdwsZk45fQ1Y5XiQ==,type:str]
      apiVersion: ENC[AES256_GCM,data:gg==,iv:VqMFnA+3+PCSOSrTAwmKahQXmbh5oua1F7XK5OWAlTQ=,tag:3JWh0kTaAvV0mEZlAlPLgQ==,type:int]
    zfs:
      datasetParentName: ENC[AES256_GCM,data:nVPqEXHLSuX9lShCgFo=,iv:DBBcANYkde1kzTMS2SIMfR1RRqAZKPR3UYeE0IElGQ8=,tag:Rhbum/mDQJKnRd2hiPd2mg==,type:str]
      detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:6Kb0fo8x+vdHSFzr6AiNHs/nDJBBU7Vi,iv:mEh1YSupAi9hD3cDITJRva2J8rLiZSGVu45875Lae2c=,tag:RRUx1TUvklQjYEtbEgYWJA==,type:str]
      zvolEnableReservation: ENC[AES256_GCM,data:WUV8UBE=,iv:2bWOSKeg+ROJpvk8jL4FJwJphD+Ef4s5EbeR1S8qbMU=,tag:gZtpNEvp8umoIB8Xrc8sNw==,type:bool]
      zvolBlocksize: ENC[AES256_GCM,data:+vby,iv:qiB78o4rQnxS/VRB3CQWji4la2hnzHJEyOWPs73IwbQ=,tag:+mPdNKAKx5MvuuIh/lt6sg==,type:str]
    iscsi:
      targetPortal: ENC[AES256_GCM,data:VBG6ab4f7ccrqMU/ViT8O5u3c+Q8bizuap0dvEq7,iv:UAriqas+UGHBfQQ/zRkcFV6hYrmvRDxB2qhw88CgfPE=,tag:gi8SQMrYoGIobJdGW303Sg==,type:str]
      namePrefix: ENC[AES256_GCM,data:FA/02g==,iv:hCwClTFQOKODguZB0VCYB0StK65vbOi1GZM+vB+8klU=,tag:hRggh1lNmDq1muH88frl8Q==,type:str]
      targetGroups:
        - targetGroupPortalGroup: ENC[AES256_GCM,data:2A==,iv:61KqUp5oJPjEkeaFiNQ7ohWXtUvlZk9LMh5ljmx0yKo=,tag:Wvue/31kM35lBDOr8pHqUA==,type:int]
          targetGroupInitiatorGroup: ENC[AES256_GCM,data:VQ==,iv:+CIG1ylZDXlsVZyUor1C2Mdk58Dn/Hz79vjX4TXVWSw=,tag:wKsa5iBcEQOHnaPr6BppQg==,type:int]
          targetGroupAuthType: ENC[AES256_GCM,data:T8nwyQ==,iv:9PzCa1LE8s8WSGYlI1K39Xnvils+KpfpQ9HieWC4Ml0=,tag:NQNMJt3QqqTELbIOP7Vl8w==,type:str]
      extentInsecureTpc: ENC[AES256_GCM,data:VgHGVw==,iv:Dcbh53sYn8c4ew3Z2VIv/RBdDJ5TkRx8cXznkymYhPY=,tag:LE0Pu1Z3+E9kcsxNM0w7Uw==,type:bool]
      extentDisablePhysicalBlocksize: ENC[AES256_GCM,data:8uJ63A==,iv:wvcv1AMGYuFCxLgRXBr9TJKIVFmrcuWXUZnEvKzqRbY=,tag:GPjniErb88bz7fzsIQxz+g==,type:bool]
      extentBlocksize: ENC[AES256_GCM,data:r7CC,iv:YMJHv5G73/RcFcWo+v6SeO6wSaUJ2e+EgoQNY3b04RY=,tag:3CD8Umnp55GwJpApHzGPxA==,type:int]
      extentRpm: ENC[AES256_GCM,data:3kB0,iv:8iTX7vWUbZ0BTd2EByqvrwH5WO75l4MNzNjF7hDevs8=,tag:qcoQSt3TND39YyiUJ/uFCw==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Vkc3dFRBcHBNREwrNmp4
        TDJFZkJRamhsQ2ljQ0NVL2RTbThjSXVPUTNRCjF1ZlV6SHRRYmFjSHV1bFhLenJp
        cEE4ZDZTeTZrWFB1MjdLMmFrMHVpMDAKLS0tIEVuTncwM2x5RStGaVU3T0NjNkFK
        RGVUaXExMWphZEg2YndkY29JNGFyaEkKI6NM+Q5ruiqJJdWDBieGa1vNY6+U3a16
        ZDahhUuFYS3YagLUpGAjdAp5lxfbAhTmVDlRgvkV8tnbgeVFilBqRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T11:35:22Z"
  mac: ENC[AES256_GCM,data:SXYGdaZ+bRA1l3/IcnixU/XGqA8kFUF86VBn0u+iCqpz4fgttZaVXfQD9fKiTOzgUTNbo+RfPOgSFdhUcNnhlb2i9toLOzm5d8LeBVNSpnIkSrN5eOPKPjpicGUivgiruFxm4tt2I1RDrps/OLYvfjiwjimOtBDFKDjj3Ne02HE=,iv:Z8AxX9mGn+qFCJAJ+wEOIpf4MSFTT2D/ZsL3EIlc+4c=,tag:eclzO5dqnn9cIxva2uySQw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
