csiDriver:
    name: ENC[AES256_GCM,data:q4eyex67un4Rrm1qA8qQWSIH,iv:4hBBquT/NGTqCYWxvSNdDjyNfbEXvKxYP4lpJAcGwBs=,tag:wsM/+BpnHCuJ15GoF5wpcg==,type:str]
storageClasses:
    - name: ENC[AES256_GCM,data:JBJpVYQ+UwNhxEmyvp24qyaO,iv:Rr0CEkqqzO3PrxpYTsDNXR8ANlbaPE5pt3TqSHcqgbM=,tag:mH+utuPuvKnUKHixeB5fHw==,type:str]
      defaultClass: ENC[AES256_GCM,data:BNEMDIk=,iv:ZtNRYeYYQ9Sb0Wav7zYd0tCuRMAVXjvmpg+rLQjig/c=,tag:BAx8OeSEucua4fjXcdz3Vw==,type:bool]
      reclaimPolicy: ENC[AES256_GCM,data:Q/NKXN9X,iv:JRHFKh2HBRM1/a4i0bWQOAUtFgITDJ94AdErOWaVPr8=,tag:iAL8qMG4UgxX4TNZVZGChw==,type:str]
      volumeBindingMode: ENC[AES256_GCM,data:N9dE/HDkXwGuaK3SeRP0UcmtBJ8=,iv:eT1WlqvbLpOCGdaloX2p6JJ56Y9bxW7Q3lNQQvQ+HeY=,tag:j9UcYNeNUPruDoxSEWoNsA==,type:str]
      allowVolumeExpansion: ENC[AES256_GCM,data:kbg4WA==,iv:CCEZ69BSgL9rDU7XdYkpd2S29INzt87Eed6bwWShOqo=,tag:/puC4E9pbcLXp9GTShrzvA==,type:bool]
      parameters:
        fsType: ENC[AES256_GCM,data:FUqItQ==,iv:XaRdlpBwB8v++OIdaH98A2ByHlElUl5mCuuclqzXDaw=,tag:jFkbrrO/DDIZUaANt+Op9w==,type:str]
driver:
    config:
        driver: ENC[AES256_GCM,data:PhAzYhcJo8bzvD0iXkOdhE8=,iv:8gWqFuocdquwveN2MHbJ+e8Ad7lpxELfYCi2kcptMHE=,tag:vbV9W6H3ZzapDj1N8tkuXg==,type:str]
        instance_id: ENC[AES256_GCM,data:AmHsh0LlzD9OLrKIFw==,iv:tqm0e3ScWYV0mi2fZ+nKwp3gEFreuyGCDjMsJtvKWak=,tag:a+cLwcK2vN5LJeNS2091Jg==,type:str]
        httpConnection:
            protocol: ENC[AES256_GCM,data:L4qugg==,iv:tN1A4TQ1+hIkEdBxRyKGi7lhK3dSaMkxpCNqDZqa0v8=,tag:tMl4S6MRlMdwLOYAtfjfkg==,type:str]
            host: ENC[AES256_GCM,data:Asmi/dPtWHXH0JcqP4mrRgeMn4jZpSuTrw==,iv:oXHc6myKcKuf8bm24jTsz8bRF8dtF/j+q+P3Z3gWufU=,tag:G9CZ7jnumFaGmuKlAKUS4Q==,type:str]
            port: ENC[AES256_GCM,data:jYc=,iv:+NSi1KnAXQIA9f0URfsLjMK3UK4Eofdt/1/SU0lC9JQ=,tag:AoWwKhTUikrWPR+uOoS83A==,type:int]
            allowInsecure: ENC[AES256_GCM,data:8bh8CQ==,iv:+IMEe1OUDqcs/a7y5E/WjtvomUkShd6u74SslFDWIVE=,tag:WQhVA0OyyGBG6jirY/AVvg==,type:bool]
            apiKey: ENC[AES256_GCM,data:4s/WxPbslFp2WaWcOzN2iZiNJfU6VIAFp9bUfEji8hxixyORHRCUcu9ci5Vs9QOy/IGED7hx4q8gsL2S38hglqSO,iv:3vn36qLnqUB4W8iuw+Ngfi7FQiNFn3+1mkzy5pJUuyc=,tag:294WotoazWOI4lci8QZASA==,type:str]
        zfs:
            datasetParentName: ENC[AES256_GCM,data:W7LVjnn6JoH/3SQimMQ=,iv:EM97Rudv8SX3tUf6oT+47f2mz3G5TAJwYJ6dErB5MDw=,tag:hPyYwZATpO1jxaOsRv8cqA==,type:str]
            detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:gj85EiVdfx49A4u0TeRO6p01z3F9UwYg,iv:LqySiJH8T0B9RhKG+VHvJ2UDxhf+J1/a+JpPUnr+CNo=,tag:YWYO32RZBObXXEQyUGGI6w==,type:str]
            zvolEnableReservation: ENC[AES256_GCM,data:rUYJctg=,iv:KcDD43vWd4Tktk3rI7Kc9l3Swan5W2+DeuSr1nAfKNo=,tag:m93H8Gxc5YtmkvA274bUtg==,type:bool]
            zvolBlocksize: ENC[AES256_GCM,data:3OA9,iv:KpW8BKAWB/g6Evf94ZOACvIQLB6OC6BAeZYQznymO84=,tag:wzWEyHLj3QXGIYxY6Ng2Og==,type:str]
        iscsi:
            targetPortal: ENC[AES256_GCM,data:zSqh5dBTt87VjVjW8iFvB7IYeFdbUnzvNlEFmuX9,iv:wxx0N4kEYGRUfB6NB5zeIgNUplN1S+C+YdRhHH39Q2M=,tag:XWeSsgegt18Nu5yV8R8GgQ==,type:str]
            namePrefix: ENC[AES256_GCM,data:yPwA6w==,iv:t7G/d/YRR5W1Gc/TmLXhTPiEBmb8T7gfSg1CnC5egyM=,tag:os0b7BQq0bXAdSMvKenYOA==,type:str]
            targetGroups:
                - targetGroupPortalGroup: ENC[AES256_GCM,data:zw==,iv:LHqEnsjFJMso9Xf4rF09kMcGBLnc7dXv7Me1JOXw32g=,tag:n05gSyzeybTPDet01CP3Hw==,type:int]
                  targetGroupInitiatorGroup: ENC[AES256_GCM,data:Vw==,iv:fSyMhUmjneh6iR+ri3MCuZPuFV/LbVPnXa61/5QQlOs=,tag:ljxwWmKleBZ6EROJF4BVLw==,type:int]
                  targetGroupAuthType: ENC[AES256_GCM,data:6vb+zQ==,iv:b3H8Sz0jyx0YOoOeWbEytikd1LkrhxLQVPdlYaEGpPA=,tag:fkPGpN4/pDBFNcU5oLItDg==,type:str]
            extentInsecureTpc: ENC[AES256_GCM,data:shLb0g==,iv:RSv9hf7f3nlX8iDPJS60DKYl4CUUQufUW3N1/cW+yZs=,tag:KLptieR09vEGE0K5lI5KKw==,type:bool]
            extentDisablePhysicalBlocksize: ENC[AES256_GCM,data:agPxtA==,iv:gVo+dwhA9vn+1bTH9bpIjIhHAI70YtswoNWCL9pN+54=,tag:Dkdlvw0UlVhYYbVAdRTGZw==,type:bool]
            extentBlocksize: ENC[AES256_GCM,data:RO46,iv:u1Mucn4Vfj8Pe7tCH/PiXbSmiOWUAcevM1ToB+8q7HE=,tag:jrsKtRhGnAH9fu5DOL1XfA==,type:int]
            extentRpm: ENC[AES256_GCM,data:6hpU,iv:ko3TqrukPbPgdpXq/RqXBS0hrla1piYCzowR5AfXyx0=,tag:1koJUW7wwPZDE7KkDL1o7g==,type:str]
sops:
    age:
        - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TE1LYVZuTk9HeUtjaUF0
            Mk4rdkFqM1J4ckhnbVJBZW9mR1dJczVpYmlNClh2ajhvUlBOUTRMa09UK3hsa0U4
            dWVFaWtKUnhQNGswWW9MRVEwNHJyd1kKLS0tIGZpOW11VzI4RU1vOU1NSWFnR05Y
            Zk1zVFlzVVB4b0g3MmJzQzc5S1JoZkUKmvIv/Tq+2VMooW+5/aEN8DEzr1v96Pk3
            rvOlJfFAkJQoTUBEEFXJA3Rq5vLOvFxkNMOV/+Iucc+Gz29uEuin6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T10:33:18Z"
    mac: ENC[AES256_GCM,data:caVf9X2KrtOD43JtbHQTH+R1znDXEdTFhkN8QWWUoTZE3lyg8HswpENlQNS0d4SECeZpecMOjtefTEjuO+Uz0YRkYjwRPg26WlmgcqrjiQ29xs7nq5zOpXReqgZLu+HNwS8zMFb/tzqCAIO1vXZNkVKXSyBmBerKuc6lmmoj2ss=,iv:lyacVbkYHo5jerPguNroA9sSaSB0g0zQVx/+5BWoNKg=,tag:BZEts9D2g97chPYXQh5C/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
