extraCaCerts: ENC[AES256_GCM,data:cVhvvtpGoUBi5fXCqD5Oz5rY3dT2HReNFTWHh9FnwzRy36ecfALZwyOUCuYBIlI8eFkam4vfeKJ4RIT71qvsJ4t7pNk0oZ4F730m7dlJ/qFJ+S/Id4UQAEwa22ArFZiGMl7ii3ZiH4YEVn5kmYetqKuY1MlMgG1Sw4VhtBtLA7H5OiOB9sVSvq49jEx6cjBrusxF8kd0a5uq2f4FihVfjGIfMficMQA1d1WfWDzeoICGPJj1yNmaKIWB2DB7QnmpQDYuobX4bckLTLuV4G9NIxYFdltsoKYNisN0aV/BJWqj6wuAN/jMWrHpMK7BvU8RrFH2Wj2yCnwB+LHzaY/i0w0xkdE5YW5wCKjLjuahd/4Ci4ETqSjj0kdLnqO2HbgxZ8AObBpG6kwvb398NDB7k0EeF15ryGtnPI5EC73Sdt8h27zMiUXXlZY+3Wva3/okPYF9sPO4d9RxEJRvC4ux2oGBQsHb/XNrO9I72eheKAX7NWIAiGLt2VYzPPuOG9PKYKpwzKzQjewP0RIYTmGbvYJbrBeJCmxmWZigO/xq3RZzhlziuoIrtBHIij84JFayyI78QHbmlUASqADn/TCXx2Gi14hx0MqFCPoWoXvWi3kO2tHKKK3jXFQY4EasoZeAmWT/w6PXoqzQAr3hW4HI9PyE0k3PCjNWmmIUll83flN9MdK6l7wp6d5uSiVhzqfH8ietan468+4H+uqQgw90CtYp47huVyO7qvKJsljSpPLazStNsSZ5lVkcn92t,iv:8WkLDZMAklRH+38c0+nlOXBnKhI6zaI7YXgisNHGauU=,tag:4jWzBDXPIghifl55jtQ+sA==,type:str]
csiDriver:
  name: ENC[AES256_GCM,data:lR6foNt00svcOWQJEJGg1+LB,iv:qGERrRt1MkDvF+JlBzj6+DPdN6JP5OlAEJFtD3NqFaM=,tag:15Ic5z+skJTRi65C8fNhxw==,type:str]
storageClasses:
  - name: ENC[AES256_GCM,data:k/n7J1MjvdGfDZ+8ruDK8Nku,iv:qG5xpqRHdwSewZdqhd0Ir0W2QO75ory28kAioMgXans=,tag:w1Hbz9HfxFtmwerPQeQoUQ==,type:str]
    defaultClass: ENC[AES256_GCM,data:8KTRcv8=,iv:4H8dOtGlt5zcXbaa9DjawQ0mX6thBU9nJ3S0z76egew=,tag:WDrU/vAoMVg2EHgFF4Kcmw==,type:bool]
    reclaimPolicy: ENC[AES256_GCM,data:qeDgSkek,iv:fR3ueBiMHsfPB+bVxaNRmo7YSCBNa5f91JCdc4iJPxY=,tag:zpf/uZF1hYUIKwcpPRQVOw==,type:str]
    volumeBindingMode: ENC[AES256_GCM,data:PsdLLuMc1z4QUlruXHcFTeAL5xU=,iv:8Y48ypx3QtjPCu/YZQu+Jx3FCc/QjM6il7QP++gAwuE=,tag:x6hogiTOFGBDPpzgdX4oLQ==,type:str]
    allowVolumeExpansion: ENC[AES256_GCM,data:GudQaA==,iv:I3d3ZaVzdQdk5Xcue5VMh+5Tyb1uoLdZVPg8QgnfS5k=,tag:vTt+xKKuCts8XQzIWpA3Og==,type:bool]
    parameters:
      fsType: ENC[AES256_GCM,data:7yeHkw==,iv:ReM/+pCgNPCx9MiOXETiMLsM30+xT21/F29imYRJF6k=,tag:Obm812NbAbyP1yjcfFGMZw==,type:str]
driver:
  config:
    driver: ENC[AES256_GCM,data:rqZ4MxWI9oXjgp+i9dm1tJs=,iv:OtzqZQTfjGT3NAKVGY89nYNRsc96NZQ+iEsWHt7mpVI=,tag:swhtxDGAkPPm1lY7Hhdxkg==,type:str]
    instance_id: ENC[AES256_GCM,data:M2sIBo4J9hm7nIEd+Q==,iv:P3FmicHrYN5y4SusxokSBwFubiUZj5atHhQ1Rc8WKQU=,tag:zTtNXLdCZ1C+ZeI7J3NbXA==,type:str]
    httpConnection:
      protocol: ENC[AES256_GCM,data:egReag8=,iv:rKYEFYeDpRZeqcDjvmLm+0ggZbMB6CUnDs9qOp7B7Qo=,tag:6OvevpRBKWc4B0sqlejjpA==,type:str]
      host: ENC[AES256_GCM,data:oRRlLYtZKxTwLvzGutwCQEmH+wmVZcqH7g==,iv:hS/NO2OwvYVFxkzFjkjPKL7IqYlZywOVV6HSMR5LEQI=,tag:qPHIEYGJu9n6Z07JI/MwaQ==,type:str]
      port: ENC[AES256_GCM,data:FJEq,iv:zutNkQxPaXbtGs5AFetnf7vBr2M5fvI8GBbsap6Gef0=,tag:DtgIyuOT5YjPTpj8RLu81Q==,type:int]
      apiKey: ENC[AES256_GCM,data:B2mnf3H0ShBtqpBkuIKWEdnHIb0t9AwV9aQUaAebj8X3l6I3ucLnww08AYlOIbDNJ8PJq94hPMTJu+LQKTQhwpNc,iv:4kUcIhgs/0Y55/htdhJ/cvXnI9h4PYOf1WNnbTH1+j8=,tag:Dcba5dxhePEvzH/tUQXT3g==,type:str]
      apiVersion: ENC[AES256_GCM,data:Bw==,iv:ZMIWC5E32gD2c6ussVrPkgfZzWj46amNJJMsnDeuoCc=,tag:j9lJq2HzhCC9AnyXNBorUA==,type:int]
    zfs:
      datasetParentName: ENC[AES256_GCM,data:icaZ5nFavvPHmjQdh98=,iv:UxdUvb5AftKNyRwXu5zFEZkceHCekTVf+dunhPYYeTA=,tag:oB3obwWmbFzm2fGJrLUsSA==,type:str]
      detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:TDuby5LrZ/Ttcl+hWA/p1e70YBLLMaG0,iv:kcJHftCehZK5ZTZlyMxhpwFLJtJT8Yn9GsLF9vZNjOU=,tag:wOI4wvLqRP5hUVV6toDl/g==,type:str]
      zvolEnableReservation: ENC[AES256_GCM,data:GrXA0wk=,iv:nLCVYkacnpp3r8FpJgpVa4Kt5QwoNs9JTa81GIFl/MQ=,tag:srPJnYnHg0rvZmDD9RT+WQ==,type:bool]
      zvolBlocksize: ENC[AES256_GCM,data:fHK5,iv:gcvH1+4QJHYGKcCe/K2yk8a1ar96UsgiP798YszoGKk=,tag:tiUr6rRojlwKLRm85gEjig==,type:str]
    iscsi:
      targetPortal: ENC[AES256_GCM,data:7rchbTLEUIHq6W6pRLWFhCRCAxjpHuqHGhSay4mw,iv:61RkCVuaHd8sBKzZoL7ei/k2ET9RhAsVdchJSI54WO8=,tag:ywQ/K53EeOwUC72pgnrKQw==,type:str]
      namePrefix: ENC[AES256_GCM,data:HAV4/w==,iv:aWeF3k64d82E31CTimefyjNfYaJJ2diHrr6hFKjueOw=,tag:GDAFpQZHI1kEb1/jGVTqDA==,type:str]
      targetGroups:
        - targetGroupPortalGroup: ENC[AES256_GCM,data:Sw==,iv:R7uW/HsDRZoqUC2U6uU6pPyWu+cOitbDOKmFuapOrek=,tag:tl7H6kFA+mXjqS/SbwNmDQ==,type:int]
          targetGroupInitiatorGroup: ENC[AES256_GCM,data:9Q==,iv:4TSEn2O86hZg/mY8kYY2tC9nLP73dQHk6HF6e79sJAs=,tag:RLYmyVjGu9bt4j210jcEAQ==,type:int]
          targetGroupAuthType: ENC[AES256_GCM,data:TzbFIA==,iv:xXod2Z3l/D96hn3eChHJPva48DPy6P9fv6aNS7mEO2c=,tag:oWCF5jpeTb+C4OYfiqBsNg==,type:str]
      extentInsecureTpc: ENC[AES256_GCM,data:kvse1A==,iv:b9ztG5l7YmOKwkAEazFiRPDHF+aSXMmR8TIQLSrJziY=,tag:lJBiUPZyiRNrsLkN6GT5sA==,type:bool]
      extentDisablePhysicalBlocksize: ENC[AES256_GCM,data:TvZOtA==,iv:i21YeH8sN8z3r9qBkZWA5hnsbDSETCJCmULRUeOwfjk=,tag:GjythEtImyPgRxHmYieA7Q==,type:bool]
      extentBlocksize: ENC[AES256_GCM,data:MPrP,iv:zbQa9vXaaUM2yRUI4nMS+sO5He10oGpXk0/wzhjNdms=,tag:hS3X+tmR6hXxQsi/I2/ojQ==,type:int]
      extentRpm: ENC[AES256_GCM,data:kA8F,iv:tnjZ3PnG1zL8GZHzJt+4AwSWvOrBNC4uMS49cze6ZM0=,tag:PJOe08WU8dR++YwU1BQPFw==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MS9sb2xSQ0VDUzU4WVlT
        NWxFSlhRcjRGVHp5RWFUWlp1YVdlN29WckFjCkJ1amZJOUx4SERLNlJtSzlsMjR0
        bzJiRGhsN2ZVT0poUVBtbk01MDZ0K0kKLS0tIERkZ2NzZ1B3My9xVXRacU80UVpD
        amYxdldocXIyZkVNSzNBZitwKzk0bzAK0TRuydCpEQ9NpqoaXPPi7J11fbWzIL7e
        SdTxwuZUcxaqoMDSaWofctgCX5XS7fAF59yPigFGqyWyUYsmZ9ENtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T11:10:43Z"
  mac: ENC[AES256_GCM,data:cAxzjEs4uQUVMU86IN01vVVqmEKQ/0vKw7NYNNGgEAWe8aR002NrYQFO8O6MA+BDvqNIZCOreqeswNbkBwPNlKWPmlIjGNPbKsCsIYTJML5F4oY6IkTinJ20rd86UMqhTys+df6MDZojsuLQfj29KFiY+wau2BL7xSJmtq0tdSY=,iv:3Tawb+KMbYPT9vsSanfDGlKK8Nbn24BHVUFZ9NSraNI=,tag:wl9N1WsAbyTRFEbG9D6UOQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
