extraCaCerts: ENC[AES256_GCM,data:/DSX2ZDDr4bqC5y9P0PQ4VF7j3zSLO7jotaG1d8S7Mg0Hoxtpz9eMK1W2Cnh/0UOLycIS7Emf2RgZQNXyzM/cMTez5eGy1OP1R0/BZ4kxLCnH6p/FA9fkiOpiOyqh4dILz1ZDUwHGPnXFJvhXj20yER84vX4/LI1jvbL3N1+X784sWcS9wjKby2H+cuivT1TU/G//sHn0RZM6jPrqwGHtENGuW5AgJ+QpMWn/fWPxOQgxsO6M5eh1LrrLJ2ArQHgiKpXoi4TdYtpi8OH/0YJgHc+hwRZDMcAH6cT7nJDjgGCp+igqQ8hgBQHGoPUrnh5L81T/mIyE3qkgspvBXCSx3YQBrLXd+D3d5x1cU57WFNA9SyGHT3aM+5wfdZnRDJYsv1LP3jyjNp8ihODDAEQvLAmiWyWh93oFu+7m6rT136KjCwf0Kf9fMWkhsVlzoFK1yAJ85Pu7ZF5uyGoB88IIu6XQ6UN+7a0HCeeDh4dLpvi5mHORMpHlB5RHdcfRPsUY/fKUNKe9V2shCD7VUTQfv44w3FcDqcv0sEmexJCHFHWHf9857MCsTFDbONeyRIIn81N9iWZBBKqVEAVa0YJ4iO1ZYvHPjkm/16QioFfFFuCcfbdBb1rRz2SGUHQi2atKiIJ06vJV06tGnMLZ79Ax/Phn8YyaSgrw4tIBdpGCBcX3cJCV4QTQ7r6wLM73+u4kTnADe6d5vcMgDi1GINN5L8nNsArnz3Sp6Vs2r5gCuLo4fowRFx283TSjLXE,iv:Slrv+ZqLiwv5HMVm1tupzy4ELI5SsOE39izzlZe3ArU=,tag:TCh/y7bCOsQ+I7pQzq5E2Q==,type:str]
csiDriver:
  name: ENC[AES256_GCM,data:rfqCeJjzzBEQzns2iaodGGKP,iv:wrLCs5RQJ6obJmlqLm2nIHwEdNaoxSE3oyPybEcWdFw=,tag:CT8MWZ7ksTxLQvcZNxtIvQ==,type:str]
storageClasses:
  - name: ENC[AES256_GCM,data:vsXmSDi+Iskr22DJbWSZUfSk,iv:ahmKknxZXT18khlYAcbNyhM2TQW294a8hDp67aYEab8=,tag:7aAANQ7hY19dNPi7qG8HCA==,type:str]
    defaultClass: ENC[AES256_GCM,data:WaErCF4=,iv:clGPp3ybhOpByvJm3J0SRuIC8vzoTL0x6WxTYwSyvLE=,tag:t5ZMjHAxP+3QXZMWWRpyvQ==,type:bool]
    reclaimPolicy: ENC[AES256_GCM,data:RDvrzJG3,iv:t3PdiAN+wGt4pksLn4RtFAxLROETh11nJjG9VbMR9WE=,tag:th74NWQjgG+OR9z+lPkXyw==,type:str]
    volumeBindingMode: ENC[AES256_GCM,data:hC4Pl3pKqYA2tv82UFIHqpav474=,iv:ztr24hD8zi6uFWy+pt7aPoBzd21yeBrKtKFzdywbD8I=,tag:ZA5mK+ru9QcIfHlCFyJlog==,type:str]
    allowVolumeExpansion: ENC[AES256_GCM,data:2qljsA==,iv:/p4ygcIuueYOyLoeuxUnWD1Ydd/NuVIficyb0GcQPyw=,tag:El/YQaNwERaanc0Qvr3cxQ==,type:bool]
    parameters:
      fsType: ENC[AES256_GCM,data:HN0OTA==,iv:G0NSKApPQGMFLKpC0MUy6JwgZW5EMx6BRQkBRaOqgAw=,tag:2UST8z8JKQ1lAG25h5nHBw==,type:str]
controller:
  driver:
    image:
      registry: ENC[AES256_GCM,data:5yYtGyF60zY/EihXBQs1QdflxPatbPYA/9SW0/RPa+xpbm930Gk=,iv:x5H9oIMdFCnsB/CalDLvNncbx11TU4YVIVh93Zc28b8=,tag:XVbQ0iXaXKJ+xEfthzICHA==,type:str]
      tag: ENC[AES256_GCM,data:8wAiFg==,iv:jV0oUHssUb7PBf5kQrAw9SxoxwNjtq71M1T5LBg9+Fg=,tag:0LKaHYi2ahuxP6WWkuILdg==,type:str]
      digest: ENC[AES256_GCM,data:L6RpizkKbiMpG4YVmWphKOutJix/BwTVSLZcTKKt9JdfpwB/LfyRhPsPrX/IImQU0asdeAke1WLcmEJ7hroEXamRoOcm2n0=,iv:P+nuo3Jf8rXju1MBt4T/e2R8v3FewwkRcrOVwgfU5+k=,tag:TeziDju8s9lkE6F4aMHR6g==,type:str]
node:
  driver:
    image:
      registry: ENC[AES256_GCM,data:AFdUpbC4G6W/7t5Umyq0ux2J1ciWp/VRiMDnx7TxOMjfVTvhbIE=,iv:+AwcfpEtT5vOoNCto6Ew+cCHGXaEkItEFXEE3owOViA=,tag:/4GrwvP4hs0DoJGGc9gsRQ==,type:str]
      tag: ENC[AES256_GCM,data:VhWxng==,iv:8yVjSKRK19BnFnQxUacilYY2dsyx5sQShN3Isx93wS0=,tag:pT5C2yCaueIPo+dyKo08Kg==,type:str]
      digest: ENC[AES256_GCM,data:XcuDGtmU0uLD5H2M5SSiUUVAnBPAwQAzP28kdYbBom5/EqvpF+HT1SfWIQMLAogl49mpAz+ZqzcRCXjYrSorQoMFAmVambM=,iv:nRtVT7nbYfq1njcPbFMcABG2jm9UHBobT2XD5bXhqtE=,tag:Mc3UjtjwyALA9x7QTj3uPA==,type:str]
driver:
  config:
    driver: ENC[AES256_GCM,data:X3osjl6WB1s6vAt0FTNtu6E=,iv:pJxcjPI+rxUYkjoXgxHdvNIUdU8I2gDUnu53keN1GpY=,tag:cSkGgHVg67DkHe0yoVdWZQ==,type:str]
    instance_id: ENC[AES256_GCM,data:MBHryrVwh3aXLT9uEw==,iv:uVL0ZHYutPRsM+xzA2/Sx/EJLaw1jyo7Uq94TYA7e2M=,tag:7RZpBZCvDVxivYtQhl/I7g==,type:str]
    httpConnection:
      protocol: ENC[AES256_GCM,data:iPcwX4c=,iv:jGpYVE7pGmzPCeILek9ltPJVpJ3HEc5R/9Lc5sh+qQA=,tag:LLzPpqOoP7NsC9J1hFe7bw==,type:str]
      host: ENC[AES256_GCM,data:0gcshcgSLMss8WvbYSSKF7qFHfixMmoDAg==,iv:aqsLXtHfjY8d2l4d+CufllE23ITUF743h4G0Xu5ejLA=,tag:+7Fe0lF5IHC/E3+J4VcTHA==,type:str]
      port: ENC[AES256_GCM,data:BcVr,iv:OeCX04/x0R8/bbDruJYBRjGLzpUhrCrDAzX5ZvSBVr0=,tag:a3KW//svOaIDUbuaPv/T0w==,type:int]
      apiKey: ENC[AES256_GCM,data:Q1Vcd7kZmbcub8ZyVhaNcwX18tHr9U6fMqjP/CTmHi3e81WbWjl/2MZyETNvf7SQCFjSyJNHAJyZalVAB24FTz8t,iv:28NcGAfimlufOtt4qNkSisstsgV3bt0JAxmozYnR7gI=,tag:TMz0vFu6EUwG8Z+udD6pzg==,type:str]
      apiVersion: ENC[AES256_GCM,data:Cg==,iv:wvDHnYu05MJWGkr3CnMcB0HOHxNpSrYlQOjM5Mdfqa0=,tag:WNkGXxNAQq4NtpSyxVz8Tg==,type:int]
    zfs:
      datasetParentName: ENC[AES256_GCM,data:B/K/I9w13G3QSOcdM8w=,iv:s/x4LwQSIO3P8Ghq8tjQu6DL2n3lCxSKsahhVc8GhU8=,tag:vSKr4SZ6ZjPsxapAxI5DOw==,type:str]
      detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:Qlz1gY0Rn+OukVE0RFMnd2rEqqqfTejj,iv:GgAymNYkJcGi+jyEob1NRgbj8tsUPEEgHMoCRmermU4=,tag:564PmLtnojM2B0X0OcX1IA==,type:str]
      zvolEnableReservation: ENC[AES256_GCM,data:ZkYJ9ec=,iv:etYDvu7Z8dVdJk3YzVUs2en5965CNr9ImZQut92u61M=,tag:UdWG7ZEdx0GGEerFIqA/GA==,type:bool]
      zvolBlocksize: ENC[AES256_GCM,data:JtCQ,iv:ywwNm7OthSqqzesksASbx9KJNAHtdrdNvjA/SidKPoU=,tag:id7ODWY86EWhCW8bIomP9Q==,type:str]
    iscsi:
      targetPortal: ENC[AES256_GCM,data:rm/a9eMv5e5hrKJuvyxg6iQee2QOyQgde6G4ZQc0,iv:4Zy+ygUz4s5hmJBSn6vFaTUSvc8V934zzU1ETdOLbV4=,tag:X/LZN0RElpo278pyeJznjw==,type:str]
      namePrefix: ENC[AES256_GCM,data:xFMdGg==,iv:Alvbr8wfN+R1C73HRJFc2UHp8ZYnKpeDC2SdZQ1y+yo=,tag:UlstVAlOc0JU0D97kGsDgw==,type:str]
      targetGroups:
        - targetGroupPortalGroup: ENC[AES256_GCM,data:ug==,iv:3zMXYoDvwYtPLLKq2syGD5BqYiLo43Ca6cuaDRAm6x8=,tag:git/2EzFQgfb9yXh57BLxQ==,type:int]
          targetGroupInitiatorGroup: ENC[AES256_GCM,data:Sg==,iv:NYKkM+w/gyNioxGfjZ5aTZqf2onRYS5LOuVl/ZMP0Uc=,tag:DbptS5XcaGiwK5lNvj1Mkw==,type:int]
          targetGroupAuthType: ENC[AES256_GCM,data:/v526Q==,iv:kSofV/sNFC84ZExEtMBM0kA4UGrDWNpGQqQp/1GBPo0=,tag:Pkhjo1oQF4B389zUTKQgBA==,type:str]
      extentInsecureTpc: ENC[AES256_GCM,data:8cGbcg==,iv:y3arFBrUIVHgyZi5Kjyc+bPC5xGjTsnY61EQ62MRBvs=,tag:qpHdrVKSl4wbJO1y/YwXGA==,type:bool]
      extentDisablePhysicalBlocksize: ENC[AES256_GCM,data:uJbakQ==,iv:MhgqiK1Fl/y3aQ/TK/A9VZXk90RNanm4Y3b8N3is/So=,tag:uFgZh9MIgaHgNbMgPkM4xQ==,type:bool]
      extentBlocksize: ENC[AES256_GCM,data:bRvB,iv:qDwBTBuml8V801GZYoGV4DfUES0C+dZdU6bJQwL+3ZQ=,tag:I4NcQ46FZl67bgzldnK/Ow==,type:int]
      extentRpm: ENC[AES256_GCM,data:RJdg,iv:yUKUWaHcVq8ZYwR+Ff/srGx8WBuipS+hBl7tDHQirC4=,tag:/zoiErkfiJ3uTt6N4rNJnw==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrME55ZFdSU0pCM2VBNnNj
        UzltdkI5bXZrRDNrTHlNenNJcVhZZUxGT3dVClNiVTZPKzU1U294eWRoNWNLQlpC
        RVh1bnJxZnVRLzZrbEk1MXpOS1JRYVUKLS0tIHNPcUtLeDJuSW16VHVBTVQvbDRH
        YUllTUZPbTNTVkFLcEkwQVhZUEVFRFkKdVTXXhs6wO2ILpRPEoEDNicLjqpMwmti
        jdPaMEHrpP+lidnRem5GjC79g2YYPKft81T9U7v4a/5LttH8yzxwIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T11:39:44Z"
  mac: ENC[AES256_GCM,data:Pfn24NPGBfjjWglZdwkxrmvEcDu7QZHJ0mDNfPE0o8aiZboApYvveZQOlK3+Iyim4beFIzY/CxY4bQKXXiAKuxKDEycA7lMPnYu8jVRlN3mzwrQlZrhddfgN3fPz52ByJFOSqA7IFq+wIPnajvGAnpcl0DeNIZiLBFfUWtB/SKc=,iv:4WLEnhT2lR6LIO9B3uOSJUR3TuAcEhZY5cDGMl2zQb8=,tag:OACz7Mx2tUfYLPvbhIGf9A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
