apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-acme
spec:
  acme:
    server: https://ca.trantor.home.arpa/acme/acme/directory
    email: vdwemil@protonmail.com
    privateKeySecretRef:
      name: step-acme-account
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlakNDQVNDZ0F3SUJBZ0lSQUpzSW5QT0NVTU9PM1d5cm1PcG5IaFl3Q2dZSUtvWkl6ajBFQXdJd0dqRVkKTUJZR0ExVUVBeE1QU0c5dFpXeGhZaUJTYjI5MElFTkJNQ0FYRFRJMU1USXhPVEUzTXpNeU5Gb1lEekl3TlRVeApNakV5TVRjek16STBXakFhTVJnd0ZnWURWUVFERXc5SWIyMWxiR0ZpSUZKdmIzUWdRMEV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUYlVuL1lIeVNmNjI1Uzd5M2xYY2Z2eUZRcHJtZ1lFUGZRVHNRT3kwNEwKRU5DdjJLdUlkU3g0OWhWR0NrMXJjSEtueHcwdEVWc3pvQUF6aU1aOGwwSUdvMFV3UXpBT0JnTlZIUThCQWY4RQpCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFUQWRCZ05WSFE0RUZnUVVGRGV3T1ZEYnlwdXFocGJQCkRqQ0lMMFJkZ1Q0d0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ1FjalI4a09ZMk13aUFISHJCYWFtbXNieEd0OUUKVHNyb29YREphM2JRRWwwQ0lRQ2RUUmJYcWxVQWN0ci9Dc291STc1QzJsU1o5cjYvK1QzeHFPOFhiQ1dmaUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

    solvers:
      - http01:
          ingress:
            class: traefik
            ingressTemplate:
              metadata:
                annotations:
                  kubernetes.io/ingress.class: traefik
