apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-acme
spec:
  acme:
    server: https://ca.trantor.home.arpa/acme/acme/directory
    email: vdwemil@protonmail.com
    privateKeySecretRef:
      name: step-acme-account
    solvers:
      - http01:
          ingress:
            class: traefik
