apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: internal-step-root
  namespace: cert-manager
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: step-root-ca
        key: ca.crt
  target:
    configMap:
      key: ca-bundle.pem
