extraCaCerts: ENC[AES256_GCM,data:vEqtjacoLv9YKmIX96rQPb6CSpTeYgv+TTk3/flkbj26oFpt+4xD9htti/Q02FibeNPhqYolTzdqkO8GMmWjx/afRS/cjEE9T5Bn7ESTag/N5InkBdvK9Jq/ZO1tzLBPiIoqh0vPGIvUSo5cLOoO+3N2FR+QQC5z1XqvWuszVZLHBEexN6V42GiYywloFGiu8PLkGZcX6HNnHed4wr3m7UBpDdEInLCNK5iwxf+Reh2LotU2yRRvxghEQXJTGq2h+UwOFRPbT0YqhWtpbxW5Qhz2pv2iavq2u9bPhehigrREL7aofJxJJF5ry2fVJ6drWr2B2OLMIUrS+MX/z9g+7KxzZ4vnr3Tg7+go69gcXel0NrlspQe3BfduGkeYXfqD34JiBemyzNRVBFfFAgazqH4id/XTQWiAf0EV+RRgEpGLd2YwKdlRcg6Q5oXRczDrKGvMxCzka99S7goxq536xDIH8ZM+hiEyzpc0Qos6lW0oiHJDvlLNv/yPyWOtJLTMzZoYImpJ16MBTEOF1EwEkDOiXwRI/hKYXL5dYLtHGjb3LS/qtMDcbyE9wRXxz7xIwe0NhKwGGzvRNtaNrf20v1cm1g9PWclOaNkfvTHmOy4OOTwzR++sVoKsAKRFIZ16wn0Gp8DKynTzZjLG5NEGDaOSSxHjs6IAkQt5Ke/yewWthNPUbwJxrJ/kdnR+OT5bduNeZNVZX2yBNA1mE1nxKzCefKanN8zPye6lsaZjbjrFxvHDw27Mm6fj7jCI,iv:D2D4BYJqnvOdGGEkzEu56HuFXNLgSbFJUobeP+HPin4=,tag:WkkP92nBRu9Unp0euTgd+A==,type:str]
csiDriver:
  name: ENC[AES256_GCM,data:hzysLy6nAdHRdBirmfSeog==,iv:8IQnhVTBivOEoIDne8GDU6A0+cVOby9DIvYONAhk1yI=,tag:x69UgMx55jcmBh2lzr2YTw==,type:str]
  fsGroupPolicy: ENC[AES256_GCM,data:nCPINA==,iv:1qDX9flCDs7NhGLFOnVXWrjFjuaO6D3HkX2NE4ZVfok=,tag:0N2vwfknlgviyKxB/0U8Ag==,type:str]
storageClasses:
  - name: ENC[AES256_GCM,data:Vj7pe9ChcTU5hD0SwODyAA==,iv:te4RN9yLhjDUnImmcTHnmrZyoNfLTCmvsmXvEOh3aik=,tag:W3MByTIgcfd7YuxYa+KHFw==,type:str]
    defaultClass: ENC[AES256_GCM,data:Gdfq8Sc=,iv:VIbFPplmGXt8LJ/oX0Z/TRV/flXZlCb7Tx5jaPiUhhg=,tag:5UdJTksrN444Xvkn5d16PA==,type:bool]
    reclaimPolicy: ENC[AES256_GCM,data:LCCStaix,iv:RPnsb7nI2Hq3ONaw5ta2rB7I8QS/JgNTB0NEMU0ctx8=,tag:CywMgHOjHbSjAQ2ReoT7Fg==,type:str]
    volumeBindingMode: ENC[AES256_GCM,data:+ouRvf6Ndjbg,iv:hddQbPrHt2F0/PC6udXdwrrQjvAAObAVRm2ese0HC7Y=,tag:a3i8bhxNvQJVQa2/Q1evcQ==,type:str]
    allowVolumeExpansion: ENC[AES256_GCM,data:Z2Ka6g==,iv:Rx+qw06fYI6MFnXFwQiK4d7y8zgE8xXfxTpCF85uhrY=,tag:Em1jOXkAgBDlfC7IbNWuDA==,type:bool]
    parameters:
      fsType: ENC[AES256_GCM,data:o7AJ,iv:gNbZEgIk15G7b0UZ4GkMgdiNn0CgQhfL6VKqC8h7bsc=,tag:9EIQ+hj4MJitCn6471gL6w==,type:str]
    mountOptions:
      - ENC[AES256_GCM,data:ywQyU5TaNw==,iv:LR4/aioQHfnJYq0sCphKkIKuyhi2ot+dNc82Syn5s1M=,tag:kGZAuiTiw6rx1TjT6qJTBw==,type:str]
      - ENC[AES256_GCM,data:vdJEBBmFBuIX,iv:p8YIJEdyM9epmTi8LT4O13gnCp9Ck8p2Gx1qh58wQ7g=,tag:4aJmD77WiV9EJ8VhHgZaoA==,type:str]
controller:
  driver:
    image:
      registry: ENC[AES256_GCM,data:cLkkJ0W0WF2XrQ8erdi5L/fEOdvGVovSY0nr5uFwgrr0iHw3Mug=,iv:or0fwmgLxqoK0nqQbr4odLpKsrxvBXV/iUQZNnu4q3c=,tag:gn9HjEg3xc4O844RBHjVug==,type:str]
      tag: ENC[AES256_GCM,data:2DXzcA==,iv:MjD47V7E9nN2l0z/qzAzG1BwVhPopv2ycxg71XuzXuc=,tag:1tXWF2Krcln4XquK54FURg==,type:str]
      digest: ENC[AES256_GCM,data:K8Tv4Ehxsl9j6iFxhZUxlFkkf157BtUWiLoD29RvGb0fZNd7YFvz5cy2dFYtPbeRz/XEPylqLukF/RewJRyFWbZqUKN5h8Q=,iv:f4nrNYxZKHB2XEHtrZu054VTwEx4gWNKz2AUEfCV3cA=,tag:TFQcSbG04IGdMdxTBpLmlQ==,type:str]
node:
  driver:
    image:
      registry: ENC[AES256_GCM,data:sykoRPcDT/QGA08ryeA4tKj3RrzV67Zkk8BmL8Un81mxbqNRAX0=,iv:0DF1xK6mhYGxh1+2F68mpyG62i16zDmQPY0GtGgpJbo=,tag:6hioZpNHugmDxKv0eeyMNg==,type:str]
      tag: ENC[AES256_GCM,data:4XlfHQ==,iv:8PHPf5FhisCkytjYwS4Zs4BuiuYehmvSm3ktYeqwqh0=,tag:8G09yHjVL13m2FR56SqsKg==,type:str]
      digest: ENC[AES256_GCM,data:ObkJHJfHIbg6/HrVWHYjpnA6Q444Kex53erKLs7Z2p73/hMEQVt3/Mwp9fK/powyV/8NRbe4ZhTMMp5VQY9YtyBvSVvy4lk=,iv:1QomlX0y7eEcqnuHqxhHRzKIonRTNUBpV1tUxero41I=,tag:EI3AA9L7tA+bVUDNJj4Nhg==,type:str]
driver:
  config:
    driver: ENC[AES256_GCM,data:TLRieoUsPI7O4JRicbWy,iv:QpAKEoj/30E/DG2e0QAnzQrNzk+cWJ6pVe73pM4qe6E=,tag:KGvM/QmNNG46bVVxfq/odw==,type:str]
    instance_id: ENC[AES256_GCM,data:4aAUmfYkd0RR1Ws=,iv:6V25fXi0chsp0kQCMkLTH9oS/siLdtkPs6eEo4lT/mU=,tag:1YcFSEUlyorzIUTdWr8ekA==,type:str]
    httpConnection:
      protocol: ENC[AES256_GCM,data:Z3hsugA=,iv:QEX1aHSWZnpnON9K7F+T/+uLKsH6Ik4OKdg+FxWbS80=,tag:bEIdBfANe50B52QnPd8dQA==,type:str]
      host: ENC[AES256_GCM,data:13Cuw8PZPrjCG6drmuHyU74zMA3jgQpG6g==,iv:r7KCGTuIBFgQ6oRaiEiY4B2qpHnhojkIfZDBTY8C0wo=,tag:ayd7rXvTdluqgx3s4oshMQ==,type:str]
      port: ENC[AES256_GCM,data:PPBc,iv:yID3X8UdqzEusX4jYa9V04fhvS38iXQlcDUtzXE88b4=,tag:0h9JJ3uNhfJNSSLZa9TBhA==,type:int]
      apiKey: ENC[AES256_GCM,data:sjQYR2ZjbO/a6GKNCdyKuxyoA+37u3qFA+ay7aGjJJQSiF+uD5bRsv/BCKTKeXnh1AVMHn2rj3tQnEoh0mUgGvUe,iv:3hS2lDjI3U1IJGnKzvRjrNHUKhyfvGGVWIs688MyJ58=,tag:5Zj3syxtTMpZGwRPT9ORow==,type:str]
      apiVersion: ENC[AES256_GCM,data:Mw==,iv:S55nzsUz90soD0aZ49XLsLDXG99QGPeDLR1vlQcLufA=,tag:JCphk4CcBzyW6eF7urvbUw==,type:int]
    zfs:
      datasetParentName: ENC[AES256_GCM,data:uslyvuNHNDHpvbnu,iv:rmKyXQ8dQOu5qFb6WuAJUp5a8zO0igS0IeJUaSGGdbo=,tag:n9oO2lO/yQjltBtivoWK9g==,type:str]
      detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:Ub+qbOXeKjGb2aAUFqY5+Pzu7Cv89g==,iv:lRHdanbabT5AaxacEo6CZVAqKBNmTXxsLeCBVO5LQQU=,tag:xkB61IfYuduwxdNtXbsdKw==,type:str]
      datasetEnableQuotas: ENC[AES256_GCM,data:e3/NNQ==,iv:ImelLBa7xqHdSpjUHAp+zq/pHWdDCKcRRgG6zABmjbk=,tag:A6KyBfHtzN2AWHYL7oyN0w==,type:bool]
      datasetPermissionsMode: ENC[AES256_GCM,data:lZbilA==,iv:1bxXeO2WQ4PRGDZqHTJUQAYpUeGQqdAQkH9Qw8iHZnE=,tag:neOccFd78oc69O4zhdaAnA==,type:str]
      datasetPermissionsUser: ENC[AES256_GCM,data:XA==,iv:woxLSu06Fg3Vsht/KSGbNAp4For2bwKZBAEHZQlbuys=,tag:girQGdXHJgO5xjsmt0lXTw==,type:int]
      datasetPermissionsGroup: ENC[AES256_GCM,data:pg==,iv:G9ySvECDIQ5RdcI1NYC3VlePsKvd65e7ZCqV7wAqJWc=,tag:zZjDvVkukbjEEsCxpuaX1A==,type:int]
    nfs:
      shareHost: ENC[AES256_GCM,data:N+hb+Yhyt2qk3oOmW1uPLdjHLw2YU7C75Q==,iv:0paor3RvedyUn+cu3hoQswDSOrUvvnAhnQlQ/ZJEzms=,tag:BmUX+J7GdwjhA5HQ65mnSw==,type:str]
      shareMaprootUser: ENC[AES256_GCM,data:9q4sYg==,iv:Y0F2uKtEUW3P1D7XMnpOmtXKFmB1Xil7cWlxk0kLZjY=,tag:a8fHtGwM1holydw6GDDhOw==,type:str]
      shareMaprootGroup: ENC[AES256_GCM,data:K/V8aQ==,iv:7hMO6f/U7gMiiwDfT05PdGCyKk1NLvWIwRyVAhcZ2IE=,tag:r4Xcn/kX5xwDUM533jFOIw==,type:str]
sops:
  age:
    - recipient: age1am0hru25ljjzpf37x8p8v3953qvpjp7ve9f5rwx0fzpjqagfjpqs55kkug
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0K01mcTFxSElyTTFtWVdz
        ZllYU2NvRGszQTY5cWx5dFFCWDlKdUkxS1ZJCm5EK2ZDdHQxcjAwNU1zWVd5Nk1o
        MkRIRjUzM2dqUCs1eWRGNGdVQ1BEMDAKLS0tIFBrWGE0NVFrYXhpd1ZJV1BNQXFT
        R1Q4WEdoaUhxSFd3RFN2RUxhMzlIMGcKrfw0zqbRJmqKHAF2oz68z1pwxV4bm4El
        q+45x5MV9MENiZG80XEQmtj3SJykHS8fi3Omcn+bw0Le/noUQXwsOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T15:08:50Z"
  mac: ENC[AES256_GCM,data:2SXcT/XIGGhY0RyWqO0oh1P4CBYc7t8aYUSnMwvMRnsXduNyTnkk8L70w0rbD6mmfTb/1GLRU8qZwdJCehJ5e72ZfIGidaGyWNn6mvtkFPMZc2RPgafQcBZ6eaQc3cocoT+mf4NsP6hy4+ckKkf7c183Dhoq5eNlStMHXWJfG8E=,iv:gsA14TozoLzt4gxC3FaqgFF6b8z2lRXMBwp1A15GtFw=,tag:9gsVLgo2xI4UQZreJfU89w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
